@echo off
copy "release\finder\widget.min.js"      "..\src\main\resources\resource\finder\widget.js"
copy "release\finder\finder.min.js"      "..\src\main\resources\resource\finder\finder.js"
copy "release\finder\grep.min.js"        "..\src\main\resources\resource\finder\grep.js"
copy "release\finder\less.min.js"        "..\src\main\resources\resource\finder\less.js"
copy "release\finder\tail.min.js"        "..\src\main\resources\resource\finder\tail.js"
copy "release\finder\base64.min.js"      "..\src\main\resources\resource\finder\base64.js"
copy "release\finder\charset.min.js"     "..\src\main\resources\resource\finder\charset.js"
copy "release\finder\colorpicker.min.js" "..\src\main\resources\resource\finder\colorpicker.js"
copy "release\finder\config.min.js"      "..\src\main\resources\resource\finder\config.js"
copy "release\finder\display.min.js"     "..\src\main\resources\resource\finder\display.js"
copy "release\finder\fileupload.min.js"  "..\src\main\resources\resource\finder\fileupload.js"
copy "release\finder\index.min.js"       "..\src\main\resources\resource\finder\index.js"
copy "release\finder\password.min.js"    "..\src\main\resources\resource\finder\password.js"
copy "release\finder\scrollpage.min.js"  "..\src\main\resources\resource\finder\scrollpage.js"
copy "release\finder\signin.min.js"      "..\src\main\resources\resource\finder\signin.js"
copy "release\finder\tab.min.js"         "..\src\main\resources\resource\finder\tab.js"
copy "release\finder\tree.min.js"        "..\src\main\resources\resource\finder\tree.js"
copy "release\finder\split.min.js"       "..\src\main\resources\resource\finder\split.js"
copy "release\finder\img-viewer.min.js"  "..\src\main\resources\resource\finder\img-viewer.js"
copy "release\finder\zip-viewer.min.js"  "..\src\main\resources\resource\finder\zip-viewer.js"
copy "release\finder\editor.min.js"      "..\src\main\resources\resource\finder\editor.js"
copy "release\finder\editplus.min.js"    "..\src\main\resources\resource\finder\editplus.js"

copy "release\finder\media\index.min.js" "..\src\main\resources\resource\finder\media\index.js"
copy "release\finder\media\media.min.js" "..\src\main\resources\resource\finder\media\media.js"
@pause
