/*
 * $RCSfile: AdminTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;



/**
 * <p>Title: AdminTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class AdminTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final AdminTemplate instance = new AdminTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_77072, 0, _jsp_77072.length);
        out.write(_jsp_77073, 0, _jsp_77073.length);
        out.write(_jsp_77074, 0, _jsp_77074.length);
        out.write(_jsp_77075, 0, _jsp_77075.length);
        out.write(_jsp_77076, 0, _jsp_77076.length);
        out.write(_jsp_77077, 0, _jsp_77077.length);
        out.write(_jsp_77078, 0, _jsp_77078.length);
        out.write(_jsp_77079, 0, _jsp_77079.length);
        out.write(_jsp_77080, 0, _jsp_77080.length);
        out.write(_jsp_77081, 0, _jsp_77081.length);
        out.write(_jsp_77082, 0, _jsp_77082.length);
        out.write(_jsp_77083, 0, _jsp_77083.length);
        out.write(_jsp_77084, 0, _jsp_77084.length);

        out.flush();
    }

    protected static final byte[] _jsp_77072 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_77073 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_77074 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_77075 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_77076 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/finder.css\"/>\r\n");
    protected static final byte[] _jsp_77077 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_77078 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/widget.js\"></script>\r\n");
    protected static final byte[] _jsp_77079 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/admin.js\"></script>\r\n");
    protected static final byte[] _jsp_77080 = b("</head>\r\n<body style=\"overflow: hidden;\">\r\n<div id=\"view-panel\" split=\"x\">\r\n    <div id=\"left-panel\" class=\"left-panel\"><iframe id=\"left-frame\" name=\"leftFrame\" class=\"left-frame\"\r\n");
    protected static final byte[] _jsp_77081 = b("        src=\"?action=admin.menu\" frameborder=\"0\" scrolling=\"no\" marginwidth=\"0\" marginheight=\"0\"></iframe></div>\r\n");
    protected static final byte[] _jsp_77082 = b("    <div id=\"main-panel\" class=\"main-panel\"><iframe id=\"main-frame\" name=\"mainFrame\" class=\"main-frame\"\r\n");
    protected static final byte[] _jsp_77083 = b("        src=\"?action=admin.system.info\" frameborder=\"0\" scrolling=\"auto\" marginwidth=\"0\" marginheight=\"0\"></iframe></div>\r\n");
    protected static final byte[] _jsp_77084 = b("</div>\r\n</body>\r\n</html>\r\n");

}
