/*
 * $RCSfile: ConfigEditTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;
import com.skin.finder.config.ConfigFactory;


/**
 * <p>Title: ConfigEditTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class ConfigEditTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final ConfigEditTemplate instance = new ConfigEditTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_19445, 0, _jsp_19445.length);
        out.write(_jsp_19446, 0, _jsp_19446.length);
        out.write(_jsp_19447, 0, _jsp_19447.length);
        out.write(_jsp_19448, 0, _jsp_19448.length);
        out.write(_jsp_19449, 0, _jsp_19449.length);
        this.write(out, (App.hash()));
        out.write(_jsp_19451, 0, _jsp_19451.length);
        out.write(_jsp_19452, 0, _jsp_19452.length);
        this.write(out, (App.hash()));
        out.write(_jsp_19454, 0, _jsp_19454.length);
        out.write(_jsp_19455, 0, _jsp_19455.length);
        out.write(_jsp_19456, 0, _jsp_19456.length);
        out.write(_jsp_19457, 0, _jsp_19457.length);
        out.write(_jsp_19458, 0, _jsp_19458.length);
        out.write(_jsp_19459, 0, _jsp_19459.length);
        out.write(_jsp_19460, 0, _jsp_19460.length);
        out.write(_jsp_19461, 0, _jsp_19461.length);
        out.write(_jsp_19462, 0, _jsp_19462.length);
        out.write(_jsp_19463, 0, _jsp_19463.length);
        out.write(_jsp_19464, 0, _jsp_19464.length);
        out.write(_jsp_19465, 0, _jsp_19465.length);
        out.write(_jsp_19466, 0, _jsp_19466.length);
        out.write(_jsp_19467, 0, _jsp_19467.length);
        out.write(_jsp_19468, 0, _jsp_19468.length);
        out.write(_jsp_19469, 0, _jsp_19469.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_19471, 0, _jsp_19471.length);
        out.write(_jsp_19472, 0, _jsp_19472.length);
        out.write(_jsp_19473, 0, _jsp_19473.length);
        out.write(_jsp_19474, 0, _jsp_19474.length);
        out.write(_jsp_19475, 0, _jsp_19475.length);
        this.write(out, (ConfigFactory.getSessionTimeout()));
        out.write(_jsp_19477, 0, _jsp_19477.length);
        out.write(_jsp_19478, 0, _jsp_19478.length);
        out.write(_jsp_19479, 0, _jsp_19479.length);
        this.write(out, (ConfigFactory.getTextType()));
        out.write(_jsp_19481, 0, _jsp_19481.length);
        out.write(_jsp_19482, 0, _jsp_19482.length);
        out.write(_jsp_19483, 0, _jsp_19483.length);
        this.write(out, (ConfigFactory.getOperateButton()));
        out.write(_jsp_19485, 0, _jsp_19485.length);
        this.write(out, (ConfigFactory.getOperateButton()));
        out.write(_jsp_19487, 0, _jsp_19487.length);
        this.write(out, (ConfigFactory.getOperateButton()));
        out.write(_jsp_19489, 0, _jsp_19489.length);
        this.write(out, (ConfigFactory.getOperateButton()));
        out.write(_jsp_19491, 0, _jsp_19491.length);
        this.write(out, (ConfigFactory.getOperateButton()));
        out.write(_jsp_19493, 0, _jsp_19493.length);
        this.write(out, (ConfigFactory.getOperateButton()));
        out.write(_jsp_19495, 0, _jsp_19495.length);
        out.write(_jsp_19496, 0, _jsp_19496.length);
        out.write(_jsp_19497, 0, _jsp_19497.length);
        out.write(_jsp_19498, 0, _jsp_19498.length);
        this.write(out, (ConfigFactory.getUploadPartSize()));
        out.write(_jsp_19500, 0, _jsp_19500.length);
        out.write(_jsp_19501, 0, _jsp_19501.length);
        out.write(_jsp_19502, 0, _jsp_19502.length);
        this.write(out, (ConfigFactory.getDemoUserName()));
        out.write(_jsp_19504, 0, _jsp_19504.length);
        out.write(_jsp_19505, 0, _jsp_19505.length);
        out.write(_jsp_19506, 0, _jsp_19506.length);
        this.write(out, (ConfigFactory.getDemoPassword()));
        out.write(_jsp_19508, 0, _jsp_19508.length);
        out.write(_jsp_19509, 0, _jsp_19509.length);
        out.write(_jsp_19510, 0, _jsp_19510.length);
        this.write(out, (ConfigFactory.getUpdateCheck()));
        out.write(_jsp_19512, 0, _jsp_19512.length);
        out.write(_jsp_19513, 0, _jsp_19513.length);
        out.write(_jsp_19514, 0, _jsp_19514.length);
        out.write(_jsp_19515, 0, _jsp_19515.length);
        out.write(_jsp_19516, 0, _jsp_19516.length);

        out.flush();
    }

    protected static final byte[] _jsp_19445 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_19446 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_19447 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_19448 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_19449 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css&v=");
    protected static final byte[] _jsp_19451 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_19452 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js&v=");
    protected static final byte[] _jsp_19454 = b("\"></script>\r\n<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    var getOperateButton = function() {\r\n");
    protected static final byte[] _jsp_19455 = b("        var b = [];\r\n\r\n        jQuery(\"input[name=operateButton]:checked\").each(function() {\r\n");
    protected static final byte[] _jsp_19456 = b("            b[b.length] = this.value;\r\n        });\r\n        return b.join(\", \");\r\n");
    protected static final byte[] _jsp_19457 = b("    };\r\n\r\n    jQuery(\"#submit\").click(function() {\r\n        var params = {};\r\n        params.sessionTimeout = jQuery.trim(jQuery(\"input[name=sessionTimeout]\").val());\r\n");
    protected static final byte[] _jsp_19458 = b("        params.operateButton = getOperateButton();\r\n        params.textType = jQuery.trim(jQuery(\"input[name=textType]\").val());\r\n");
    protected static final byte[] _jsp_19459 = b("        params.uploadPartSize = jQuery.trim(jQuery(\"input[name=uploadPartSize]\").val());\r\n");
    protected static final byte[] _jsp_19460 = b("        params.demoUserName = jQuery.trim(jQuery(\"input[name=demoUserName]\").val());\r\n");
    protected static final byte[] _jsp_19461 = b("        params.demoPassword = jQuery.trim(jQuery(\"input[name=demoPassword]\").val());\r\n");
    protected static final byte[] _jsp_19462 = b("        params.updateCheck = jQuery(\"input[name=updateCheck]\").prop(\"checked\");\r\n");
    protected static final byte[] _jsp_19463 = b("\r\n        jQuery.ajax({\r\n            \"type\": \"post\",\r\n            \"url\": \"?action=admin.config.save\",\r\n");
    protected static final byte[] _jsp_19464 = b("            \"dataType\": \"json\",\r\n            \"data\": jQuery.param(params, true),\r\n");
    protected static final byte[] _jsp_19465 = b("            \"error\": function() {\r\n                alert(\"系统错误，请稍后再试！\");\r\n            },\r\n");
    protected static final byte[] _jsp_19466 = b("            \"success\": function(response) {\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_19467 = b("                    alert(response.message);\r\n                }\r\n                else {\r\n");
    protected static final byte[] _jsp_19468 = b("                    alert(\"保存并同步成功！\");\r\n                }\r\n                window.location.reload();\r\n");
    protected static final byte[] _jsp_19469 = b("            }\r\n        });\r\n    });\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_19471 = b("\">\r\n<div class=\"menu-bar\">\r\n    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_19472 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_19473 = b("    <span class=\"seperator\"></span>\r\n</div>\r\n<div class=\"form\">\r\n    <div class=\"title\"><h4>系统设置 - 一般设置</h4></div>\r\n");
    protected static final byte[] _jsp_19474 = b("    <div class=\"form-row\">\r\n        <div class=\"form-label\">会话有效期：</div>\r\n        <div class=\"form-c400\">\r\n");
    protected static final byte[] _jsp_19475 = b("            <div class=\"form-field\">\r\n                <input name=\"sessionTimeout\" type=\"text\" class=\"text w300\" placeholder=\"0s\" value=\"");
    protected static final byte[] _jsp_19477 = b("\"/>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">用户登录的有效期。可选单位: [d: 天, h: 时, m: 分, s: 秒]；单位不区分大小写, 无单位或者其他都按照秒处理。支持小数形式。</div>\r\n");
    protected static final byte[] _jsp_19478 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">允许打开的文本类型：</div>\r\n");
    protected static final byte[] _jsp_19479 = b("        <div class=\"form-c400\">\r\n            <div class=\"form-field\">\r\n                <input name=\"textType\" type=\"text\" class=\"text w300\" placeholder=\"5M\" value=\"");
    protected static final byte[] _jsp_19481 = b("\"/>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">允许使用tail，less，grep打开的文本文件类型，逗号分隔。\"*\"表示全部。</div>\r\n");
    protected static final byte[] _jsp_19482 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">显示操作按钮：</div>\r\n");
    protected static final byte[] _jsp_19483 = b("        <div class=\"form-c400\">\r\n            <div class=\"form-field\">\r\n                <p><input name=\"operateButton\" type=\"checkbox\" checked-value=\"");
    protected static final byte[] _jsp_19485 = b("\" value=\"tail\"/> tail</p>\r\n                <p><input name=\"operateButton\" type=\"checkbox\" checked-value=\"");
    protected static final byte[] _jsp_19487 = b("\" value=\"less\"/> less</p>\r\n                <p><input name=\"operateButton\" type=\"checkbox\" checked-value=\"");
    protected static final byte[] _jsp_19489 = b("\" value=\"grep\"/> grep</p>\r\n                <p><input name=\"operateButton\" type=\"checkbox\" checked-value=\"");
    protected static final byte[] _jsp_19491 = b("\" value=\"open\"/> open</p>\r\n                <p><input name=\"operateButton\" type=\"checkbox\" checked-value=\"");
    protected static final byte[] _jsp_19493 = b("\" value=\"download\"/> download</p>\r\n                <p><input name=\"operateButton\" type=\"checkbox\" checked-value=\"");
    protected static final byte[] _jsp_19495 = b("\" value=\"delete\"/> delete</p>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n");
    protected static final byte[] _jsp_19496 = b("            <div class=\"form-comment\">显示的操作按钮, 文件列表项后面的操作按钮。</div>\r\n        </div>\r\n");
    protected static final byte[] _jsp_19497 = b("    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">文件上传分片大小：</div>\r\n");
    protected static final byte[] _jsp_19498 = b("        <div class=\"form-c400\">\r\n            <div class=\"form-field\">\r\n                <input name=\"uploadPartSize\" type=\"text\" class=\"text w300\" placeholder=\"5M\" value=\"");
    protected static final byte[] _jsp_19500 = b("\"/>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">可选单位: [b: 字节, k: 千字节, m: 兆字节, g: 千兆字节]，单位不区分大小写, 无单位或者其他都按照字节处理。支持小数形式。</div>\r\n");
    protected static final byte[] _jsp_19501 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">演示账号：</div>\r\n");
    protected static final byte[] _jsp_19502 = b("        <div class=\"form-c400\">\r\n            <div class=\"form-field\">\r\n                <input name=\"demoUserName\" type=\"text\" class=\"text w300\" placeholder=\"User Name\" value=\"");
    protected static final byte[] _jsp_19504 = b("\"/>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">显示在登录页的用户名密码。一般用于演示系统或者公共用户。置空则不显示账号密码。</div>\r\n");
    protected static final byte[] _jsp_19505 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">演示账号密码：</div>\r\n");
    protected static final byte[] _jsp_19506 = b("        <div class=\"form-c400\">\r\n            <div class=\"form-field\">\r\n                <input name=\"demoPassword\" type=\"text\" class=\"text w300\" placeholder=\"Password\" value=\"");
    protected static final byte[] _jsp_19508 = b("\"/>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">显示在登录页的用户名密码。一般用于演示系统或者公共用户。置空则不显示账号密码。</div>\r\n");
    protected static final byte[] _jsp_19509 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">自动更新检查：</div>\r\n");
    protected static final byte[] _jsp_19510 = b("        <div class=\"form-c400\">\r\n            <div class=\"form-field\">\r\n                <input name=\"updateCheck\" type=\"checkbox\" checked-value=\"");
    protected static final byte[] _jsp_19512 = b("\" value=\"true\"/>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n");
    protected static final byte[] _jsp_19513 = b("            <div class=\"form-comment\">是否开启自动更新检查。</div>\r\n        </div>\r\n    </div>\r\n");
    protected static final byte[] _jsp_19514 = b("    <div class=\"button\">\r\n        <button id=\"submit\" class=\"button ensure\">保存并同步到集群</button>\r\n");
    protected static final byte[] _jsp_19515 = b("    </div>\r\n</div>\r\n<div id=\"pageContext\" style=\"display: none;\"></div>\r\n</body>\r\n");
    protected static final byte[] _jsp_19516 = b("</html>\r\n");

}
