/*
 * $RCSfile: ConfigListTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import java.util.List;
import com.skin.finder.config.App;
import com.skin.finder.cluster.Cluster;
import com.skin.finder.cluster.Host;


/**
 * <p>Title: ConfigListTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class ConfigListTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final ConfigListTemplate instance = new ConfigListTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();


    Cluster cluster = (Cluster)(request.getAttribute("cluster"));
    List<Host> hosts = cluster.getHosts();

        out.write(_jsp_76583, 0, _jsp_76583.length);
        out.write(_jsp_76584, 0, _jsp_76584.length);
        out.write(_jsp_76585, 0, _jsp_76585.length);
        out.write(_jsp_76586, 0, _jsp_76586.length);
        out.write(_jsp_76587, 0, _jsp_76587.length);
        this.write(out, (App.hash()));
        out.write(_jsp_76589, 0, _jsp_76589.length);
        out.write(_jsp_76590, 0, _jsp_76590.length);
        this.write(out, (App.hash()));
        out.write(_jsp_76592, 0, _jsp_76592.length);
        out.write(_jsp_76593, 0, _jsp_76593.length);
        out.write(_jsp_76594, 0, _jsp_76594.length);
        out.write(_jsp_76595, 0, _jsp_76595.length);
        out.write(_jsp_76596, 0, _jsp_76596.length);
        out.write(_jsp_76597, 0, _jsp_76597.length);
        out.write(_jsp_76598, 0, _jsp_76598.length);
        out.write(_jsp_76599, 0, _jsp_76599.length);
        out.write(_jsp_76600, 0, _jsp_76600.length);
        out.write(_jsp_76601, 0, _jsp_76601.length);
        out.write(_jsp_76602, 0, _jsp_76602.length);
        out.write(_jsp_76603, 0, _jsp_76603.length);
        out.write(_jsp_76604, 0, _jsp_76604.length);
        out.write(_jsp_76605, 0, _jsp_76605.length);
        out.write(_jsp_76606, 0, _jsp_76606.length);
        out.write(_jsp_76607, 0, _jsp_76607.length);
        out.write(_jsp_76608, 0, _jsp_76608.length);
        out.write(_jsp_76609, 0, _jsp_76609.length);
        out.write(_jsp_76610, 0, _jsp_76610.length);
        out.write(_jsp_76611, 0, _jsp_76611.length);
        out.write(_jsp_76612, 0, _jsp_76612.length);
        out.write(_jsp_76613, 0, _jsp_76613.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_76615, 0, _jsp_76615.length);
        out.write(_jsp_76616, 0, _jsp_76616.length);
        out.write(_jsp_76617, 0, _jsp_76617.length);
        out.write(_jsp_76618, 0, _jsp_76618.length);
        out.write(_jsp_76619, 0, _jsp_76619.length);
        out.write(_jsp_76620, 0, _jsp_76620.length);
        out.write(_jsp_76621, 0, _jsp_76621.length);

        for(Host host : hosts) {
    
        out.write(_jsp_76623, 0, _jsp_76623.length);
        this.write(out, (host.getName()));
        out.write(_jsp_76625, 0, _jsp_76625.length);
        this.write(out, (host.getName()));
        out.write(_jsp_76627, 0, _jsp_76627.length);
        this.write(out, (host.getDisplayName()));
        out.write(_jsp_76629, 0, _jsp_76629.length);
        this.write(out, (host.getUrl()));
        out.write(_jsp_76631, 0, _jsp_76631.length);

        }
    
        out.write(_jsp_76633, 0, _jsp_76633.length);
        this.write(out, request.getAttribute("masterName"));
        out.write(_jsp_76635, 0, _jsp_76635.length);
        this.write(out, request.getAttribute("confVersion"));
        out.write(_jsp_76637, 0, _jsp_76637.length);

        out.flush();
    }

    protected static final byte[] _jsp_76583 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_76584 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_76585 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_76586 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_76587 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css&v=");
    protected static final byte[] _jsp_76589 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_76590 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js&v=");
    protected static final byte[] _jsp_76592 = b("\"></script>\r\n<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    var master = PageContext.getAttribute(\"master-name\");\r\n");
    protected static final byte[] _jsp_76593 = b("    var table = document.getElementById(\"host-table\");\r\n    var rows = table.rows;\r\n");
    protected static final byte[] _jsp_76594 = b("\r\n    for(var i = 0; i < rows.length; i++) {\r\n        var tr = rows[i];\r\n        var hostName = tr.getAttribute(\"hostName\");\r\n");
    protected static final byte[] _jsp_76595 = b("\r\n        if(hostName == null || hostName == undefined) {\r\n            continue;\r\n");
    protected static final byte[] _jsp_76596 = b("        }\r\n\r\n        if(hostName == master) {\r\n            var src = jQuery(tr).find(\"td a.conf-sync\");\r\n");
    protected static final byte[] _jsp_76597 = b("            src.attr(\"class\", \"btn disabled\");\r\n        }\r\n    }\r\n});\r\n\r\njQuery(function() {\r\n");
    protected static final byte[] _jsp_76598 = b("    /**\r\n     * 1. 遍历所有host, 发起ajax请求获取目标主机的host.xml的版本号\r\n     */\r\n    var handler = function(index) {\r\n");
    protected static final byte[] _jsp_76599 = b("        if(index == null || index == undefined) {\r\n            return;\r\n        }\r\n");
    protected static final byte[] _jsp_76600 = b("\r\n        var table = document.getElementById(\"host-table\");\r\n        var rows = table.rows;\r\n");
    protected static final byte[] _jsp_76601 = b("\r\n        if(index >= rows.length) {\r\n            return;\r\n        }\r\n\r\n        var tr = rows[index];\r\n");
    protected static final byte[] _jsp_76602 = b("        var hostName = tr.getAttribute(\"hostName\");\r\n        var version = PageContext.getAttribute(\"master-config-version\");\r\n");
    protected static final byte[] _jsp_76603 = b("\r\n        if(hostName == null || hostName == undefined) {\r\n            return;\r\n");
    protected static final byte[] _jsp_76604 = b("        }\r\n\r\n        jQuery.ajax({\r\n            \"type\": \"get\",\r\n            \"url\": \"?action=agent.conf.version&host=\" + encodeURIComponent(hostName),\r\n");
    protected static final byte[] _jsp_76605 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                jQuery(tr).find(\"td.version\").html(\"系统错误\");\r\n");
    protected static final byte[] _jsp_76606 = b("                handler(index + 1);\r\n            },\r\n            \"success\": function(response) {\r\n");
    protected static final byte[] _jsp_76607 = b("                if(response.status != 200) {\r\n                    jQuery(tr).find(\"td.version\").attr(\"title\", response.message);\r\n");
    protected static final byte[] _jsp_76608 = b("                    jQuery(tr).find(\"td.version\").html(\"系统错误\");\r\n                }\r\n");
    protected static final byte[] _jsp_76609 = b("                else {\r\n                    if(response.value != version) {\r\n                        jQuery(tr).find(\"td.version\").attr(\"title\", \"该节点配置与master节点不一致，请从master同步数据。\");\r\n");
    protected static final byte[] _jsp_76610 = b("                        jQuery(tr).find(\"td.version\").html(\"<span class=\\\"red\\\">\" + response.value + \"</span>\");\r\n");
    protected static final byte[] _jsp_76611 = b("                    }\r\n                    else {\r\n                        jQuery(tr).find(\"td.version\").html(\"<span>\" + response.value + \"</span>\");\r\n");
    protected static final byte[] _jsp_76612 = b("                    }\r\n                }\r\n                handler(index + 1);\r\n            }\r\n");
    protected static final byte[] _jsp_76613 = b("        });\r\n    };\r\n    handler(1);\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_76615 = b("\">\r\n<div class=\"menu-bar\">\r\n    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_76616 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_76617 = b("    <span class=\"seperator\"></span>\r\n    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.href='?action=admin.config.edit';\"><span class=\"add\"></span>一般设置</a>\r\n");
    protected static final byte[] _jsp_76618 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.href='?action=admin.security.config.edit';\"><span class=\"add\"></span>安全设置</a>\r\n");
    protected static final byte[] _jsp_76619 = b("</div>\r\n<table id=\"host-table\" class=\"list\">\r\n    <tr class=\"head\">\r\n        <td class=\"w200\">Name</td>\r\n");
    protected static final byte[] _jsp_76620 = b("        <td class=\"w200\">Display Name</td>\r\n        <td class=\"w300\">URL</td>\r\n        <td>Version</td>\r\n");
    protected static final byte[] _jsp_76621 = b("    </tr>\r\n    ");
    protected static final byte[] _jsp_76623 = b("    <tr hostName=\"");
    protected static final byte[] _jsp_76625 = b("\">\r\n        <td>");
    protected static final byte[] _jsp_76627 = b("</td>\r\n        <td>");
    protected static final byte[] _jsp_76629 = b("</td>\r\n        <td>");
    protected static final byte[] _jsp_76631 = b("</td>\r\n        <td class=\"version\">...</td>\r\n    </tr>\r\n    ");
    protected static final byte[] _jsp_76633 = b("</table>\r\n<div id=\"pageContext\" style=\"display: none;\" master-name=\"");
    protected static final byte[] _jsp_76635 = b("\" master-config-version=\"");
    protected static final byte[] _jsp_76637 = b("\"></div>\r\n</body>\r\n</html>\r\n");

}
