/*
 * $RCSfile: HostEditTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;
import com.skin.finder.cluster.Host;


/**
 * <p>Title: HostEditTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class HostEditTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final HostEditTemplate instance = new HostEditTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();


    Host host = (Host)(request.getAttribute("host"));

    if(host == null) {
        host = new Host();
    }

        out.write(_jsp_10745, 0, _jsp_10745.length);
        out.write(_jsp_10746, 0, _jsp_10746.length);
        out.write(_jsp_10747, 0, _jsp_10747.length);
        out.write(_jsp_10748, 0, _jsp_10748.length);
        out.write(_jsp_10749, 0, _jsp_10749.length);
        this.write(out, (App.hash()));
        out.write(_jsp_10751, 0, _jsp_10751.length);
        out.write(_jsp_10752, 0, _jsp_10752.length);
        this.write(out, (App.hash()));
        out.write(_jsp_10754, 0, _jsp_10754.length);
        out.write(_jsp_10755, 0, _jsp_10755.length);
        out.write(_jsp_10756, 0, _jsp_10756.length);
        out.write(_jsp_10757, 0, _jsp_10757.length);
        out.write(_jsp_10758, 0, _jsp_10758.length);
        out.write(_jsp_10759, 0, _jsp_10759.length);
        out.write(_jsp_10760, 0, _jsp_10760.length);
        out.write(_jsp_10761, 0, _jsp_10761.length);
        out.write(_jsp_10762, 0, _jsp_10762.length);
        out.write(_jsp_10763, 0, _jsp_10763.length);
        out.write(_jsp_10764, 0, _jsp_10764.length);
        out.write(_jsp_10765, 0, _jsp_10765.length);
        out.write(_jsp_10766, 0, _jsp_10766.length);
        out.write(_jsp_10767, 0, _jsp_10767.length);
        out.write(_jsp_10768, 0, _jsp_10768.length);
        out.write(_jsp_10769, 0, _jsp_10769.length);
        out.write(_jsp_10770, 0, _jsp_10770.length);
        out.write(_jsp_10771, 0, _jsp_10771.length);
        out.write(_jsp_10772, 0, _jsp_10772.length);
        out.write(_jsp_10773, 0, _jsp_10773.length);
        out.write(_jsp_10774, 0, _jsp_10774.length);
        out.write(_jsp_10775, 0, _jsp_10775.length);
        out.write(_jsp_10776, 0, _jsp_10776.length);
        out.write(_jsp_10777, 0, _jsp_10777.length);
        out.write(_jsp_10778, 0, _jsp_10778.length);
        out.write(_jsp_10779, 0, _jsp_10779.length);
        out.write(_jsp_10780, 0, _jsp_10780.length);
        out.write(_jsp_10781, 0, _jsp_10781.length);
        out.write(_jsp_10782, 0, _jsp_10782.length);
        out.write(_jsp_10783, 0, _jsp_10783.length);
        out.write(_jsp_10784, 0, _jsp_10784.length);
        out.write(_jsp_10785, 0, _jsp_10785.length);
        out.write(_jsp_10786, 0, _jsp_10786.length);
        this.write(out, request.getAttribute("oldName"));
        out.write(_jsp_10788, 0, _jsp_10788.length);
        this.write(out, (host.getName()));
        out.write(_jsp_10790, 0, _jsp_10790.length);
        out.write(_jsp_10791, 0, _jsp_10791.length);
        out.write(_jsp_10792, 0, _jsp_10792.length);
        this.write(out, (host.getDisplayName()));
        out.write(_jsp_10794, 0, _jsp_10794.length);
        out.write(_jsp_10795, 0, _jsp_10795.length);
        out.write(_jsp_10796, 0, _jsp_10796.length);
        out.write(_jsp_10797, 0, _jsp_10797.length);
        this.write(out, (host.getUrl()));
        out.write(_jsp_10799, 0, _jsp_10799.length);
        out.write(_jsp_10800, 0, _jsp_10800.length);
        out.write(_jsp_10801, 0, _jsp_10801.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_10803, 0, _jsp_10803.length);

        out.flush();
    }

    protected static final byte[] _jsp_10745 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_10746 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_10747 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_10748 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_10749 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css&v=");
    protected static final byte[] _jsp_10751 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_10752 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js&v=");
    protected static final byte[] _jsp_10754 = b("\"></script>\r\n<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    jQuery(\"#url-open\").click(function() {\r\n");
    protected static final byte[] _jsp_10755 = b("        var hostUrl = jQuery.trim(jQuery(\"input[name=hostUrl]\").val());\r\n\r\n        if(hostUrl.length < 1) {\r\n");
    protected static final byte[] _jsp_10756 = b("            alert(\"请输入Host URL!\");\r\n            return;\r\n        }\r\n        window.open(hostUrl + \"?action=finder.status\");\r\n");
    protected static final byte[] _jsp_10757 = b("    });\r\n\r\n    jQuery(\"#url-test\").click(function() {\r\n        var requestURI = window.location.pathname;\r\n");
    protected static final byte[] _jsp_10758 = b("        var hostUrl = jQuery.trim(jQuery(\"input[name=hostUrl]\").val());\r\n\r\n        if(hostUrl.length < 1) {\r\n");
    protected static final byte[] _jsp_10759 = b("            alert(\"请输入Host URL!\");\r\n            return;\r\n        }\r\n\r\n        jQuery.ajax({\r\n");
    protected static final byte[] _jsp_10760 = b("            type: \"post\",\r\n            url: requestURI + \"?action=admin.host.test\",\r\n");
    protected static final byte[] _jsp_10761 = b("            dataType: \"json\",\r\n            data: \"hostUrl=\" + encodeURIComponent(hostUrl),\r\n");
    protected static final byte[] _jsp_10762 = b("            error: function(req, status, error) {\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_10763 = b("            },\r\n            success: function(result) {\r\n                if(result.status != 200) {\r\n");
    protected static final byte[] _jsp_10764 = b("                    alert(result.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_10765 = b("                alert(\"测试成功！\");\r\n            }\r\n        });\r\n    });\r\n\r\n    jQuery(\"#submit\").click(function() {\r\n");
    protected static final byte[] _jsp_10766 = b("        var oldName = jQuery.trim(jQuery(\"input[name=oldName]\").val());\r\n        var hostName = jQuery.trim(jQuery(\"input[name=hostName]\").val());\r\n");
    protected static final byte[] _jsp_10767 = b("        var displayName = jQuery.trim(jQuery(\"input[name=displayName]\").val());\r\n");
    protected static final byte[] _jsp_10768 = b("        var hostUrl = jQuery.trim(jQuery(\"input[name=hostUrl]\").val());\r\n\r\n        if(hostName.length < 1) {\r\n");
    protected static final byte[] _jsp_10769 = b("            alert(\"主机名不能为空！\");\r\n            return;\r\n        }\r\n\r\n        if(hostUrl.length < 1) {\r\n");
    protected static final byte[] _jsp_10770 = b("            alert(\"主机URL不能为空！\");\r\n            return;\r\n        }\r\n\r\n        var params = [];\r\n");
    protected static final byte[] _jsp_10771 = b("        var requestURI = window.location.pathname;\r\n        params[params.length] = \"oldName=\" + encodeURIComponent(oldName);\r\n");
    protected static final byte[] _jsp_10772 = b("        params[params.length] = \"hostName=\" + encodeURIComponent(hostName);\r\n        params[params.length] = \"displayName=\" + encodeURIComponent(displayName);\r\n");
    protected static final byte[] _jsp_10773 = b("        params[params.length] = \"hostUrl=\" + encodeURIComponent(hostUrl);\r\n\r\n        jQuery.ajax({\r\n");
    protected static final byte[] _jsp_10774 = b("            type: \"post\",\r\n            url: requestURI + \"?action=admin.host.save\",\r\n");
    protected static final byte[] _jsp_10775 = b("            dataType: \"json\",\r\n            data: params.join(\"&\"),\r\n            error: function(req, status, error) {\r\n");
    protected static final byte[] _jsp_10776 = b("                alert(\"系统错误，请稍后再试！\");\r\n            },\r\n            success: function(result) {\r\n");
    protected static final byte[] _jsp_10777 = b("                if(result.status != 200) {\r\n                    alert(result.message);\r\n");
    protected static final byte[] _jsp_10778 = b("                    return;\r\n                }\r\n                alert(\"操作成功！\");\r\n");
    protected static final byte[] _jsp_10779 = b("                window.location.href = \"?action=admin.host.list\";\r\n            }\r\n");
    protected static final byte[] _jsp_10780 = b("        });\r\n    });\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n<body>\r\n<div class=\"menu-bar\">\r\n");
    protected static final byte[] _jsp_10781 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_10782 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_10783 = b("    <span class=\"seperator\"></span>\r\n</div>\r\n<div class=\"form\">\r\n    <div class=\"title\"><h4>主机编辑</h4></div>\r\n");
    protected static final byte[] _jsp_10784 = b("    <ul class=\"tips\">\r\n        <li>\r\n            <div><span style=\"color: #ff0000;\">重要提示：</span>如果修改了master，在添加完所有主机之后请到系统设置-一般设置，重新保存并同步到集群;</div>\r\n");
    protected static final byte[] _jsp_10785 = b("        </li>\r\n    </ul>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">Host Name：</div>\r\n");
    protected static final byte[] _jsp_10786 = b("        <div class=\"form-c300\">\r\n            <div class=\"form-field\">\r\n                <input name=\"oldName\" type=\"hidden\" value=\"");
    protected static final byte[] _jsp_10788 = b("\"/>\r\n                <input name=\"hostName\" type=\"text\" class=\"text w200\" placeholder=\"Host Name\" value=\"");
    protected static final byte[] _jsp_10790 = b("\"/>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">主机名。字母和数字开头，允许包含的字符: [a-z], [A-Z], [0-9], [-_.:@].</div>\r\n");
    protected static final byte[] _jsp_10791 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">Display Name：</div>\r\n");
    protected static final byte[] _jsp_10792 = b("        <div class=\"form-c300\">\r\n            <div class=\"form-field\">\r\n                <input name=\"displayName\" type=\"text\" class=\"text w200\" placeholder=\"Display Name\" value=\"");
    protected static final byte[] _jsp_10794 = b("\"/>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">显示名。允许任意可见字符。如果为空则显示为主机名。</div>\r\n");
    protected static final byte[] _jsp_10795 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">Host URL:</div>\r\n");
    protected static final byte[] _jsp_10796 = b("        <div class=\"form-comment\">Finder的访问地址。一般为http://IP:PORT/finder，如果使用了contextPath，finder的访问地址为：http://IP:PORT/[CONTEXT_PATH]/finder</div>\r\n");
    protected static final byte[] _jsp_10797 = b("        <div class=\"form-field\">\r\n            <input name=\"hostUrl\" type=\"text\" class=\"text w400\" placeholder=\"Host URL\" value=\"");
    protected static final byte[] _jsp_10799 = b("\"/>\r\n            <button id=\"url-test\" class=\"button ensure\">测 试</button>\r\n            <button id=\"url-open\" class=\"button ensure\">打 开</button>\r\n");
    protected static final byte[] _jsp_10800 = b("        </div>\r\n    </div>\r\n\r\n    <div class=\"button\">\r\n        <button id=\"submit\" class=\"button ensure\">保 存</button>\r\n");
    protected static final byte[] _jsp_10801 = b("    </div>\r\n</div>\r\n<div id=\"pageContext\" style=\"display: none;\" contextPath=\"");
    protected static final byte[] _jsp_10803 = b("\"></div>\r\n</body>\r\n</html>");

}
