/*
 * $RCSfile: MenuXmlTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;



/**
 * <p>Title: MenuXmlTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class MenuXmlTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final MenuXmlTemplate instance = new MenuXmlTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/xml; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_38324, 0, _jsp_38324.length);
        out.write(_jsp_38325, 0, _jsp_38325.length);

        if(Boolean.TRUE.equals(request.getAttribute("userSupport"))) {
    
        out.write(_jsp_38327, 0, _jsp_38327.length);
        out.write(_jsp_38328, 0, _jsp_38328.length);
        out.write(_jsp_38329, 0, _jsp_38329.length);
        out.write(_jsp_38330, 0, _jsp_38330.length);

        }
    
        out.write(_jsp_38332, 0, _jsp_38332.length);
        out.write(_jsp_38333, 0, _jsp_38333.length);
        out.write(_jsp_38334, 0, _jsp_38334.length);
        out.write(_jsp_38335, 0, _jsp_38335.length);
        out.write(_jsp_38336, 0, _jsp_38336.length);
        out.write(_jsp_38337, 0, _jsp_38337.length);

        out.flush();
    }

    protected static final byte[] _jsp_38324 = b("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<tree>\r\n<!-- FinderWeb - Powered by FinderWeb -->\r\n");
    protected static final byte[] _jsp_38325 = b("    <treeNode title=\"主机管理\" href=\"?action=admin.host.list\"/>\r\n    ");
    protected static final byte[] _jsp_38327 = b("    <treeNode title=\"用户管理\" href=\"?action=admin.user.query\" expand=\"true\">\r\n        <treeNode title=\"全部用户\" href=\"?action=admin.user.list\"/>\r\n");
    protected static final byte[] _jsp_38328 = b("        <treeNode title=\"添加用户\" href=\"?action=admin.user.edit\"/>\r\n        <treeNode title=\"修改用户\" href=\"?action=admin.user.query\"/>\r\n");
    protected static final byte[] _jsp_38329 = b("        <treeNode title=\"删除用户\" href=\"?action=admin.user.query\"/>\r\n    </treeNode>\r\n");
    protected static final byte[] _jsp_38330 = b("    ");
    protected static final byte[] _jsp_38332 = b("    <treeNode title=\"权限管理\" href=\"?action=admin.user.host.policy\" expand=\"true\">\r\n");
    protected static final byte[] _jsp_38333 = b("        <treeNode title=\"主机权限\" href=\"?action=admin.user.host.policy\"/>\r\n        <treeNode title=\"文件权限\" href=\"?action=admin.user.file.policy\"/>\r\n");
    protected static final byte[] _jsp_38334 = b("    </treeNode>\r\n    <treeNode title=\"系统设置\" href=\"?action=admin.config.list\" expand=\"true\">\r\n");
    protected static final byte[] _jsp_38335 = b("        <treeNode title=\"一般设置\" href=\"?action=admin.config.edit\"/>\r\n        <treeNode title=\"安全设置\" href=\"?action=admin.security.config.edit\"/>\r\n");
    protected static final byte[] _jsp_38336 = b("    </treeNode>\r\n    <treeNode title=\"系统更新\" href=\"?action=admin.upgrade.index\"/>\r\n");
    protected static final byte[] _jsp_38337 = b("    <treeNode title=\"系统信息\" href=\"?action=admin.system.info\"/>\r\n</tree>\r\n");

}
