/*
 * $RCSfile: SecurityConfigEditTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;
import com.skin.finder.config.ConfigFactory;


/**
 * <p>Title: SecurityConfigEditTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class SecurityConfigEditTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final SecurityConfigEditTemplate instance = new SecurityConfigEditTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_57346, 0, _jsp_57346.length);
        out.write(_jsp_57347, 0, _jsp_57347.length);
        out.write(_jsp_57348, 0, _jsp_57348.length);
        out.write(_jsp_57349, 0, _jsp_57349.length);
        out.write(_jsp_57350, 0, _jsp_57350.length);
        this.write(out, (App.hash()));
        out.write(_jsp_57352, 0, _jsp_57352.length);
        out.write(_jsp_57353, 0, _jsp_57353.length);
        this.write(out, (App.hash()));
        out.write(_jsp_57355, 0, _jsp_57355.length);
        this.write(out, (App.hash()));
        out.write(_jsp_57357, 0, _jsp_57357.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_57359, 0, _jsp_57359.length);
        out.write(_jsp_57360, 0, _jsp_57360.length);
        out.write(_jsp_57361, 0, _jsp_57361.length);
        out.write(_jsp_57362, 0, _jsp_57362.length);
        out.write(_jsp_57363, 0, _jsp_57363.length);
        this.write(out, (ConfigFactory.getAdmin()));
        out.write(_jsp_57365, 0, _jsp_57365.length);
        out.write(_jsp_57366, 0, _jsp_57366.length);
        out.write(_jsp_57367, 0, _jsp_57367.length);
        this.write(out, (ConfigFactory.getSecurityKey()));
        out.write(_jsp_57369, 0, _jsp_57369.length);
        out.write(_jsp_57370, 0, _jsp_57370.length);
        out.write(_jsp_57371, 0, _jsp_57371.length);
        out.write(_jsp_57372, 0, _jsp_57372.length);
        this.write(out, (ConfigFactory.getSessionName()));
        out.write(_jsp_57374, 0, _jsp_57374.length);
        out.write(_jsp_57375, 0, _jsp_57375.length);
        out.write(_jsp_57376, 0, _jsp_57376.length);
        this.write(out, (ConfigFactory.getSessionKey()));
        out.write(_jsp_57378, 0, _jsp_57378.length);
        out.write(_jsp_57379, 0, _jsp_57379.length);
        out.write(_jsp_57380, 0, _jsp_57380.length);
        out.write(_jsp_57381, 0, _jsp_57381.length);
        out.write(_jsp_57382, 0, _jsp_57382.length);
        this.write(out, (ConfigFactory.getPublicKey()));
        out.write(_jsp_57384, 0, _jsp_57384.length);
        out.write(_jsp_57385, 0, _jsp_57385.length);
        out.write(_jsp_57386, 0, _jsp_57386.length);
        out.write(_jsp_57387, 0, _jsp_57387.length);
        this.write(out, (ConfigFactory.getPrivateKey()));
        out.write(_jsp_57389, 0, _jsp_57389.length);
        out.write(_jsp_57390, 0, _jsp_57390.length);
        out.write(_jsp_57391, 0, _jsp_57391.length);

        out.flush();
    }

    protected static final byte[] _jsp_57346 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_57347 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_57348 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_57349 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_57350 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css&v=");
    protected static final byte[] _jsp_57352 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_57353 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js&v=");
    protected static final byte[] _jsp_57355 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/admin/security.js&v=");
    protected static final byte[] _jsp_57357 = b("\"></script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_57359 = b("\">\r\n<div class=\"menu-bar\">\r\n    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_57360 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_57361 = b("    <span class=\"seperator\"></span>\r\n</div>\r\n<div class=\"form\">\r\n    <div class=\"title\"><h4>系统设置 - 安全设置</h4></div>\r\n");
    protected static final byte[] _jsp_57362 = b("    <div class=\"form-row\">\r\n        <div class=\"form-label\">超级管理员：</div>\r\n        <div class=\"form-c400\">\r\n");
    protected static final byte[] _jsp_57363 = b("            <div class=\"form-field\">\r\n                <input name=\"adminName\" type=\"text\" class=\"text w300\" placeholder=\"User Name\" value=\"");
    protected static final byte[] _jsp_57365 = b("\"/>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">超级管理员账号。</div>\r\n");
    protected static final byte[] _jsp_57366 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">安全Key：</div>\r\n");
    protected static final byte[] _jsp_57367 = b("        <div class=\"form-c400\">\r\n            <div class=\"form-field\">\r\n                <input name=\"securityKey\" type=\"text\" class=\"text w300\" placeholder=\"Security Key\" value=\"");
    protected static final byte[] _jsp_57369 = b("\"/>\r\n                <button id=\"url-test\" class=\"button key-generate\" data-for-name=\"securityKey\">生成</button>\r\n");
    protected static final byte[] _jsp_57370 = b("            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">Finder内部通讯使用的安全KEY。集群环境下，所有机器的安全KEY必须一致。强烈建议重新生成。</div>\r\n");
    protected static final byte[] _jsp_57371 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">会话名：</div>\r\n");
    protected static final byte[] _jsp_57372 = b("        <div class=\"form-c400\">\r\n            <div class=\"form-field\">\r\n                <input name=\"sessionName\" type=\"text\" class=\"text w300\" placeholder=\"Session Name\" value=\"");
    protected static final byte[] _jsp_57374 = b("\"/>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">会话存储的cookie名。</div>\r\n");
    protected static final byte[] _jsp_57375 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">会话签名Key：</div>\r\n");
    protected static final byte[] _jsp_57376 = b("        <div class=\"form-c400\">\r\n            <div class=\"form-field\">\r\n                <input name=\"sessionKey\" type=\"text\" class=\"text w300\" placeholder=\"Session Key\" value=\"");
    protected static final byte[] _jsp_57378 = b("\"/>\r\n                <button id=\"url-test\" class=\"button key-generate\" data-for-name=\"sessionKey\">生成</button>\r\n");
    protected static final byte[] _jsp_57379 = b("            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">会话签名使用的key。强烈建议重新生成。</div>\r\n");
    protected static final byte[] _jsp_57380 = b("        </div>\r\n    </div>\r\n\r\n    <div class=\"form-row\" style=\"display: none;\">\r\n");
    protected static final byte[] _jsp_57381 = b("        <div class=\"form-label\">RSA PublicKey：</div>\r\n        <div class=\"form-comment\">用户登录使用的加密key。强烈建议重新生成。</div>\r\n");
    protected static final byte[] _jsp_57382 = b("        <div class=\"form-field\">\r\n            <textarea name=\"publicKey\" type=\"text\" class=\"text\" style=\"width: 800px; resize: none;\">");
    protected static final byte[] _jsp_57384 = b("</textarea>\r\n        </div>\r\n        <div class=\"form-field\">\r\n            <button id=\"url-test\" class=\"button rsa-generate\">生成</button>\r\n");
    protected static final byte[] _jsp_57385 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\" style=\"display: none;\">\r\n        <div class=\"form-label\">RSA PrivateKey：</div>\r\n");
    protected static final byte[] _jsp_57386 = b("        <div class=\"form-comment\">用户登录使用的解密key。强烈建议重新生成。</div>\r\n        <div class=\"form-field\">\r\n");
    protected static final byte[] _jsp_57387 = b("            <textarea name=\"privateKey\" type=\"text\" class=\"text\" style=\"width: 800px; resize: none;\">");
    protected static final byte[] _jsp_57389 = b("</textarea>\r\n        </div>\r\n    </div>\r\n    <div class=\"button\">\r\n        <button id=\"submit\" class=\"button ensure\">保存并同步到集群</button>\r\n");
    protected static final byte[] _jsp_57390 = b("    </div>\r\n</div>\r\n<div id=\"pageContext\" style=\"display: none;\"></div>\r\n</body>\r\n");
    protected static final byte[] _jsp_57391 = b("</html>\r\n");

}
