/*
 * $RCSfile: SystemInfoTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;
import com.skin.finder.util.SystemInfo;
import com.skin.finder.util.Version;
import com.skin.finder.util.Manifest;
import com.skin.finder.util.ServletInfo;


/**
 * <p>Title: SystemInfoTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class SystemInfoTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final SystemInfoTemplate instance = new SystemInfoTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();


    Version version = (Version)(request.getAttribute("version"));
    SystemInfo systemInfo = (SystemInfo)(request.getAttribute("systemInfo"));
    ServletInfo servletInfo = (ServletInfo)(request.getAttribute("servletInfo"));

        out.write(_jsp_35178, 0, _jsp_35178.length);
        out.write(_jsp_35179, 0, _jsp_35179.length);
        out.write(_jsp_35180, 0, _jsp_35180.length);
        out.write(_jsp_35181, 0, _jsp_35181.length);
        out.write(_jsp_35182, 0, _jsp_35182.length);
        this.write(out, (App.hash()));
        out.write(_jsp_35184, 0, _jsp_35184.length);
        out.write(_jsp_35185, 0, _jsp_35185.length);
        this.write(out, (App.hash()));
        out.write(_jsp_35187, 0, _jsp_35187.length);
        this.write(out, request.getAttribute("reqeustHeaders"));
        out.write(_jsp_35189, 0, _jsp_35189.length);
        out.write(_jsp_35190, 0, _jsp_35190.length);
        out.write(_jsp_35191, 0, _jsp_35191.length);
        out.write(_jsp_35192, 0, _jsp_35192.length);
        out.write(_jsp_35193, 0, _jsp_35193.length);
        this.write(out, request.getAttribute("hostName"));
        out.write(_jsp_35195, 0, _jsp_35195.length);
        this.write(out, (version.getVersionName()));
        out.write(_jsp_35197, 0, _jsp_35197.length);
        this.write(out, (Manifest.getBuildTime()));
        out.write(_jsp_35199, 0, _jsp_35199.length);
        this.write(out, (version.getDeveloper()));
        out.write(_jsp_35201, 0, _jsp_35201.length);
        this.write(out, (version.getDeveloper()));
        out.write(_jsp_35203, 0, _jsp_35203.length);
        this.write(out, (servletInfo.getServerInfo()));
        out.write(_jsp_35205, 0, _jsp_35205.length);
        this.write(out, (servletInfo.getServletVersion()));
        out.write(_jsp_35207, 0, _jsp_35207.length);
        this.write(out, (servletInfo.getAppPath()));
        out.write(_jsp_35209, 0, _jsp_35209.length);
        this.write(out, (servletInfo.getAppPath()));
        out.write(_jsp_35211, 0, _jsp_35211.length);
        this.write(out, (systemInfo.getOsName()));
        out.write(_jsp_35213, 0, _jsp_35213.length);
        this.write(out, (systemInfo.getOsVersion()));
        out.write(_jsp_35215, 0, _jsp_35215.length);
        this.write(out, (systemInfo.getCpu()));
        out.write(_jsp_35217, 0, _jsp_35217.length);
        this.write(out, (systemInfo.getVmName()));
        out.write(_jsp_35219, 0, _jsp_35219.length);
        this.write(out, (systemInfo.getVmVendor()));
        out.write(_jsp_35221, 0, _jsp_35221.length);
        this.write(out, (systemInfo.getVmVersion()));
        out.write(_jsp_35223, 0, _jsp_35223.length);
        this.write(out, (systemInfo.getRuntimeName()));
        out.write(_jsp_35225, 0, _jsp_35225.length);
        this.write(out, (systemInfo.getRuntimeVersion()));
        out.write(_jsp_35227, 0, _jsp_35227.length);
        this.write(out, (systemInfo.getMaxMemory()));
        out.write(_jsp_35229, 0, _jsp_35229.length);
        this.write(out, (systemInfo.getMaxMemory() / 1048576));
        out.write(_jsp_35231, 0, _jsp_35231.length);
        this.write(out, (systemInfo.getTotalMemory()));
        out.write(_jsp_35233, 0, _jsp_35233.length);
        this.write(out, (systemInfo.getTotalMemory() / 1048576));
        out.write(_jsp_35235, 0, _jsp_35235.length);
        this.write(out, (systemInfo.getFreeMemory()));
        out.write(_jsp_35237, 0, _jsp_35237.length);
        this.write(out, (systemInfo.getFreeMemory() / 1048576));
        out.write(_jsp_35239, 0, _jsp_35239.length);

        out.flush();
    }

    protected static final byte[] _jsp_35178 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_35179 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_35180 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_35181 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_35182 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css&v=");
    protected static final byte[] _jsp_35184 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_35185 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js&v=");
    protected static final byte[] _jsp_35187 = b("\"></script>\r\n</head>\r\n<body>\r\n<!--\r\n");
    protected static final byte[] _jsp_35189 = b("\r\n-->\r\n<div class=\"menu-bar\">\r\n    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_35190 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_35191 = b("    <span class=\"seperator\"></span>\r\n</div>\r\n<table class=\"list2\">\r\n    <!-- Server Info -->\r\n");
    protected static final byte[] _jsp_35192 = b("    <tr class=\"head\">\r\n        <td colspan=\"2\">System Info</td>\r\n    </tr>\r\n    <tr>\r\n");
    protected static final byte[] _jsp_35193 = b("        <td class=\"w200\">Host</td>\r\n        <td>");
    protected static final byte[] _jsp_35195 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Version</td>\r\n        <td>");
    protected static final byte[] _jsp_35197 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td>BuildTime</td>\r\n        <td>");
    protected static final byte[] _jsp_35199 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Developer</td>\r\n        <td><a href=\"");
    protected static final byte[] _jsp_35201 = b("\" target=\"_blank\">");
    protected static final byte[] _jsp_35203 = b("</a></td>\r\n    </tr>\r\n    <tr>\r\n        <td>ServerInfo</td>\r\n        <td>");
    protected static final byte[] _jsp_35205 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td>ServletVersion</td>\r\n        <td>");
    protected static final byte[] _jsp_35207 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td>ServletPath</td>\r\n        <td><a href=\"");
    protected static final byte[] _jsp_35209 = b("\" target=\"_blank\">");
    protected static final byte[] _jsp_35211 = b("</a></td>\r\n    </tr>\r\n    <!-- System Info -->\r\n    <tr>\r\n        <td>OS</td>\r\n        <td>");
    protected static final byte[] _jsp_35213 = b(" (");
    protected static final byte[] _jsp_35215 = b(") (");
    protected static final byte[] _jsp_35217 = b(")</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Virtual Machine Name</td>\r\n        <td>");
    protected static final byte[] _jsp_35219 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Virtual Machine Vendor</td>\r\n        <td>");
    protected static final byte[] _jsp_35221 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Virtual Machine Version</td>\r\n        <td>");
    protected static final byte[] _jsp_35223 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Runtime Name</td>\r\n        <td>");
    protected static final byte[] _jsp_35225 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Runtime Version</td>\r\n        <td>");
    protected static final byte[] _jsp_35227 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Max Memory</td>\r\n        <td>");
    protected static final byte[] _jsp_35229 = b(" (");
    protected static final byte[] _jsp_35231 = b("M)</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Total Memory</td>\r\n        <td>");
    protected static final byte[] _jsp_35233 = b(" (");
    protected static final byte[] _jsp_35235 = b("M)</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Free Memory</td>\r\n        <td>");
    protected static final byte[] _jsp_35237 = b(" (");
    protected static final byte[] _jsp_35239 = b("M)</td>\r\n    </tr>\r\n</table>\r\n</body>\r\n</html>\r\n");

}
