/*
 * $RCSfile: TreeMenuTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;


/**
 * <p>Title: TreeMenuTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class TreeMenuTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final TreeMenuTemplate instance = new TreeMenuTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_85435, 0, _jsp_85435.length);
        out.write(_jsp_85436, 0, _jsp_85436.length);
        out.write(_jsp_85437, 0, _jsp_85437.length);
        out.write(_jsp_85438, 0, _jsp_85438.length);
        out.write(_jsp_85439, 0, _jsp_85439.length);
        this.write(out, (App.hash()));
        out.write(_jsp_85441, 0, _jsp_85441.length);
        this.write(out, (App.hash()));
        out.write(_jsp_85443, 0, _jsp_85443.length);
        this.write(out, (App.hash()));
        out.write(_jsp_85445, 0, _jsp_85445.length);
        this.write(out, (App.hash()));
        out.write(_jsp_85447, 0, _jsp_85447.length);
        out.write(_jsp_85448, 0, _jsp_85448.length);
        out.write(_jsp_85449, 0, _jsp_85449.length);
        out.write(_jsp_85450, 0, _jsp_85450.length);
        out.write(_jsp_85451, 0, _jsp_85451.length);
        out.write(_jsp_85452, 0, _jsp_85452.length);
        out.write(_jsp_85453, 0, _jsp_85453.length);
        out.write(_jsp_85454, 0, _jsp_85454.length);
        out.write(_jsp_85455, 0, _jsp_85455.length);
        out.write(_jsp_85456, 0, _jsp_85456.length);
        out.write(_jsp_85457, 0, _jsp_85457.length);
        out.write(_jsp_85458, 0, _jsp_85458.length);
        out.write(_jsp_85459, 0, _jsp_85459.length);
        out.write(_jsp_85460, 0, _jsp_85460.length);
        out.write(_jsp_85461, 0, _jsp_85461.length);
        out.write(_jsp_85462, 0, _jsp_85462.length);
        out.write(_jsp_85463, 0, _jsp_85463.length);
        out.write(_jsp_85464, 0, _jsp_85464.length);
        out.write(_jsp_85465, 0, _jsp_85465.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_85467, 0, _jsp_85467.length);
        out.write(_jsp_85468, 0, _jsp_85468.length);

        out.flush();
    }

    protected static final byte[] _jsp_85435 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_85436 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_85437 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_85438 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_85439 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css&v=");
    protected static final byte[] _jsp_85441 = b("\"/>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/tree.css&v=");
    protected static final byte[] _jsp_85443 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/htree/htree.js&v=");
    protected static final byte[] _jsp_85445 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/htree/htree.util.js&v=");
    protected static final byte[] _jsp_85447 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_85448 = b("<script type=\"text/javascript\">\r\n//<![CDATA[\r\nHTree.mode = \"menu\";\r\nHTree.click = function(src) {\r\n");
    protected static final byte[] _jsp_85449 = b("    var url = src.getAttribute(\"data\");\r\n\r\n    if(url == null || url.length < 1) {\r\n");
    protected static final byte[] _jsp_85450 = b("        return;\r\n    }\r\n\r\n    if(url == \"javascript:void(0);\") {\r\n        return;\r\n");
    protected static final byte[] _jsp_85451 = b("    }\r\n\r\n    try {\r\n        var doc = window.parent.window.document;\r\n        var iframe = doc.getElementById(\"main-frame\");\r\n");
    protected static final byte[] _jsp_85452 = b("\r\n        if(iframe != null) {\r\n            iframe.src = url;\r\n        }\r\n        else {\r\n");
    protected static final byte[] _jsp_85453 = b("            alert(\"系统错误，请稍后再试！\");\r\n        }\r\n    }\r\n    catch(e) {\r\n        if(typeof(window.console) != \"undefined\") {\r\n");
    protected static final byte[] _jsp_85454 = b("            window.console.error(e.name + \": \" + e.message);\r\n        }\r\n        alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_85455 = b("    }\r\n};\r\n\r\nfunction buildTree(id, xmlUrl, rootUrl){\r\n    HTree.config.stylePath = window.location.pathname + \"?action=res&path=/htree/menu/\";\r\n");
    protected static final byte[] _jsp_85456 = b("\r\n    var e = document.getElementById(id);\r\n\r\n    if(e == null) {\r\n        return;\r\n");
    protected static final byte[] _jsp_85457 = b("    }\r\n\r\n    var tree = new HTree.TreeNode({text: \"管理控制台\", href: rootUrl, xmlSrc: xmlUrl});\r\n");
    protected static final byte[] _jsp_85458 = b("\r\n    tree.load(function() {\r\n        this.render(document.getElementById(id));\r\n");
    protected static final byte[] _jsp_85459 = b("    });\r\n}\r\n\r\njQuery(function() {\r\n    var resize = function() {\r\n        var e = document.getElementById(\"htree\");\r\n");
    protected static final byte[] _jsp_85460 = b("\r\n        if(e != null) {\r\n            var parent = e.parentNode;\r\n            var offset = parseInt(parent.getAttribute(\"offset-top\"));\r\n");
    protected static final byte[] _jsp_85461 = b("\r\n            if(isNaN(offset)) {\r\n                offset = 0;\r\n            }\r\n\r\n");
    protected static final byte[] _jsp_85462 = b("            var height = document.documentElement.clientHeight - offset;\r\n            parent.style.height = height + \"px\";\r\n");
    protected static final byte[] _jsp_85463 = b("        }\r\n    };\r\n    jQuery(window).load(resize);\r\n    jQuery(window).resize(resize);\r\n");
    protected static final byte[] _jsp_85464 = b("});\r\n\r\njQuery(function() {\r\n    var requestURI = window.location.pathname;\r\n    buildTree(\"htree\", requestURI + \"?action=admin.menu.xml&r=\" + new Date().getTime(), requestURI + \"?action=finder.blank\");\r\n");
    protected static final byte[] _jsp_85465 = b("});\r\n//]]>\r\n</script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_85467 = b("\">\r\n<div class=\"left-nav\">\r\n    <div class=\"menu-body\">\r\n        <div id=\"htree\" class=\"htree\" style=\"margin-top: 10px; white-space: nowrap;\"></div>\r\n");
    protected static final byte[] _jsp_85468 = b("    </div>\r\n</div>\r\n</body>\r\n</html>\r\n");

}
