/*
 * $RCSfile: UpgradeTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import java.util.List;
import com.skin.finder.config.App;
import com.skin.finder.cluster.Cluster;
import com.skin.finder.cluster.Host;


/**
 * <p>Title: UpgradeTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class UpgradeTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final UpgradeTemplate instance = new UpgradeTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();


    Cluster cluster = (Cluster)(request.getAttribute("cluster"));
    List<Host> hosts = cluster.getHosts();

        out.write(_jsp_69936, 0, _jsp_69936.length);
        out.write(_jsp_69937, 0, _jsp_69937.length);
        out.write(_jsp_69938, 0, _jsp_69938.length);
        out.write(_jsp_69939, 0, _jsp_69939.length);
        out.write(_jsp_69940, 0, _jsp_69940.length);
        this.write(out, (App.hash()));
        out.write(_jsp_69942, 0, _jsp_69942.length);
        out.write(_jsp_69943, 0, _jsp_69943.length);
        this.write(out, (App.hash()));
        out.write(_jsp_69945, 0, _jsp_69945.length);
        this.write(out, (App.hash()));
        out.write(_jsp_69947, 0, _jsp_69947.length);
        this.write(out, (App.hash()));
        out.write(_jsp_69949, 0, _jsp_69949.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_69951, 0, _jsp_69951.length);
        out.write(_jsp_69952, 0, _jsp_69952.length);
        out.write(_jsp_69953, 0, _jsp_69953.length);
        out.write(_jsp_69954, 0, _jsp_69954.length);
        out.write(_jsp_69955, 0, _jsp_69955.length);
        out.write(_jsp_69956, 0, _jsp_69956.length);
        out.write(_jsp_69957, 0, _jsp_69957.length);

        for(Host host : hosts) {
    
        out.write(_jsp_69959, 0, _jsp_69959.length);
        this.write(out, (host.getName()));
        out.write(_jsp_69961, 0, _jsp_69961.length);
        this.write(out, (host.getName()));
        out.write(_jsp_69963, 0, _jsp_69963.length);
        this.write(out, (host.getName()));
        out.write(_jsp_69965, 0, _jsp_69965.length);
        this.write(out, (host.getDisplayName()));
        out.write(_jsp_69967, 0, _jsp_69967.length);
        out.write(_jsp_69968, 0, _jsp_69968.length);
        this.write(out, (host.getName()));
        out.write(_jsp_69970, 0, _jsp_69970.length);
        this.write(out, (host.getName()));
        out.write(_jsp_69972, 0, _jsp_69972.length);

        }
    
        out.write(_jsp_69974, 0, _jsp_69974.length);
        this.write(out, request.getAttribute("masterName"));
        out.write(_jsp_69976, 0, _jsp_69976.length);
        this.write(out, request.getAttribute("masterVersion"));
        out.write(_jsp_69978, 0, _jsp_69978.length);

        out.flush();
    }

    protected static final byte[] _jsp_69936 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_69937 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_69938 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_69939 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_69940 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css&v=");
    protected static final byte[] _jsp_69942 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_69943 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js&v=");
    protected static final byte[] _jsp_69945 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/fileupload.js&v=");
    protected static final byte[] _jsp_69947 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/admin/upgrade.js&v=");
    protected static final byte[] _jsp_69949 = b("\"></script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_69951 = b("\">\r\n<div class=\"menu-bar\">\r\n    <a class=\"button back\" href=\"javascript:void(0)\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_69952 = b("    <a class=\"button refresh\" href=\"javascript:void(0)\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_69953 = b("    <span class=\"seperator\"></span>\r\n    <a class=\"button upgrade\" href=\"javascript:void(0)\"><span class=\"add\"></span>系统升级</a>\r\n");
    protected static final byte[] _jsp_69954 = b("</div>\r\n<table id=\"host-table\" class=\"list\">\r\n    <tr class=\"head\">\r\n        <td class=\"w080 center\"><a id=\"checkall\" href=\"javascript:void(0)\">全 选</a> / <a id=\"uncheck\" href=\"javascript:void(0)\">取 消</a></td>\r\n");
    protected static final byte[] _jsp_69955 = b("        <td class=\"w200\">Name</td>\r\n        <td class=\"w200\">Display Name</td>\r\n");
    protected static final byte[] _jsp_69956 = b("        <td class=\"w100\">Version</td>\r\n        <td class=\"w150\">Start Time</td>\r\n");
    protected static final byte[] _jsp_69957 = b("        <td>操作</td>\r\n    </tr>\r\n    ");
    protected static final byte[] _jsp_69959 = b("    <tr class=\"disabled\" hostName=\"");
    protected static final byte[] _jsp_69961 = b("\">\r\n        <td style=\"text-align: center;\"><input name=\"hostName\" type=\"checkbox\" disabled=\"true\" value=\"");
    protected static final byte[] _jsp_69963 = b("\"/></td>\r\n        <td>");
    protected static final byte[] _jsp_69965 = b("</td>\r\n        <td>");
    protected static final byte[] _jsp_69967 = b("</td>\r\n        <td class=\"version\">...</td>\r\n        <td class=\"startTime\">...</td>\r\n");
    protected static final byte[] _jsp_69968 = b("        <td>\r\n            <a class=\"btn sys-inf disabled\" href=\"javascript:void(0)\" hostName=\"");
    protected static final byte[] _jsp_69970 = b("\">系统信息</a>\r\n            <a class=\"btn restart disabled\" href=\"javascript:void(0)\" hostName=\"");
    protected static final byte[] _jsp_69972 = b("\">重新启动</a>\r\n        </td>\r\n    </tr>\r\n    ");
    protected static final byte[] _jsp_69974 = b("</table>\r\n<div id=\"pageContext\" style=\"display: none;\" cluster-master-name=\"");
    protected static final byte[] _jsp_69976 = b("\" cluster-master-version=\"");
    protected static final byte[] _jsp_69978 = b("\"></div>\r\n</body>\r\n</html>\r\n");

}
