/*
 * $RCSfile: UserQueryListTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import java.util.List;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import com.skin.finder.config.App;
import com.skin.finder.acl.User;


/**
 * <p>Title: UserQueryListTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class UserQueryListTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final UserQueryListTemplate instance = new UserQueryListTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();


    @SuppressWarnings("unchecked")
    List<User> userList = (List<User>)(request.getAttribute("userList"));

        out.write(_jsp_42735, 0, _jsp_42735.length);
        out.write(_jsp_42736, 0, _jsp_42736.length);
        out.write(_jsp_42737, 0, _jsp_42737.length);
        out.write(_jsp_42738, 0, _jsp_42738.length);
        out.write(_jsp_42739, 0, _jsp_42739.length);
        this.write(out, (App.hash()));
        out.write(_jsp_42741, 0, _jsp_42741.length);
        out.write(_jsp_42742, 0, _jsp_42742.length);
        this.write(out, (App.hash()));
        out.write(_jsp_42744, 0, _jsp_42744.length);
        out.write(_jsp_42745, 0, _jsp_42745.length);
        out.write(_jsp_42746, 0, _jsp_42746.length);
        out.write(_jsp_42747, 0, _jsp_42747.length);
        out.write(_jsp_42748, 0, _jsp_42748.length);
        out.write(_jsp_42749, 0, _jsp_42749.length);
        out.write(_jsp_42750, 0, _jsp_42750.length);
        out.write(_jsp_42751, 0, _jsp_42751.length);
        out.write(_jsp_42752, 0, _jsp_42752.length);
        out.write(_jsp_42753, 0, _jsp_42753.length);
        out.write(_jsp_42754, 0, _jsp_42754.length);
        out.write(_jsp_42755, 0, _jsp_42755.length);
        out.write(_jsp_42756, 0, _jsp_42756.length);
        out.write(_jsp_42757, 0, _jsp_42757.length);
        out.write(_jsp_42758, 0, _jsp_42758.length);
        out.write(_jsp_42759, 0, _jsp_42759.length);
        out.write(_jsp_42760, 0, _jsp_42760.length);
        out.write(_jsp_42761, 0, _jsp_42761.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_42763, 0, _jsp_42763.length);
        out.write(_jsp_42764, 0, _jsp_42764.length);
        out.write(_jsp_42765, 0, _jsp_42765.length);
        out.write(_jsp_42766, 0, _jsp_42766.length);
        out.write(_jsp_42767, 0, _jsp_42767.length);
        this.write(out, request.getAttribute("userName"));
        out.write(_jsp_42769, 0, _jsp_42769.length);
        out.write(_jsp_42770, 0, _jsp_42770.length);
        out.write(_jsp_42771, 0, _jsp_42771.length);

            if(userList != null && userList.size() > 0) {
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

                for(User user : userList) {
        
        out.write(_jsp_42773, 0, _jsp_42773.length);
        this.write(out, (user.getUserName()));
        out.write(_jsp_42775, 0, _jsp_42775.length);
        this.write(out, (user.getUserName()));
        out.write(_jsp_42777, 0, _jsp_42777.length);
        this.write(out, (dateFormat.format(user.getCreateTime())));
        out.write(_jsp_42779, 0, _jsp_42779.length);
        this.write(out, (user.getUserName()));
        out.write(_jsp_42781, 0, _jsp_42781.length);
        this.write(out, (user.getUserName()));
        out.write(_jsp_42783, 0, _jsp_42783.length);
        this.write(out, (user.getUserName()));
        out.write(_jsp_42785, 0, _jsp_42785.length);

                }
            }
        
        out.write(_jsp_42787, 0, _jsp_42787.length);

        if(userList == null || userList.size() < 1) {
    
        out.write(_jsp_42789, 0, _jsp_42789.length);

        }
    
        out.write(_jsp_42791, 0, _jsp_42791.length);

        out.flush();
    }

    protected static final byte[] _jsp_42735 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_42736 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_42737 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_42738 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_42739 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css&v=");
    protected static final byte[] _jsp_42741 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_42742 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js&v=");
    protected static final byte[] _jsp_42744 = b("\"></script>\r\n<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    jQuery(\"input[name=query]\").click(function() {\r\n");
    protected static final byte[] _jsp_42745 = b("        var userName = jQuery.trim(jQuery(\"input[name=userName]\").val());\r\n\r\n        if(userName.length < 1) {\r\n");
    protected static final byte[] _jsp_42746 = b("            alert(\"用户名不能为空！\");\r\n            return;\r\n        }\r\n        window.location.href = \"?action=admin.user.query&userName=\" + encodeURIComponent(userName);\r\n");
    protected static final byte[] _jsp_42747 = b("    });\r\n\r\n    jQuery(\"table tr td a.delete\").click(function() {\r\n        var userName = this.getAttribute(\"userName\");\r\n");
    protected static final byte[] _jsp_42748 = b("\r\n        if(!window.confirm(\"删除之后不可恢复，确定要删除 [\" + userName + \"] 吗？\")) {\r\n            return;\r\n");
    protected static final byte[] _jsp_42749 = b("        }\r\n\r\n        jQuery.ajax({\r\n            \"type\": \"get\",\r\n            \"url\": \"?action=admin.user.delete&userName=\" + encodeURIComponent(userName),\r\n");
    protected static final byte[] _jsp_42750 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_42751 = b("            },\r\n            \"success\": function(response) {\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_42752 = b("                    alert(response.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_42753 = b("                window.location.reload();\r\n            }\r\n        });\r\n    });\r\n");
    protected static final byte[] _jsp_42754 = b("\r\n    jQuery(\"table tr td a.as-admin\").click(function() {\r\n        var userName = this.getAttribute(\"userName\");\r\n");
    protected static final byte[] _jsp_42755 = b("\r\n        if(!window.confirm(\"管理员只能有一个，设置为管理员后之前的管理员将降为普通用户，确定继续吗？\")) {\r\n            return;\r\n");
    protected static final byte[] _jsp_42756 = b("        }\r\n\r\n        jQuery.ajax({\r\n            \"type\": \"get\",\r\n            \"url\": \"?action=admin.user.asadmin&userName=\" + encodeURIComponent(userName),\r\n");
    protected static final byte[] _jsp_42757 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_42758 = b("            },\r\n            \"success\": function(response) {\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_42759 = b("                    alert(response.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_42760 = b("                window.location.reload();\r\n            }\r\n        });\r\n    });\r\n");
    protected static final byte[] _jsp_42761 = b("});\r\n//-->\r\n</script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_42763 = b("\">\r\n<div class=\"menu-bar\">\r\n    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_42764 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_42765 = b("    <span class=\"seperator\"></span>\r\n</div>\r\n<div class=\"form\">\r\n    <div class=\"title\"><h4>查询用户</h4></div>\r\n");
    protected static final byte[] _jsp_42766 = b("    <div style=\"margin: 10px 0px; font-size: 13px;\">请先输入用户名查询用户:</div>\r\n    <div style=\"margin: 10px 0px;\">\r\n");
    protected static final byte[] _jsp_42767 = b("        <input name=\"userName\" type=\"text\" class=\"text w200\" placeholder=\"User Name\" value=\"");
    protected static final byte[] _jsp_42769 = b("\"/>\r\n        <input name=\"query\" type=\"button\" class=\"button\" value=\"查询\"/>\r\n    </div>\r\n");
    protected static final byte[] _jsp_42770 = b("    <table id=\"host-table\" class=\"list\">\r\n        <tr class=\"head\">\r\n            <td>用户名</td>\r\n");
    protected static final byte[] _jsp_42771 = b("            <td>注册时间</td>\r\n            <td>操作</td>\r\n        </tr>\r\n        ");
    protected static final byte[] _jsp_42773 = b("        <tr userName=\"");
    protected static final byte[] _jsp_42775 = b("\">\r\n            <td class=\"w200\">");
    protected static final byte[] _jsp_42777 = b("</td>\r\n            <td class=\"w400\">");
    protected static final byte[] _jsp_42779 = b("</td>\r\n            <td>\r\n                <a class=\"btn\" href=\"?action=admin.user.edit&userName=");
    protected static final byte[] _jsp_42781 = b("\">修改</a>\r\n                <a class=\"btn delete\" href=\"javascript:void(0)\" userName=\"");
    protected static final byte[] _jsp_42783 = b("\">刪除</a>\r\n                <a class=\"btn as-admin\" href=\"javascript:void(0)\" userName=\"");
    protected static final byte[] _jsp_42785 = b("\">设置为管理员</a>\r\n            </td>\r\n        </tr>\r\n        ");
    protected static final byte[] _jsp_42787 = b("    </table>\r\n    ");
    protected static final byte[] _jsp_42789 = b("    <div style=\"margin: 10px 0px;\">无查询条件或者无数据。</div>\r\n    ");
    protected static final byte[] _jsp_42791 = b("</div>\r\n<div id=\"pageContext\" style=\"display: none;\"></div>\r\n</body>\r\n</html>\r\n");

}
