/*
 * $RCSfile: UserHostPolicyTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;


/**
 * <p>Title: UserHostPolicyTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class UserHostPolicyTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final UserHostPolicyTemplate instance = new UserHostPolicyTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_22382, 0, _jsp_22382.length);
        out.write(_jsp_22383, 0, _jsp_22383.length);
        out.write(_jsp_22384, 0, _jsp_22384.length);
        out.write(_jsp_22385, 0, _jsp_22385.length);
        out.write(_jsp_22386, 0, _jsp_22386.length);
        this.write(out, (App.hash()));
        out.write(_jsp_22388, 0, _jsp_22388.length);
        out.write(_jsp_22389, 0, _jsp_22389.length);
        this.write(out, (App.hash()));
        out.write(_jsp_22391, 0, _jsp_22391.length);
        out.write(_jsp_22392, 0, _jsp_22392.length);
        out.write(_jsp_22393, 0, _jsp_22393.length);
        out.write(_jsp_22394, 0, _jsp_22394.length);
        out.write(_jsp_22395, 0, _jsp_22395.length);
        out.write(_jsp_22396, 0, _jsp_22396.length);
        out.write(_jsp_22397, 0, _jsp_22397.length);
        out.write(_jsp_22398, 0, _jsp_22398.length);
        out.write(_jsp_22399, 0, _jsp_22399.length);
        out.write(_jsp_22400, 0, _jsp_22400.length);
        out.write(_jsp_22401, 0, _jsp_22401.length);
        out.write(_jsp_22402, 0, _jsp_22402.length);
        out.write(_jsp_22403, 0, _jsp_22403.length);
        out.write(_jsp_22404, 0, _jsp_22404.length);
        out.write(_jsp_22405, 0, _jsp_22405.length);
        out.write(_jsp_22406, 0, _jsp_22406.length);
        out.write(_jsp_22407, 0, _jsp_22407.length);
        out.write(_jsp_22408, 0, _jsp_22408.length);
        out.write(_jsp_22409, 0, _jsp_22409.length);
        out.write(_jsp_22410, 0, _jsp_22410.length);
        out.write(_jsp_22411, 0, _jsp_22411.length);
        out.write(_jsp_22412, 0, _jsp_22412.length);
        out.write(_jsp_22413, 0, _jsp_22413.length);
        out.write(_jsp_22414, 0, _jsp_22414.length);
        out.write(_jsp_22415, 0, _jsp_22415.length);
        out.write(_jsp_22416, 0, _jsp_22416.length);
        out.write(_jsp_22417, 0, _jsp_22417.length);
        out.write(_jsp_22418, 0, _jsp_22418.length);
        out.write(_jsp_22419, 0, _jsp_22419.length);
        out.write(_jsp_22420, 0, _jsp_22420.length);
        out.write(_jsp_22421, 0, _jsp_22421.length);
        out.write(_jsp_22422, 0, _jsp_22422.length);
        out.write(_jsp_22423, 0, _jsp_22423.length);
        out.write(_jsp_22424, 0, _jsp_22424.length);
        out.write(_jsp_22425, 0, _jsp_22425.length);
        out.write(_jsp_22426, 0, _jsp_22426.length);
        out.write(_jsp_22427, 0, _jsp_22427.length);
        out.write(_jsp_22428, 0, _jsp_22428.length);
        out.write(_jsp_22429, 0, _jsp_22429.length);
        out.write(_jsp_22430, 0, _jsp_22430.length);
        out.write(_jsp_22431, 0, _jsp_22431.length);
        out.write(_jsp_22432, 0, _jsp_22432.length);
        out.write(_jsp_22433, 0, _jsp_22433.length);
        out.write(_jsp_22434, 0, _jsp_22434.length);
        out.write(_jsp_22435, 0, _jsp_22435.length);
        out.write(_jsp_22436, 0, _jsp_22436.length);
        out.write(_jsp_22437, 0, _jsp_22437.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_22439, 0, _jsp_22439.length);

        out.flush();
    }

    protected static final byte[] _jsp_22382 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_22383 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_22384 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_22385 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_22386 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css&v=");
    protected static final byte[] _jsp_22388 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_22389 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js&v=");
    protected static final byte[] _jsp_22391 = b("\"></script>\r\n<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    var showHostList = function(userName, list) {\r\n");
    protected static final byte[] _jsp_22392 = b("        var table = document.getElementById(\"host-table\");\r\n        jQuery(table).find(\"tr.item\").remove();\r\n");
    protected static final byte[] _jsp_22393 = b("\r\n        if(list == null || list.length < 1) {\r\n            return;\r\n        }\r\n");
    protected static final byte[] _jsp_22394 = b("\r\n        for(var i = 0; i < list.length; i++) {\r\n            var hostName = list[i];\r\n");
    protected static final byte[] _jsp_22395 = b("            var tr = table.insertRow(-1);\r\n            var td1 = tr.insertCell(-1);\r\n");
    protected static final byte[] _jsp_22396 = b("            var td2 = tr.insertCell(-1);\r\n\r\n            tr.className = \"item\";\r\n");
    protected static final byte[] _jsp_22397 = b("            td1.innerHTML = hostName;\r\n            td2.innerHTML = \"<a class=\\\"btn delete\\\" href=\\\"javascript:void(0)\\\" userName=\\\"\" + userName + \"\\\" hostName=\\\"\" + hostName + \"\\\">删除</a>\";\r\n");
    protected static final byte[] _jsp_22398 = b("        }\r\n        jQuery(\"#host-list\").show();\r\n    };\r\n\r\n    jQuery(\"input[name=query]\").click(function() {\r\n");
    protected static final byte[] _jsp_22399 = b("        var userName = jQuery.trim(jQuery(\"input[name=userName]\").val());\r\n\r\n        if(userName.length < 1) {\r\n");
    protected static final byte[] _jsp_22400 = b("            alert(\"请输入用户名！\");\r\n            return;\r\n        }\r\n\r\n        var src = jQuery(this);\r\n");
    protected static final byte[] _jsp_22401 = b("        src.prop(\"disabled\", true);\r\n        src.prop(\"class\", \"button disabled\");\r\n");
    protected static final byte[] _jsp_22402 = b("        jQuery.ajax({\r\n            \"type\": \"get\",\r\n            \"url\": \"?action=admin.policy.getHostPolicy&userName=\" + encodeURIComponent(userName),\r\n");
    protected static final byte[] _jsp_22403 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                src.prop(\"disabled\", false);\r\n");
    protected static final byte[] _jsp_22404 = b("                src.prop(\"class\", \"button\");\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_22405 = b("            },\r\n            \"success\": function(response) {\r\n                src.prop(\"disabled\", false);\r\n");
    protected static final byte[] _jsp_22406 = b("                src.prop(\"class\", \"button\");\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_22407 = b("                    alert(response.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_22408 = b("\r\n                jQuery(\"#host-list\").show();\r\n                showHostList(userName, response.value);\r\n");
    protected static final byte[] _jsp_22409 = b("            }\r\n        });\r\n    });\r\n\r\n    jQuery(\"input[name=flush]\").click(function() {\r\n");
    protected static final byte[] _jsp_22410 = b("        var userName = jQuery.trim(jQuery(\"input[name=userName]\").val());\r\n\r\n        if(userName.length < 1) {\r\n");
    protected static final byte[] _jsp_22411 = b("            return;\r\n        }\r\n\r\n        jQuery.ajax({\r\n            \"type\": \"get\",\r\n");
    protected static final byte[] _jsp_22412 = b("            \"url\": \"?action=admin.policy.host.flush&userName=\" + encodeURIComponent(userName),\r\n");
    protected static final byte[] _jsp_22413 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_22414 = b("            },\r\n            \"success\": function(response) {\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_22415 = b("                    alert(response.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_22416 = b("                alert(\"刷新成功，请重新查询！\");\r\n            }\r\n        });\r\n    });\r\n});\r\n");
    protected static final byte[] _jsp_22417 = b("\r\njQuery(function() {\r\n    var remove = function(src) {\r\n        var userName = src.getAttribute(\"userName\");\r\n");
    protected static final byte[] _jsp_22418 = b("        var hostName = src.getAttribute(\"hostName\");\r\n\r\n        if(hostName == null || hostName == undefined) {\r\n");
    protected static final byte[] _jsp_22419 = b("            return;\r\n        }\r\n\r\n        jQuery.ajax({\r\n            \"type\": \"get\",\r\n");
    protected static final byte[] _jsp_22420 = b("            \"url\": \"?action=admin.policy.host.remove&userName=\" + encodeURIComponent(userName) + \"&hostName=\" + encodeURIComponent(hostName),\r\n");
    protected static final byte[] _jsp_22421 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_22422 = b("            },\r\n            \"success\": function(response) {\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_22423 = b("                    alert(response.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_22424 = b("                jQuery(src).closest(\"tr\").remove();\r\n            }\r\n        });\r\n");
    protected static final byte[] _jsp_22425 = b("    };\r\n\r\n    jQuery(\"#host-table\").click(function(event) {\r\n        var src = (event.target || event.srcElement);\r\n");
    protected static final byte[] _jsp_22426 = b("        var className = src.className;\r\n\r\n        if(className == null) {\r\n            return;\r\n");
    protected static final byte[] _jsp_22427 = b("        }\r\n\r\n        if(className.indexOf(\"delete\") > -1) {\r\n            remove(src);\r\n");
    protected static final byte[] _jsp_22428 = b("        }\r\n    });\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n<body>\r\n<div class=\"menu-bar\">\r\n");
    protected static final byte[] _jsp_22429 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_22430 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_22431 = b("    <span class=\"seperator\"></span>\r\n    <a class=\"button add\" href=\"javascript:void(0)\" onclick=\"window.location.href='?action=admin.user.host.edit';\"><span class=\"add\"></span>添加</a>\r\n");
    protected static final byte[] _jsp_22432 = b("</div>\r\n<div class=\"form\">\r\n    <div style=\"margin: 10px 0px; font-size: 13px;\">请输入用户名查询该用户拥有的主机权限:</div>\r\n");
    protected static final byte[] _jsp_22433 = b("    <div style=\"margin: 10px 0px;\">\r\n        <input name=\"userName\" type=\"text\" class=\"text w200\" placeholder=\"User Name\" value=\"\"/>\r\n");
    protected static final byte[] _jsp_22434 = b("        <input name=\"query\" type=\"button\" class=\"button\" value=\"查询\"/>\r\n        <input name=\"flush\" type=\"button\" class=\"button\" value=\"刷新缓存\"/>\r\n");
    protected static final byte[] _jsp_22435 = b("    </div>\r\n</div>\r\n<div id=\"host-list\" class=\"form\" style=\"display: none;\">\r\n    <table id=\"host-table\" class=\"list\">\r\n");
    protected static final byte[] _jsp_22436 = b("        <tr class=\"head\">\r\n            <td>Host</td>\r\n            <td>操作</td>\r\n        </tr>\r\n");
    protected static final byte[] _jsp_22437 = b("    </table>\r\n</div>\r\n<div id=\"pageContext\" style=\"display: none;\" contextPath=\"");
    protected static final byte[] _jsp_22439 = b("\"></div>\r\n</body>\r\n</html>\r\n");

}
