/*
 * $RCSfile: UserEditTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;
import com.skin.finder.config.ConfigFactory;


/**
 * <p>Title: UserEditTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class UserEditTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final UserEditTemplate instance = new UserEditTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_76285, 0, _jsp_76285.length);
        out.write(_jsp_76286, 0, _jsp_76286.length);
        out.write(_jsp_76287, 0, _jsp_76287.length);
        out.write(_jsp_76288, 0, _jsp_76288.length);
        out.write(_jsp_76289, 0, _jsp_76289.length);
        this.write(out, (App.hash()));
        out.write(_jsp_76291, 0, _jsp_76291.length);
        out.write(_jsp_76292, 0, _jsp_76292.length);
        this.write(out, (App.hash()));
        out.write(_jsp_76294, 0, _jsp_76294.length);
        out.write(_jsp_76295, 0, _jsp_76295.length);
        out.write(_jsp_76296, 0, _jsp_76296.length);
        out.write(_jsp_76297, 0, _jsp_76297.length);
        out.write(_jsp_76298, 0, _jsp_76298.length);
        out.write(_jsp_76299, 0, _jsp_76299.length);
        out.write(_jsp_76300, 0, _jsp_76300.length);
        out.write(_jsp_76301, 0, _jsp_76301.length);
        out.write(_jsp_76302, 0, _jsp_76302.length);
        out.write(_jsp_76303, 0, _jsp_76303.length);
        out.write(_jsp_76304, 0, _jsp_76304.length);
        out.write(_jsp_76305, 0, _jsp_76305.length);
        out.write(_jsp_76306, 0, _jsp_76306.length);
        out.write(_jsp_76307, 0, _jsp_76307.length);
        out.write(_jsp_76308, 0, _jsp_76308.length);
        out.write(_jsp_76309, 0, _jsp_76309.length);
        out.write(_jsp_76310, 0, _jsp_76310.length);
        out.write(_jsp_76311, 0, _jsp_76311.length);
        out.write(_jsp_76312, 0, _jsp_76312.length);
        out.write(_jsp_76313, 0, _jsp_76313.length);
        out.write(_jsp_76314, 0, _jsp_76314.length);
        out.write(_jsp_76315, 0, _jsp_76315.length);
        out.write(_jsp_76316, 0, _jsp_76316.length);
        this.write(out, request.getAttribute("userName"));
        out.write(_jsp_76318, 0, _jsp_76318.length);
        out.write(_jsp_76319, 0, _jsp_76319.length);
        out.write(_jsp_76320, 0, _jsp_76320.length);
        out.write(_jsp_76321, 0, _jsp_76321.length);
        out.write(_jsp_76322, 0, _jsp_76322.length);
        out.write(_jsp_76323, 0, _jsp_76323.length);
        this.write(out, (System.currentTimeMillis()));
        out.write(_jsp_76325, 0, _jsp_76325.length);
        this.write(out, (ConfigFactory.getPublicKey()));
        out.write(_jsp_76327, 0, _jsp_76327.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_76329, 0, _jsp_76329.length);

        out.flush();
    }

    protected static final byte[] _jsp_76285 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_76286 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_76287 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_76288 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_76289 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css&v=");
    protected static final byte[] _jsp_76291 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_76292 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js&v=");
    protected static final byte[] _jsp_76294 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jsencrypt.min.js\"></script>\r\n");
    protected static final byte[] _jsp_76295 = b("<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    var encrypt = function(userName, password, timestamp) {\r\n");
    protected static final byte[] _jsp_76296 = b("        var params = [];\r\n        var encrypt = new JSEncrypt();\r\n        encrypt.setPublicKey(jQuery(\"#publicKey\").val());\r\n");
    protected static final byte[] _jsp_76297 = b("        params[params.length] = \"userName=\" + encodeURIComponent(encrypt.encrypt(userName + \"|\" + timestamp));\r\n");
    protected static final byte[] _jsp_76298 = b("        params[params.length] = \"password=\" + encodeURIComponent(encrypt.encrypt(password + \"|\" + timestamp));\r\n");
    protected static final byte[] _jsp_76299 = b("        params[params.length] = \"timestamp=\" + timestamp;\r\n        return params.join(\"&\");\r\n");
    protected static final byte[] _jsp_76300 = b("    };\r\n\r\n    jQuery(\"#submit\").click(function() {\r\n        var timestamp = jQuery.trim(jQuery(\"#timestamp\").val());\r\n");
    protected static final byte[] _jsp_76301 = b("        var userName = jQuery.trim(jQuery(\"#s1\").val());\r\n        var password = jQuery.trim(jQuery(\"#s2\").val());\r\n");
    protected static final byte[] _jsp_76302 = b("\r\n        if(userName.length < 1) {\r\n            alert(\"用户名不能为空！\");\r\n            return;\r\n");
    protected static final byte[] _jsp_76303 = b("        }\r\n\r\n        if(password.length < 1) {\r\n            alert(\"密码不能为空！\");\r\n            return;\r\n");
    protected static final byte[] _jsp_76304 = b("        }\r\n\r\n        var requestURI = window.location.pathname;\r\n        var params = encrypt(userName, password, timestamp);\r\n");
    protected static final byte[] _jsp_76305 = b("\r\n        jQuery.ajax({\r\n            type: \"post\",\r\n            url: requestURI + \"?action=admin.user.save\",\r\n");
    protected static final byte[] _jsp_76306 = b("            dataType: \"json\",\r\n            data: params,\r\n            error: function(req, status, error) {\r\n");
    protected static final byte[] _jsp_76307 = b("                alert(\"系统错误，请稍后再试！\");\r\n            },\r\n            success: function(result) {\r\n");
    protected static final byte[] _jsp_76308 = b("                if(result.status != 200) {\r\n                    alert(result.message);\r\n");
    protected static final byte[] _jsp_76309 = b("                    return;\r\n                }\r\n                alert(\"操作成功！\");\r\n");
    protected static final byte[] _jsp_76310 = b("                window.location.href = \"?action=admin.user.query\";\r\n            }\r\n");
    protected static final byte[] _jsp_76311 = b("        });\r\n    });\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n<body>\r\n<div class=\"menu-bar\">\r\n");
    protected static final byte[] _jsp_76312 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_76313 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_76314 = b("    <span class=\"seperator\"></span>\r\n</div>\r\n<div class=\"form\">\r\n    <div class=\"title\"><h4>用户编辑</h4></div>\r\n");
    protected static final byte[] _jsp_76315 = b("    <div class=\"form-row\">\r\n        <div class=\"form-label\">User Name：</div>\r\n        <div class=\"form-c300\">\r\n");
    protected static final byte[] _jsp_76316 = b("            <div class=\"form-field\">\r\n                <input id=\"s1\" type=\"text\" class=\"text w200\" placeholder=\"User Name\" value=\"");
    protected static final byte[] _jsp_76318 = b("\"/>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">User Name .</div>\r\n");
    protected static final byte[] _jsp_76319 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">Password:</div>\r\n");
    protected static final byte[] _jsp_76320 = b("        <div class=\"form-c300\">\r\n            <div class=\"form-field\">\r\n                <input id=\"s2\" type=\"text\" class=\"text w200\" placeholder=\"password\" value=\"\"/>\r\n");
    protected static final byte[] _jsp_76321 = b("            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">Password .</div>\r\n");
    protected static final byte[] _jsp_76322 = b("        </div>\r\n    </div>\r\n\r\n    <div class=\"button\">\r\n        <button id=\"submit\" class=\"button ensure\">保 存</button>\r\n");
    protected static final byte[] _jsp_76323 = b("    </div>\r\n</div>\r\n<div style=\"display: none;\">\r\n    <input id=\"timestamp\" type=\"text\" value=\"");
    protected static final byte[] _jsp_76325 = b("\"/>\r\n    <textarea id=\"publicKey\">");
    protected static final byte[] _jsp_76327 = b("</textarea>\r\n</div>\r\n<div id=\"pageContext\" style=\"display: none;\" contextPath=\"");
    protected static final byte[] _jsp_76329 = b("\"></div>\r\n</body>\r\n</html>");

}
