/*
 * $RCSfile: UserFilePolicyTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;


/**
 * <p>Title: UserFilePolicyTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class UserFilePolicyTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final UserFilePolicyTemplate instance = new UserFilePolicyTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_26340, 0, _jsp_26340.length);
        out.write(_jsp_26341, 0, _jsp_26341.length);
        out.write(_jsp_26342, 0, _jsp_26342.length);
        out.write(_jsp_26343, 0, _jsp_26343.length);
        out.write(_jsp_26344, 0, _jsp_26344.length);
        this.write(out, (App.hash()));
        out.write(_jsp_26346, 0, _jsp_26346.length);
        out.write(_jsp_26347, 0, _jsp_26347.length);
        this.write(out, (App.hash()));
        out.write(_jsp_26349, 0, _jsp_26349.length);
        out.write(_jsp_26350, 0, _jsp_26350.length);
        out.write(_jsp_26351, 0, _jsp_26351.length);
        out.write(_jsp_26352, 0, _jsp_26352.length);
        out.write(_jsp_26353, 0, _jsp_26353.length);
        out.write(_jsp_26354, 0, _jsp_26354.length);
        out.write(_jsp_26355, 0, _jsp_26355.length);
        out.write(_jsp_26356, 0, _jsp_26356.length);
        out.write(_jsp_26357, 0, _jsp_26357.length);
        out.write(_jsp_26358, 0, _jsp_26358.length);
        out.write(_jsp_26359, 0, _jsp_26359.length);
        out.write(_jsp_26360, 0, _jsp_26360.length);
        out.write(_jsp_26361, 0, _jsp_26361.length);
        out.write(_jsp_26362, 0, _jsp_26362.length);
        out.write(_jsp_26363, 0, _jsp_26363.length);
        out.write(_jsp_26364, 0, _jsp_26364.length);
        out.write(_jsp_26365, 0, _jsp_26365.length);
        out.write(_jsp_26366, 0, _jsp_26366.length);
        out.write(_jsp_26367, 0, _jsp_26367.length);
        out.write(_jsp_26368, 0, _jsp_26368.length);
        out.write(_jsp_26369, 0, _jsp_26369.length);
        out.write(_jsp_26370, 0, _jsp_26370.length);
        out.write(_jsp_26371, 0, _jsp_26371.length);
        out.write(_jsp_26372, 0, _jsp_26372.length);
        out.write(_jsp_26373, 0, _jsp_26373.length);
        out.write(_jsp_26374, 0, _jsp_26374.length);
        out.write(_jsp_26375, 0, _jsp_26375.length);
        out.write(_jsp_26376, 0, _jsp_26376.length);
        out.write(_jsp_26377, 0, _jsp_26377.length);
        out.write(_jsp_26378, 0, _jsp_26378.length);
        out.write(_jsp_26379, 0, _jsp_26379.length);
        out.write(_jsp_26380, 0, _jsp_26380.length);
        out.write(_jsp_26381, 0, _jsp_26381.length);
        out.write(_jsp_26382, 0, _jsp_26382.length);
        out.write(_jsp_26383, 0, _jsp_26383.length);
        out.write(_jsp_26384, 0, _jsp_26384.length);
        out.write(_jsp_26385, 0, _jsp_26385.length);
        out.write(_jsp_26386, 0, _jsp_26386.length);
        out.write(_jsp_26387, 0, _jsp_26387.length);
        out.write(_jsp_26388, 0, _jsp_26388.length);
        out.write(_jsp_26389, 0, _jsp_26389.length);
        out.write(_jsp_26390, 0, _jsp_26390.length);
        out.write(_jsp_26391, 0, _jsp_26391.length);
        out.write(_jsp_26392, 0, _jsp_26392.length);
        out.write(_jsp_26393, 0, _jsp_26393.length);
        out.write(_jsp_26394, 0, _jsp_26394.length);
        out.write(_jsp_26395, 0, _jsp_26395.length);
        out.write(_jsp_26396, 0, _jsp_26396.length);
        out.write(_jsp_26397, 0, _jsp_26397.length);
        out.write(_jsp_26398, 0, _jsp_26398.length);
        out.write(_jsp_26399, 0, _jsp_26399.length);
        out.write(_jsp_26400, 0, _jsp_26400.length);
        out.write(_jsp_26401, 0, _jsp_26401.length);
        out.write(_jsp_26402, 0, _jsp_26402.length);
        out.write(_jsp_26403, 0, _jsp_26403.length);
        out.write(_jsp_26404, 0, _jsp_26404.length);
        out.write(_jsp_26405, 0, _jsp_26405.length);
        out.write(_jsp_26406, 0, _jsp_26406.length);
        out.write(_jsp_26407, 0, _jsp_26407.length);
        out.write(_jsp_26408, 0, _jsp_26408.length);
        out.write(_jsp_26409, 0, _jsp_26409.length);
        out.write(_jsp_26410, 0, _jsp_26410.length);
        out.write(_jsp_26411, 0, _jsp_26411.length);
        out.write(_jsp_26412, 0, _jsp_26412.length);
        out.write(_jsp_26413, 0, _jsp_26413.length);
        out.write(_jsp_26414, 0, _jsp_26414.length);
        out.write(_jsp_26415, 0, _jsp_26415.length);
        out.write(_jsp_26416, 0, _jsp_26416.length);
        out.write(_jsp_26417, 0, _jsp_26417.length);
        out.write(_jsp_26418, 0, _jsp_26418.length);
        out.write(_jsp_26419, 0, _jsp_26419.length);
        out.write(_jsp_26420, 0, _jsp_26420.length);
        out.write(_jsp_26421, 0, _jsp_26421.length);
        out.write(_jsp_26422, 0, _jsp_26422.length);
        out.write(_jsp_26423, 0, _jsp_26423.length);
        out.write(_jsp_26424, 0, _jsp_26424.length);
        out.write(_jsp_26425, 0, _jsp_26425.length);
        out.write(_jsp_26426, 0, _jsp_26426.length);
        out.write(_jsp_26427, 0, _jsp_26427.length);
        out.write(_jsp_26428, 0, _jsp_26428.length);
        out.write(_jsp_26429, 0, _jsp_26429.length);
        out.write(_jsp_26430, 0, _jsp_26430.length);
        out.write(_jsp_26431, 0, _jsp_26431.length);
        out.write(_jsp_26432, 0, _jsp_26432.length);
        out.write(_jsp_26433, 0, _jsp_26433.length);
        out.write(_jsp_26434, 0, _jsp_26434.length);
        out.write(_jsp_26435, 0, _jsp_26435.length);
        out.write(_jsp_26436, 0, _jsp_26436.length);
        out.write(_jsp_26437, 0, _jsp_26437.length);
        out.write(_jsp_26438, 0, _jsp_26438.length);
        out.write(_jsp_26439, 0, _jsp_26439.length);
        out.write(_jsp_26440, 0, _jsp_26440.length);
        out.write(_jsp_26441, 0, _jsp_26441.length);
        out.write(_jsp_26442, 0, _jsp_26442.length);
        out.write(_jsp_26443, 0, _jsp_26443.length);
        out.write(_jsp_26444, 0, _jsp_26444.length);
        out.write(_jsp_26445, 0, _jsp_26445.length);
        out.write(_jsp_26446, 0, _jsp_26446.length);
        out.write(_jsp_26447, 0, _jsp_26447.length);
        out.write(_jsp_26448, 0, _jsp_26448.length);
        out.write(_jsp_26449, 0, _jsp_26449.length);
        out.write(_jsp_26450, 0, _jsp_26450.length);
        out.write(_jsp_26451, 0, _jsp_26451.length);
        out.write(_jsp_26452, 0, _jsp_26452.length);
        out.write(_jsp_26453, 0, _jsp_26453.length);
        out.write(_jsp_26454, 0, _jsp_26454.length);
        out.write(_jsp_26455, 0, _jsp_26455.length);
        out.write(_jsp_26456, 0, _jsp_26456.length);
        out.write(_jsp_26457, 0, _jsp_26457.length);
        out.write(_jsp_26458, 0, _jsp_26458.length);
        out.write(_jsp_26459, 0, _jsp_26459.length);
        out.write(_jsp_26460, 0, _jsp_26460.length);
        out.write(_jsp_26461, 0, _jsp_26461.length);
        out.write(_jsp_26462, 0, _jsp_26462.length);
        out.write(_jsp_26463, 0, _jsp_26463.length);
        out.write(_jsp_26464, 0, _jsp_26464.length);
        out.write(_jsp_26465, 0, _jsp_26465.length);
        out.write(_jsp_26466, 0, _jsp_26466.length);
        out.write(_jsp_26467, 0, _jsp_26467.length);
        out.write(_jsp_26468, 0, _jsp_26468.length);
        out.write(_jsp_26469, 0, _jsp_26469.length);
        out.write(_jsp_26470, 0, _jsp_26470.length);
        out.write(_jsp_26471, 0, _jsp_26471.length);
        out.write(_jsp_26472, 0, _jsp_26472.length);
        out.write(_jsp_26473, 0, _jsp_26473.length);
        out.write(_jsp_26474, 0, _jsp_26474.length);
        out.write(_jsp_26475, 0, _jsp_26475.length);
        out.write(_jsp_26476, 0, _jsp_26476.length);
        out.write(_jsp_26477, 0, _jsp_26477.length);
        out.write(_jsp_26478, 0, _jsp_26478.length);
        out.write(_jsp_26479, 0, _jsp_26479.length);
        out.write(_jsp_26480, 0, _jsp_26480.length);
        out.write(_jsp_26481, 0, _jsp_26481.length);
        out.write(_jsp_26482, 0, _jsp_26482.length);

    String[] hosts = (String[])(request.getAttribute("hosts"));

    if(hosts == null) {
        hosts = new String[0];
    }

        out.write(_jsp_26484, 0, _jsp_26484.length);
        out.write(_jsp_26485, 0, _jsp_26485.length);
        out.write(_jsp_26486, 0, _jsp_26486.length);

            for(String hostName : hosts) {
        
        out.write(_jsp_26488, 0, _jsp_26488.length);
        this.write(out, (hostName));
        out.write(_jsp_26490, 0, _jsp_26490.length);
        this.write(out, (hostName));
        out.write(_jsp_26492, 0, _jsp_26492.length);

            }
        
        out.write(_jsp_26494, 0, _jsp_26494.length);
        out.write(_jsp_26495, 0, _jsp_26495.length);
        out.write(_jsp_26496, 0, _jsp_26496.length);
        out.write(_jsp_26497, 0, _jsp_26497.length);
        out.write(_jsp_26498, 0, _jsp_26498.length);
        out.write(_jsp_26499, 0, _jsp_26499.length);
        out.write(_jsp_26500, 0, _jsp_26500.length);
        out.write(_jsp_26501, 0, _jsp_26501.length);
        out.write(_jsp_26502, 0, _jsp_26502.length);
        out.write(_jsp_26503, 0, _jsp_26503.length);
        out.write(_jsp_26504, 0, _jsp_26504.length);
        out.write(_jsp_26505, 0, _jsp_26505.length);
        out.write(_jsp_26506, 0, _jsp_26506.length);
        out.write(_jsp_26507, 0, _jsp_26507.length);
        out.write(_jsp_26508, 0, _jsp_26508.length);
        out.write(_jsp_26509, 0, _jsp_26509.length);
        out.write(_jsp_26510, 0, _jsp_26510.length);
        out.write(_jsp_26511, 0, _jsp_26511.length);
        out.write(_jsp_26512, 0, _jsp_26512.length);
        out.write(_jsp_26513, 0, _jsp_26513.length);
        out.write(_jsp_26514, 0, _jsp_26514.length);
        out.write(_jsp_26515, 0, _jsp_26515.length);
        out.write(_jsp_26516, 0, _jsp_26516.length);
        out.write(_jsp_26517, 0, _jsp_26517.length);
        out.write(_jsp_26518, 0, _jsp_26518.length);
        out.write(_jsp_26519, 0, _jsp_26519.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_26521, 0, _jsp_26521.length);

        out.flush();
    }

    protected static final byte[] _jsp_26340 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_26341 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_26342 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_26343 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_26344 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css&v=");
    protected static final byte[] _jsp_26346 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_26347 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js&v=");
    protected static final byte[] _jsp_26349 = b("\"></script>\r\n<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    var getOptions = function(name, list, value) {\r\n");
    protected static final byte[] _jsp_26350 = b("        var b = [];\r\n        b[b.length] = \"<select name=\\\"\" + name + \"\\\" class=\\\"select\\\">\";\r\n");
    protected static final byte[] _jsp_26351 = b("\r\n        for(var i = 0; i < list.length; i++) {\r\n            if(list[i] == value) {\r\n");
    protected static final byte[] _jsp_26352 = b("                b[b.length] = \"<option value=\\\"\" + list[i] + \"\\\" selected=\\\"true\\\">\" + list[i] + \"</option>\";\r\n");
    protected static final byte[] _jsp_26353 = b("            }\r\n            else {\r\n                b[b.length] = \"<option value=\\\"\" + list[i] + \"\\\">\" + list[i] + \"</option>\";\r\n");
    protected static final byte[] _jsp_26354 = b("            }\r\n        }\r\n        b[b.length] = \"</select>\";\r\n        return b.join(\"\");\r\n");
    protected static final byte[] _jsp_26355 = b("    };\r\n\r\n    var showPermissionList = function(userName, hostName, bean) {\r\n        var table = document.getElementById(\"permission-table\");\r\n");
    protected static final byte[] _jsp_26356 = b("        jQuery(table).find(\"tr.item\").remove();\r\n\r\n        var workspaces = bean.workspaces;\r\n");
    protected static final byte[] _jsp_26357 = b("        var permissions = bean.permissions;\r\n\r\n        table.setAttribute(\"hostName\", hostName);\r\n");
    protected static final byte[] _jsp_26358 = b("        table.setAttribute(\"workspaces\", workspaces.join(\",\"));\r\n\r\n        if(permissions == null || permissions.length < 1) {\r\n");
    protected static final byte[] _jsp_26359 = b("            return;\r\n        }\r\n\r\n        var compare = function(s1, s2) {\r\n            if(s1 == s2) {\r\n");
    protected static final byte[] _jsp_26360 = b("                return 0;\r\n            }\r\n\r\n            if(s1 > s2) {\r\n                return 1;\r\n");
    protected static final byte[] _jsp_26361 = b("            }\r\n            else {\r\n                return -1;\r\n            }\r\n        };\r\n");
    protected static final byte[] _jsp_26362 = b("\r\n        var comparator = function(p1, p2) {\r\n            var v = compare(p1.workspace, p2.workspace);\r\n");
    protected static final byte[] _jsp_26363 = b("\r\n            if(v == 0) {\r\n                return compare(p1.action, p2.action);\r\n");
    protected static final byte[] _jsp_26364 = b("            }\r\n            return v;\r\n        };\r\n\r\n        permissions.sort(comparator);\r\n");
    protected static final byte[] _jsp_26365 = b("\r\n        var colors = {\r\n            \"index\": 0,\r\n            \"values\": [\"#ffffff\", \"#f4f8c9\", \"#c2defb\", \"#fdc4c4\"],\r\n");
    protected static final byte[] _jsp_26366 = b("            \"next\": function() {\r\n                if(this.index >= this.values.length) {\r\n");
    protected static final byte[] _jsp_26367 = b("                    this.index = 0;\r\n                }\r\n                return this.values[this.index++];\r\n");
    protected static final byte[] _jsp_26368 = b("            }\r\n        };\r\n\r\n        var current = null;\r\n        var bgcolor = colors.next();\r\n");
    protected static final byte[] _jsp_26369 = b("        var actions = [\"read\", \"write\", \"delete\", \"download\"];\r\n\r\n        for(var i = 0; i < permissions.length; i++) {\r\n");
    protected static final byte[] _jsp_26370 = b("            var permission = permissions[i];\r\n            var tr = table.insertRow(-1);\r\n");
    protected static final byte[] _jsp_26371 = b("            var td1 = tr.insertCell(-1);\r\n            var td2 = tr.insertCell(-1);\r\n");
    protected static final byte[] _jsp_26372 = b("            var td3 = tr.insertCell(-1);\r\n            var td4 = tr.insertCell(-1);\r\n");
    protected static final byte[] _jsp_26373 = b("\r\n            if(current != permission.workspace) {\r\n                bgcolor = colors.next();\r\n");
    protected static final byte[] _jsp_26374 = b("                current = permission.workspace;\r\n            }\r\n\r\n            tr.className = \"item\";\r\n");
    protected static final byte[] _jsp_26375 = b("            td1.style.backgroundColor = bgcolor;\r\n            td1.innerHTML = getOptions(\"workspace\", workspaces, permission.workspace);\r\n");
    protected static final byte[] _jsp_26376 = b("            td2.innerHTML = getOptions(\"action\", actions, permission.action);\r\n            td3.innerHTML = \"<input name=\\\"pattern\\\" type=\\\"text\\\" class=\\\"text\\\" style=\\\"width: 80%; box-sizing: border-box;\\\" value=\\\"\" + permission.pattern + \"\\\"/>\";\r\n");
    protected static final byte[] _jsp_26377 = b("            td4.innerHTML = \"<a class=\\\"btn delete\\\" href=\\\"javascript:void(0)\\\" userName=\\\"\" + userName + \"\\\" hostName=\\\"\" + hostName + \"\\\" onclick=\\\"jQuery(this).closest('tr').remove();\\\">删除</a>\";\r\n");
    protected static final byte[] _jsp_26378 = b("        }\r\n    };\r\n\r\n    jQuery(\"#add-btn\").click(function() {\r\n        var table = document.getElementById(\"permission-table\");\r\n");
    protected static final byte[] _jsp_26379 = b("        var tr = table.insertRow(-1);\r\n        var td1 = tr.insertCell(-1);\r\n        var td2 = tr.insertCell(-1);\r\n");
    protected static final byte[] _jsp_26380 = b("        var td3 = tr.insertCell(-1);\r\n        var td4 = tr.insertCell(-1);\r\n        var workspaces = table.getAttribute(\"workspaces\").split(\",\");\r\n");
    protected static final byte[] _jsp_26381 = b("        var actions = [\"read\", \"write\", \"delete\", \"download\"];\r\n\r\n        tr.className = \"item\";\r\n");
    protected static final byte[] _jsp_26382 = b("        td1.innerHTML = getOptions(\"workspace\", workspaces, \"\");\r\n        td2.innerHTML = getOptions(\"action\", actions, \"read\");\r\n");
    protected static final byte[] _jsp_26383 = b("        td3.innerHTML = \"<input name=\\\"pattern\\\" type=\\\"text\\\" class=\\\"text\\\" style=\\\"width: 80%; box-sizing: border-box;\\\" value=\\\"/**\\\"/>\";\r\n");
    protected static final byte[] _jsp_26384 = b("        td4.innerHTML = \"<a class=\\\"btn delete\\\" href=\\\"javascript:void(0)\\\" onclick=\\\"jQuery(this).closest('tr').remove();\\\">删除</a>\";\r\n");
    protected static final byte[] _jsp_26385 = b("    });\r\n\r\n    jQuery(\"input[name=query]\").click(function() {\r\n        var userName = jQuery.trim(jQuery(\"input[name=userName]\").val());\r\n");
    protected static final byte[] _jsp_26386 = b("        var hostName = jQuery.trim(jQuery(\"select[name=hostName]\").val());\r\n\r\n        if(userName.length < 1) {\r\n");
    protected static final byte[] _jsp_26387 = b("            alert(\"userName 不能为空！\");\r\n            return;\r\n        }\r\n\r\n        if(hostName.length < 1) {\r\n");
    protected static final byte[] _jsp_26388 = b("            alert(\"hostName 不能为空！\");\r\n            return;\r\n        }\r\n\r\n        var src = jQuery(this);\r\n");
    protected static final byte[] _jsp_26389 = b("        src.prop(\"disabled\", true);\r\n        src.prop(\"class\", \"button disabled\");\r\n");
    protected static final byte[] _jsp_26390 = b("\r\n        var params = [];\r\n        params[params.length] = \"host=\" + encodeURIComponent(hostName);\r\n");
    protected static final byte[] _jsp_26391 = b("        params[params.length] = \"userName=\" + encodeURIComponent(userName);\r\n\r\n        jQuery.ajax({\r\n");
    protected static final byte[] _jsp_26392 = b("            \"type\": \"get\",\r\n            \"url\": \"?action=admin.policy.getFilePolicy&\" + params.join(\"&\"),\r\n");
    protected static final byte[] _jsp_26393 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                src.prop(\"disabled\", false);\r\n");
    protected static final byte[] _jsp_26394 = b("                src.prop(\"class\", \"button\");\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_26395 = b("            },\r\n            \"success\": function(response) {\r\n                src.prop(\"disabled\", false);\r\n");
    protected static final byte[] _jsp_26396 = b("                src.prop(\"class\", \"button\");\r\n\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_26397 = b("                    alert(response.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_26398 = b("                jQuery(\"#permission-panel\").show();\r\n                jQuery(\"#advance-panel\").hide();\r\n");
    protected static final byte[] _jsp_26399 = b("                showPermissionList(userName, hostName, response.value);\r\n            }\r\n");
    protected static final byte[] _jsp_26400 = b("        });\r\n    });\r\n\r\n    jQuery(\"input[name=flush]\").click(function() {\r\n        var userName = jQuery.trim(jQuery(\"input[name=userName]\").val());\r\n");
    protected static final byte[] _jsp_26401 = b("        var hostName = jQuery.trim(jQuery(\"select[name=hostName]\").val());\r\n\r\n        if(userName.length < 1) {\r\n");
    protected static final byte[] _jsp_26402 = b("            alert(\"userName 不能为空！\");\r\n            return;\r\n        }\r\n\r\n        if(hostName.length < 1) {\r\n");
    protected static final byte[] _jsp_26403 = b("            alert(\"hostName 不能为空！\");\r\n            return;\r\n        }\r\n\r\n        var src = jQuery(this);\r\n");
    protected static final byte[] _jsp_26404 = b("        src.prop(\"disabled\", true);\r\n        src.prop(\"class\", \"button disabled\");\r\n");
    protected static final byte[] _jsp_26405 = b("\r\n        var params = [];\r\n        params[params.length] = \"host=\" + encodeURIComponent(hostName);\r\n");
    protected static final byte[] _jsp_26406 = b("        params[params.length] = \"userName=\" + encodeURIComponent(userName);\r\n\r\n        jQuery.ajax({\r\n");
    protected static final byte[] _jsp_26407 = b("            \"type\": \"get\",\r\n            \"url\": \"?action=admin.policy.file.flush&\" + params.join(\"&\"),\r\n");
    protected static final byte[] _jsp_26408 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                src.prop(\"disabled\", false);\r\n");
    protected static final byte[] _jsp_26409 = b("                src.prop(\"class\", \"button\");\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_26410 = b("            },\r\n            \"success\": function(response) {\r\n                src.prop(\"disabled\", false);\r\n");
    protected static final byte[] _jsp_26411 = b("                src.prop(\"class\", \"button\");\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_26412 = b("                    alert(response.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_26413 = b("                alert(\"刷新成功，请重新查询！\");\r\n            }\r\n        });\r\n    });\r\n});\r\n");
    protected static final byte[] _jsp_26414 = b("\r\njQuery(function() {\r\n    var getUserPermission = function() {\r\n        var context = {};\r\n");
    protected static final byte[] _jsp_26415 = b("\r\n        jQuery(\"#permission-table tr\").each(function() {\r\n            var workspace = jQuery.trim(jQuery(this).find(\"select[name=workspace]\").val());\r\n");
    protected static final byte[] _jsp_26416 = b("            var pattern = jQuery.trim(jQuery(this).find(\"input[name=pattern]\").val());\r\n");
    protected static final byte[] _jsp_26417 = b("            var action = jQuery.trim(jQuery(this).find(\"select[name=action]\").val());\r\n");
    protected static final byte[] _jsp_26418 = b("\r\n            if(workspace.length < 1 || pattern.length < 1) {\r\n                return;\r\n");
    protected static final byte[] _jsp_26419 = b("            }\r\n\r\n            if(pattern.charAt(0) == \"!\") {\r\n                if(pattern.length < 2 || pattern.charAt(1) != \"/\") {\r\n");
    protected static final byte[] _jsp_26420 = b("                    return;\r\n                }\r\n            }\r\n            else if(pattern.charAt(0) != \"/\") {\r\n");
    protected static final byte[] _jsp_26421 = b("                return;\r\n            }\r\n\r\n            var key = action + \"@\" + workspace;\r\n");
    protected static final byte[] _jsp_26422 = b("            var permission = context[key];\r\n\r\n            if(permission == null) {\r\n");
    protected static final byte[] _jsp_26423 = b("                permission = context[key] = {\"workspace\": workspace, \"action\": action, \"includes\": []};\r\n");
    protected static final byte[] _jsp_26424 = b("            }\r\n\r\n            var includes = permission.includes;\r\n            includes[includes.length] = pattern;\r\n");
    protected static final byte[] _jsp_26425 = b("        });\r\n        return context;\r\n    };\r\n\r\n    var getWorkspaceList = function(context) {\r\n");
    protected static final byte[] _jsp_26426 = b("        var map = {};\r\n        var list = [];\r\n\r\n        for(var key in context) {\r\n");
    protected static final byte[] _jsp_26427 = b("            var permission = context[key];\r\n            var workspace = permission.workspace;\r\n");
    protected static final byte[] _jsp_26428 = b("            map[workspace] = workspace;\r\n        }\r\n\r\n        for(var name in map) {\r\n");
    protected static final byte[] _jsp_26429 = b("            list[list.length] = name;\r\n        }\r\n        return list;\r\n    };\r\n");
    protected static final byte[] _jsp_26430 = b("\r\n    var getContent = function() {\r\n        var userPermission = getUserPermission();\r\n");
    protected static final byte[] _jsp_26431 = b("        var workspaceList = getWorkspaceList(userPermission);\r\n\r\n        var b = [];\r\n");
    protected static final byte[] _jsp_26432 = b("        b[b.length] = \"grant read on localhost@@ {\\r\\n\";\r\n\r\n        for(var i = 0; i < workspaceList.length; i++) {\r\n");
    protected static final byte[] _jsp_26433 = b("            b[b.length] = \"    include \" + workspaceList[i] + \"\\r\\n\";\r\n        }\r\n");
    protected static final byte[] _jsp_26434 = b("        b[b.length] = \"}\\r\\n\\r\\n\";\r\n\r\n        for(var key in userPermission) {\r\n");
    protected static final byte[] _jsp_26435 = b("            var permission = userPermission[key];\r\n            var workspace = permission.workspace;\r\n");
    protected static final byte[] _jsp_26436 = b("            var action = permission.action;\r\n            var includes = permission.includes;\r\n");
    protected static final byte[] _jsp_26437 = b("            b[b.length] = \"grant \" + action + \" on localhost@\" + workspace + \" {\\r\\n\";\r\n");
    protected static final byte[] _jsp_26438 = b("\r\n            for(var i = 0; i < includes.length; i++) {\r\n                var pattern = jQuery.trim(includes[i]);\r\n");
    protected static final byte[] _jsp_26439 = b("\r\n                if(pattern.length < 1) {\r\n                    continue;\r\n                }\r\n");
    protected static final byte[] _jsp_26440 = b("\r\n                if(pattern.charAt(0) == \"!\") {\r\n                    b[b.length] = \"    exclude \" + pattern.substring(1) + \"\\r\\n\";\r\n");
    protected static final byte[] _jsp_26441 = b("                }\r\n                else {\r\n                    b[b.length] = \"    include \" + pattern + \"\\r\\n\";\r\n");
    protected static final byte[] _jsp_26442 = b("                }\r\n            }\r\n            b[b.length] = \"}\\r\\n\\r\\n\";\r\n        }\r\n");
    protected static final byte[] _jsp_26443 = b("        return b.join(\"\");\r\n    };\r\n\r\n    jQuery(\"input[name=submit]\").click(function(event) {\r\n");
    protected static final byte[] _jsp_26444 = b("        var userName = jQuery.trim(jQuery(\"input[name=userName]\").val());\r\n        var hostName = jQuery.trim(jQuery(\"#permission-table\").attr(\"hostName\"));\r\n");
    protected static final byte[] _jsp_26445 = b("        var content = getContent();\r\n\r\n        if(userName.length < 1) {\r\n            alert(\"userName 不能为空！\");\r\n");
    protected static final byte[] _jsp_26446 = b("            return;\r\n        }\r\n\r\n        if(hostName.length < 1) {\r\n            alert(\"hostName 不能为空！\");\r\n");
    protected static final byte[] _jsp_26447 = b("            return;\r\n        }\r\n\r\n        var params = [];\r\n        params[params.length] = \"userName=\" + encodeURIComponent(userName);\r\n");
    protected static final byte[] _jsp_26448 = b("        params[params.length] = \"content=\" + encodeURIComponent(content);\r\n\r\n        jQuery.ajax({\r\n");
    protected static final byte[] _jsp_26449 = b("            \"type\": \"post\",\r\n            \"url\": \"?action=admin.policy.file.save&host=\" + encodeURIComponent(hostName),\r\n");
    protected static final byte[] _jsp_26450 = b("            \"dataType\": \"json\",\r\n            \"data\": params.join(\"&\"),\r\n            \"error\": function() {\r\n");
    protected static final byte[] _jsp_26451 = b("                alert(\"系统错误，请稍后再试！\");\r\n            },\r\n            \"success\": function(response) {\r\n");
    protected static final byte[] _jsp_26452 = b("                if(response.status != 200) {\r\n                    alert(response.message);\r\n");
    protected static final byte[] _jsp_26453 = b("                    return;\r\n                }\r\n                alert(\"保存成功，请重新查询！\");\r\n");
    protected static final byte[] _jsp_26454 = b("            }\r\n        });\r\n    });\r\n\r\n    jQuery(\"input[name=test]\").click(function(event) {\r\n");
    protected static final byte[] _jsp_26455 = b("        var userName = jQuery.trim(jQuery(\"input[name=userName]\").val());\r\n        var hostName = jQuery.trim(jQuery(\"select[name=hostName]\").val());\r\n");
    protected static final byte[] _jsp_26456 = b("        var path = jQuery.trim(jQuery(\"input[name=path]\").val());\r\n\r\n        if(userName.length < 1) {\r\n");
    protected static final byte[] _jsp_26457 = b("            alert(\"userName 不能为空！\");\r\n            return;\r\n        }\r\n\r\n        if(hostName.length < 1) {\r\n");
    protected static final byte[] _jsp_26458 = b("            alert(\"hostName 不能为空！\");\r\n            return;\r\n        }\r\n\r\n        if(path.length < 1) {\r\n");
    protected static final byte[] _jsp_26459 = b("            alert(\"测试路径不能为空！\");\r\n            return;\r\n        }\r\n\r\n        var params = [];\r\n");
    protected static final byte[] _jsp_26460 = b("        params[params.length] = \"userName=\" + encodeURIComponent(userName);\r\n        params[params.length] = \"path=\" + encodeURIComponent(path);\r\n");
    protected static final byte[] _jsp_26461 = b("\r\n        jQuery.ajax({\r\n            \"type\": \"post\",\r\n            \"url\": \"?action=admin.policy.file.test&host=\" + encodeURIComponent(hostName),\r\n");
    protected static final byte[] _jsp_26462 = b("            \"dataType\": \"json\",\r\n            \"data\": params.join(\"&\"),\r\n            \"error\": function() {\r\n");
    protected static final byte[] _jsp_26463 = b("                alert(\"系统错误，请稍后再试！\");\r\n            },\r\n            \"success\": function(response) {\r\n");
    protected static final byte[] _jsp_26464 = b("                alert(response.value);\r\n            }\r\n        });\r\n    });\r\n\r\n    jQuery(\"input[name=edit-mode-btn]\").click(function() {\r\n");
    protected static final byte[] _jsp_26465 = b("        var src = jQuery(this);\r\n\r\n        if(src.attr(\"edit-mode\") == \"1\") {\r\n            jQuery(\"#permission-panel\").hide();\r\n");
    protected static final byte[] _jsp_26466 = b("            jQuery(\"#advance-panel\").show();\r\n        }\r\n        else {\r\n            src.attr(\"edit-mode\", \"0\");\r\n");
    protected static final byte[] _jsp_26467 = b("            jQuery(\"#permission-panel\").show();\r\n            jQuery(\"#advance-panel\").hide();\r\n");
    protected static final byte[] _jsp_26468 = b("        }\r\n    });\r\n\r\n    jQuery(\"input[name=advance-submit]\").click(function(event) {\r\n");
    protected static final byte[] _jsp_26469 = b("        var userName = jQuery.trim(jQuery(\"input[name=userName]\").val());\r\n        var hostName = jQuery.trim(jQuery(\"select[name=hostName]\").val());\r\n");
    protected static final byte[] _jsp_26470 = b("        var content = jQuery(\"textarea[name=content]\").val();\r\n\r\n        if(userName.length < 1) {\r\n");
    protected static final byte[] _jsp_26471 = b("            alert(\"userName 不能为空！\");\r\n            return;\r\n        }\r\n\r\n        if(hostName.length < 1) {\r\n");
    protected static final byte[] _jsp_26472 = b("            alert(\"hostName 不能为空！\");\r\n            return;\r\n        }\r\n\r\n        var params = [];\r\n");
    protected static final byte[] _jsp_26473 = b("        params[params.length] = \"userName=\" + encodeURIComponent(userName);\r\n        params[params.length] = \"content=\" + encodeURIComponent(content);\r\n");
    protected static final byte[] _jsp_26474 = b("\r\n        jQuery.ajax({\r\n            \"type\": \"post\",\r\n            \"url\": \"?action=admin.policy.file.save&host=\" + encodeURIComponent(hostName),\r\n");
    protected static final byte[] _jsp_26475 = b("            \"dataType\": \"json\",\r\n            \"data\": params.join(\"&\"),\r\n            \"error\": function() {\r\n");
    protected static final byte[] _jsp_26476 = b("                alert(\"系统错误，请稍后再试！\");\r\n            },\r\n            \"success\": function(response) {\r\n");
    protected static final byte[] _jsp_26477 = b("                if(response.status != 200) {\r\n                    alert(response.message);\r\n");
    protected static final byte[] _jsp_26478 = b("                    return;\r\n                }\r\n                alert(\"保存成功，请重新查询！\");\r\n");
    protected static final byte[] _jsp_26479 = b("            }\r\n        });\r\n    });\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n<body>\r\n<div class=\"menu-bar\">\r\n");
    protected static final byte[] _jsp_26480 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_26481 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_26482 = b("    <span class=\"seperator\"></span>\r\n</div>\r\n");
    protected static final byte[] _jsp_26484 = b("<div class=\"form\">\r\n    <div style=\"margin: 10px 0px; font-size: 13px;\">请输入用户名查询该用户拥有的文件权限:</div>\r\n");
    protected static final byte[] _jsp_26485 = b("    <div style=\"margin: 10px 0px;\">\r\n        <input name=\"userName\" type=\"text\" class=\"text w200\" title=\"用户名\" placeholder=\"user name\" value=\"\"/>\r\n");
    protected static final byte[] _jsp_26486 = b("        <select name=\"hostName\" type=\"text\" class=\"select w200\" title=\"主机\">\r\n        ");
    protected static final byte[] _jsp_26488 = b("            <option value=\"");
    protected static final byte[] _jsp_26490 = b("\">");
    protected static final byte[] _jsp_26492 = b("</option>\r\n        ");
    protected static final byte[] _jsp_26494 = b("        </select>\r\n        <input name=\"query\" type=\"button\" class=\"button\" value=\"查询\"/>\r\n");
    protected static final byte[] _jsp_26495 = b("        <input name=\"flush\" type=\"button\" class=\"button\" value=\"刷新缓存\"/>\r\n    </div>\r\n");
    protected static final byte[] _jsp_26496 = b("</div>\r\n<div id=\"permission-panel\" class=\"form\" style=\"display: none;\">\r\n    <div class=\"title\"><h4>操作说明</h4></div>\r\n");
    protected static final byte[] _jsp_26497 = b("    <ul class=\"tips\">\r\n        <li>\r\n            <div style=\"color: #ff0000;\">路径匹配必须以/或者!/开头，支持通配符，遵循ANT路径匹配规则;</div>\r\n");
    protected static final byte[] _jsp_26498 = b("<pre style=\"padding: 8px 0px; width: 80%; box-sizing: border-box; line-height: 20px; font-size: 14px;\">\r\n");
    protected static final byte[] _jsp_26499 = b("!    排除, 只能出现在开头;\r\n?    匹配任何单字符;\r\n*    匹配0或者任意数量的字符;\r\n**   匹配0或者更多的目录;\r\n</pre>\r\n");
    protected static final byte[] _jsp_26500 = b("        </li>\r\n    </ul>\r\n    <div style=\"margin: 10px 0px;\">\r\n        <table id=\"permission-table\" class=\"list\">\r\n");
    protected static final byte[] _jsp_26501 = b("            <tr class=\"head\">\r\n                <td class=\"w200\">工作空间</td>\r\n                <td class=\"w200\">操作权限</td>\r\n");
    protected static final byte[] _jsp_26502 = b("                <td class=\"w300\">路径匹配</td>\r\n                <td>操作</td>\r\n            </tr>\r\n");
    protected static final byte[] _jsp_26503 = b("        </table>\r\n        <div style=\"margin: 10px 0px 10px 210px;\">\r\n            <a id=\"add-btn\" class=\"add-row\" href=\"javascript:void(0)\">添加权限</a>\r\n");
    protected static final byte[] _jsp_26504 = b("        </div>\r\n    </div>\r\n    <!-- div style=\"margin: 10px 0px;\">\r\n        测试路径：<input name=\"path\" type=\"text\" class=\"text w400\" title=\"测试路径\" placeholder=\"\" value=\"\"/>\r\n");
    protected static final byte[] _jsp_26505 = b("        <input name=\"test\" type=\"button\" class=\"button\" value=\"测试\"/>\r\n    </div -->\r\n");
    protected static final byte[] _jsp_26506 = b("    <div style=\"margin: 10px 0px;\">\r\n        <input name=\"submit\" type=\"button\" class=\"button\" value=\"保存\"/>\r\n");
    protected static final byte[] _jsp_26507 = b("        <input name=\"edit-mode-btn\" type=\"button\" class=\"button\" edit-mode=\"1\" value=\"高级权限设置\"/>\r\n");
    protected static final byte[] _jsp_26508 = b("    </div>\r\n</div>\r\n<div id=\"advance-panel\" class=\"form\" style=\"display: none;\">\r\n");
    protected static final byte[] _jsp_26509 = b("        <div class=\"title\"><h4>操作说明</h4></div>\r\n    <ul class=\"tips\">\r\n        <li>\r\n");
    protected static final byte[] _jsp_26510 = b("            <div style=\"color: #ff0000;\">路径匹配必须以/开头，支持通配符，遵循ANT路径匹配规则;</div>\r\n<pre style=\"padding: 8px 0px; width: 80%; box-sizing: border-box; line-height: 20px; font-size: 14px;\">\r\n");
    protected static final byte[] _jsp_26511 = b("1. grant read on localhost, 此处只能且必须是localhost;\r\n2. 两个@表示用户能看到的工作空间;\r\n3. include表示包含某个目录或者文件;\r\n");
    protected static final byte[] _jsp_26512 = b("4. exclude表示排除某个目录或者文件;\r\n</pre>\r\n        </li>\r\n    </ul>\r\n    <div style=\"margin: 10px 0px;\">\r\n");
    protected static final byte[] _jsp_26513 = b("        <textarea name=\"content\" style=\"width: 800px; height: 200px; outline: none; resize: none; background-color: #000000; color: #999999;\">\r\n");
    protected static final byte[] _jsp_26514 = b("# 这只是一个示例, 请从外部编辑好之后粘贴到此处并保存\r\ngrant read on localhost@@ {\r\n    include finder.webapp\r\n");
    protected static final byte[] _jsp_26515 = b("    include server1.mp3\r\n}\r\n\r\ngrant read on localhost@finder.webapp {\r\n    include /**\r\n");
    protected static final byte[] _jsp_26516 = b("}\r\n\r\ngrant read on localhost@server1.mp3 {\r\n    include /**\r\n    exclude /test\r\n");
    protected static final byte[] _jsp_26517 = b("}\r\n</textarea>\r\n    </div>\r\n    <div style=\"margin: 10px 0px;\">\r\n        <input name=\"advance-submit\" type=\"button\" class=\"button\" value=\"保存\"/>\r\n");
    protected static final byte[] _jsp_26518 = b("        <input name=\"edit-mode-btn\" type=\"button\" class=\"button\" edit-mode=\"0\" value=\"一般权限设置\"/>\r\n");
    protected static final byte[] _jsp_26519 = b("    </div>\r\n</div>\r\n<div id=\"pageContext\" style=\"display: none;\" contextPath=\"");
    protected static final byte[] _jsp_26521 = b("\"></div>\r\n</body>\r\n</html>\r\n");

}
