/*
 * $RCSfile: UserListTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import java.util.List;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import com.skin.finder.config.App;
import com.skin.finder.acl.User;


/**
 * <p>Title: UserListTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class UserListTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final UserListTemplate instance = new UserListTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();


    @SuppressWarnings("unchecked")
    List<User> userList = (List<User>)(request.getAttribute("userList"));

        out.write(_jsp_96103, 0, _jsp_96103.length);
        out.write(_jsp_96104, 0, _jsp_96104.length);
        out.write(_jsp_96105, 0, _jsp_96105.length);
        out.write(_jsp_96106, 0, _jsp_96106.length);
        out.write(_jsp_96107, 0, _jsp_96107.length);
        this.write(out, (App.hash()));
        out.write(_jsp_96109, 0, _jsp_96109.length);
        this.write(out, (App.hash()));
        out.write(_jsp_96111, 0, _jsp_96111.length);
        out.write(_jsp_96112, 0, _jsp_96112.length);
        this.write(out, (App.hash()));
        out.write(_jsp_96114, 0, _jsp_96114.length);
        this.write(out, (App.hash()));
        out.write(_jsp_96116, 0, _jsp_96116.length);
        out.write(_jsp_96117, 0, _jsp_96117.length);
        out.write(_jsp_96118, 0, _jsp_96118.length);
        out.write(_jsp_96119, 0, _jsp_96119.length);
        out.write(_jsp_96120, 0, _jsp_96120.length);
        out.write(_jsp_96121, 0, _jsp_96121.length);
        out.write(_jsp_96122, 0, _jsp_96122.length);
        out.write(_jsp_96123, 0, _jsp_96123.length);
        out.write(_jsp_96124, 0, _jsp_96124.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_96126, 0, _jsp_96126.length);
        out.write(_jsp_96127, 0, _jsp_96127.length);
        out.write(_jsp_96128, 0, _jsp_96128.length);
        out.write(_jsp_96129, 0, _jsp_96129.length);
        out.write(_jsp_96130, 0, _jsp_96130.length);

            if(userList != null && userList.size() > 0) {
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

                for(User user : userList) {
        
        out.write(_jsp_96132, 0, _jsp_96132.length);
        this.write(out, (user.getUserName()));
        out.write(_jsp_96134, 0, _jsp_96134.length);
        this.write(out, (user.getUserName()));
        out.write(_jsp_96136, 0, _jsp_96136.length);
        this.write(out, (dateFormat.format(user.getCreateTime())));
        out.write(_jsp_96138, 0, _jsp_96138.length);
        this.write(out, (user.getUserName()));
        out.write(_jsp_96140, 0, _jsp_96140.length);
        this.write(out, (user.getUserName()));
        out.write(_jsp_96142, 0, _jsp_96142.length);

                }
            }
        
        out.write(_jsp_96144, 0, _jsp_96144.length);

        if(userList == null || userList.size() < 1) {
    
        out.write(_jsp_96146, 0, _jsp_96146.length);

        }
        else {
    
        out.write(_jsp_96148, 0, _jsp_96148.length);
        this.write(out, request.getAttribute("pageNum"));
        out.write(_jsp_96150, 0, _jsp_96150.length);
        this.write(out, request.getAttribute("pageSize"));
        out.write(_jsp_96152, 0, _jsp_96152.length);
        this.write(out, request.getAttribute("userCount"));
        out.write(_jsp_96154, 0, _jsp_96154.length);

        }
    
        out.write(_jsp_96156, 0, _jsp_96156.length);

        out.flush();
    }

    protected static final byte[] _jsp_96103 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_96104 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_96105 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_96106 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_96107 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css&v=");
    protected static final byte[] _jsp_96109 = b("\"/>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/pagebar.css&v=");
    protected static final byte[] _jsp_96111 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_96112 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js&v=");
    protected static final byte[] _jsp_96114 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/scrollpage.js&v=");
    protected static final byte[] _jsp_96116 = b("\"></script>\r\n<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    jQuery(\"table tr td a.delete\").click(function() {\r\n");
    protected static final byte[] _jsp_96117 = b("        var userName = this.getAttribute(\"userName\");\r\n\r\n        if(!window.confirm(\"删除之后不可恢复，确定要删除 [\" + userName + \"] 吗？\")) {\r\n");
    protected static final byte[] _jsp_96118 = b("            return;\r\n        }\r\n\r\n        jQuery.ajax({\r\n            \"type\": \"get\",\r\n");
    protected static final byte[] _jsp_96119 = b("            \"url\": \"?action=admin.user.delete&userName=\" + encodeURIComponent(userName),\r\n");
    protected static final byte[] _jsp_96120 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_96121 = b("            },\r\n            \"success\": function(response) {\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_96122 = b("                    alert(response.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_96123 = b("                window.location.reload();\r\n            }\r\n        });\r\n    });\r\n");
    protected static final byte[] _jsp_96124 = b("});\r\n//-->\r\n</script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_96126 = b("\">\r\n<div class=\"menu-bar\">\r\n    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_96127 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_96128 = b("    <span class=\"seperator\"></span>\r\n</div>\r\n<div class=\"form\">\r\n    <div class=\"title\"><h4>用户管理</h4></div>\r\n");
    protected static final byte[] _jsp_96129 = b("    <table id=\"host-table\" class=\"list\">\r\n        <tr class=\"head\">\r\n            <td>用户名</td>\r\n");
    protected static final byte[] _jsp_96130 = b("            <td>注册时间</td>\r\n            <td>操作</td>\r\n        </tr>\r\n        ");
    protected static final byte[] _jsp_96132 = b("        <tr userName=\"");
    protected static final byte[] _jsp_96134 = b("\">\r\n            <td class=\"w200\">");
    protected static final byte[] _jsp_96136 = b("</td>\r\n            <td class=\"w400\">");
    protected static final byte[] _jsp_96138 = b("</td>\r\n            <td>\r\n                <a class=\"btn\" href=\"?action=admin.user.edit&userName=");
    protected static final byte[] _jsp_96140 = b("\">修改</a>\r\n                <a class=\"btn delete\" href=\"javascript:void(0)\" userName=\"");
    protected static final byte[] _jsp_96142 = b("\">刪除</a>\r\n            </td>\r\n        </tr>\r\n        ");
    protected static final byte[] _jsp_96144 = b("    </table>\r\n    ");
    protected static final byte[] _jsp_96146 = b("    <div style=\"margin: 10px 0px;\">无数据。</div>\r\n    ");
    protected static final byte[] _jsp_96148 = b("    <div class=\"pagebar\">\r\n        <div name=\"scrollpage\" class=\"scrollpage\" theme=\"2\" pageNum=\"");
    protected static final byte[] _jsp_96150 = b("\" pageSize=\"");
    protected static final byte[] _jsp_96152 = b("\" count=\"");
    protected static final byte[] _jsp_96154 = b("\" href=\"?action=admin.user.list&pageNum=%s\"></div>\r\n    </div>\r\n    ");
    protected static final byte[] _jsp_96156 = b("</div>\r\n<div id=\"pageContext\" style=\"display: none;\"></div>\r\n</body>\r\n</html>\r\n");

}
