/*
 * $RCSfile: UserHostEditTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;


/**
 * <p>Title: UserHostEditTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class UserHostEditTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final UserHostEditTemplate instance = new UserHostEditTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_18194, 0, _jsp_18194.length);
        out.write(_jsp_18195, 0, _jsp_18195.length);
        out.write(_jsp_18196, 0, _jsp_18196.length);
        out.write(_jsp_18197, 0, _jsp_18197.length);
        out.write(_jsp_18198, 0, _jsp_18198.length);
        this.write(out, (App.hash()));
        out.write(_jsp_18200, 0, _jsp_18200.length);
        out.write(_jsp_18201, 0, _jsp_18201.length);
        this.write(out, (App.hash()));
        out.write(_jsp_18203, 0, _jsp_18203.length);
        out.write(_jsp_18204, 0, _jsp_18204.length);
        out.write(_jsp_18205, 0, _jsp_18205.length);
        out.write(_jsp_18206, 0, _jsp_18206.length);
        out.write(_jsp_18207, 0, _jsp_18207.length);
        out.write(_jsp_18208, 0, _jsp_18208.length);
        out.write(_jsp_18209, 0, _jsp_18209.length);
        out.write(_jsp_18210, 0, _jsp_18210.length);
        out.write(_jsp_18211, 0, _jsp_18211.length);
        out.write(_jsp_18212, 0, _jsp_18212.length);
        out.write(_jsp_18213, 0, _jsp_18213.length);
        out.write(_jsp_18214, 0, _jsp_18214.length);
        out.write(_jsp_18215, 0, _jsp_18215.length);
        out.write(_jsp_18216, 0, _jsp_18216.length);
        out.write(_jsp_18217, 0, _jsp_18217.length);

    String[] hosts = (String[])(request.getAttribute("hosts"));

    if(hosts == null) {
        hosts = new String[0];
    }

        out.write(_jsp_18219, 0, _jsp_18219.length);
        out.write(_jsp_18220, 0, _jsp_18220.length);
        out.write(_jsp_18221, 0, _jsp_18221.length);
        out.write(_jsp_18222, 0, _jsp_18222.length);
        out.write(_jsp_18223, 0, _jsp_18223.length);
        out.write(_jsp_18224, 0, _jsp_18224.length);

                    for(String hostName : hosts) {
                
        out.write(_jsp_18226, 0, _jsp_18226.length);
        this.write(out, (hostName));
        out.write(_jsp_18228, 0, _jsp_18228.length);
        this.write(out, (hostName));
        out.write(_jsp_18230, 0, _jsp_18230.length);

                    }
                
        out.write(_jsp_18232, 0, _jsp_18232.length);
        out.write(_jsp_18233, 0, _jsp_18233.length);
        out.write(_jsp_18234, 0, _jsp_18234.length);
        out.write(_jsp_18235, 0, _jsp_18235.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_18237, 0, _jsp_18237.length);

        out.flush();
    }

    protected static final byte[] _jsp_18194 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_18195 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_18196 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_18197 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_18198 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css&v=");
    protected static final byte[] _jsp_18200 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_18201 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js&v=");
    protected static final byte[] _jsp_18203 = b("\"></script>\r\n<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    jQuery(\"button[name=submit]\").click(function() {\r\n");
    protected static final byte[] _jsp_18204 = b("        var userName = jQuery.trim(jQuery(\"input[name=userName]\").val());\r\n        var hostName = jQuery.trim(jQuery(\"select[name=hostName]\").val());\r\n");
    protected static final byte[] _jsp_18205 = b("\r\n        if(userName.length < 1) {\r\n            alert(\"请输入用户名！\");\r\n            return;\r\n");
    protected static final byte[] _jsp_18206 = b("        }\r\n\r\n        if(hostName.length < 1) {\r\n            alert(\"请选择主机！\");\r\n            return;\r\n");
    protected static final byte[] _jsp_18207 = b("        }\r\n\r\n        var params = [];\r\n        params[params.length] = \"userName=\" + encodeURIComponent(userName);\r\n");
    protected static final byte[] _jsp_18208 = b("        params[params.length] = \"hostName=\" + encodeURIComponent(hostName);\r\n\r\n        jQuery.ajax({\r\n");
    protected static final byte[] _jsp_18209 = b("            \"type\": \"get\",\r\n            \"url\": \"?action=admin.policy.host.add&host=\" + encodeURIComponent(hostName),\r\n");
    protected static final byte[] _jsp_18210 = b("            \"dataType\": \"json\",\r\n            \"data\": params.join(\"&\"),\r\n            \"error\": function() {\r\n");
    protected static final byte[] _jsp_18211 = b("                alert(\"系统错误，请稍后再试！\");\r\n            },\r\n            \"success\": function(response) {\r\n");
    protected static final byte[] _jsp_18212 = b("                if(response.status != 200) {\r\n                    alert(response.message);\r\n");
    protected static final byte[] _jsp_18213 = b("                    return;\r\n                }\r\n                alert(\"添加成功，您可以继续添加其他主机或者返回到上一个页面！\");\r\n");
    protected static final byte[] _jsp_18214 = b("            }\r\n        });\r\n    });\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n<body>\r\n<div class=\"menu-bar\">\r\n");
    protected static final byte[] _jsp_18215 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_18216 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_18217 = b("    <span class=\"seperator\"></span>\r\n</div>\r\n");
    protected static final byte[] _jsp_18219 = b("<div class=\"form\">\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">User Name：</div>\r\n");
    protected static final byte[] _jsp_18220 = b("        <div class=\"form-c300\">\r\n            <div class=\"form-field\">\r\n                <input name=\"userName\" type=\"text\" class=\"text w200\" placeholder=\"User Name\" value=\"\"/>\r\n");
    protected static final byte[] _jsp_18221 = b("            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">User Name .</div>\r\n");
    protected static final byte[] _jsp_18222 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">Host Name</div>\r\n");
    protected static final byte[] _jsp_18223 = b("        <div class=\"form-c300\">\r\n            <div class=\"form-field\">\r\n                <select name=\"hostName\" type=\"text\" class=\"select w200\" title=\"主机\">\r\n");
    protected static final byte[] _jsp_18224 = b("                    <option value=\"\">请选择主机</option>\r\n                ");
    protected static final byte[] _jsp_18226 = b("                    <option value=\"");
    protected static final byte[] _jsp_18228 = b("\">");
    protected static final byte[] _jsp_18230 = b("</option>\r\n                ");
    protected static final byte[] _jsp_18232 = b("                </select>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n");
    protected static final byte[] _jsp_18233 = b("            <div class=\"form-comment\">Host Name .</div>\r\n        </div>\r\n    </div>\r\n");
    protected static final byte[] _jsp_18234 = b("\r\n    <div class=\"button\">\r\n        <button name=\"submit\" class=\"button ensure\">保 存</button>\r\n");
    protected static final byte[] _jsp_18235 = b("    </div>\r\n</div>\r\n<div id=\"pageContext\" style=\"display: none;\" contextPath=\"");
    protected static final byte[] _jsp_18237 = b("\"></div>\r\n</body>\r\n</html>\r\n");

}
