/*
 * $RCSfile: WorkspacesTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import java.util.List;
import com.skin.finder.config.App;
import com.skin.finder.cluster.Host;
import com.skin.finder.cluster.Workspace;


/**
 * <p>Title: WorkspacesTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class WorkspacesTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final WorkspacesTemplate instance = new WorkspacesTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();


    Host host = (Host)(request.getAttribute("host"));

    if(host == null) {
        host = new Host();
    }

    List<Workspace> workspaces = host.getWorkspaces();

        out.write(_jsp_80994, 0, _jsp_80994.length);
        out.write(_jsp_80995, 0, _jsp_80995.length);
        out.write(_jsp_80996, 0, _jsp_80996.length);
        out.write(_jsp_80997, 0, _jsp_80997.length);
        out.write(_jsp_80998, 0, _jsp_80998.length);
        this.write(out, (App.hash()));
        out.write(_jsp_81000, 0, _jsp_81000.length);
        out.write(_jsp_81001, 0, _jsp_81001.length);
        this.write(out, (App.hash()));
        out.write(_jsp_81003, 0, _jsp_81003.length);
        out.write(_jsp_81004, 0, _jsp_81004.length);
        out.write(_jsp_81005, 0, _jsp_81005.length);
        out.write(_jsp_81006, 0, _jsp_81006.length);
        out.write(_jsp_81007, 0, _jsp_81007.length);
        out.write(_jsp_81008, 0, _jsp_81008.length);
        out.write(_jsp_81009, 0, _jsp_81009.length);
        out.write(_jsp_81010, 0, _jsp_81010.length);
        out.write(_jsp_81011, 0, _jsp_81011.length);
        out.write(_jsp_81012, 0, _jsp_81012.length);
        out.write(_jsp_81013, 0, _jsp_81013.length);
        out.write(_jsp_81014, 0, _jsp_81014.length);
        out.write(_jsp_81015, 0, _jsp_81015.length);
        out.write(_jsp_81016, 0, _jsp_81016.length);
        out.write(_jsp_81017, 0, _jsp_81017.length);
        out.write(_jsp_81018, 0, _jsp_81018.length);
        out.write(_jsp_81019, 0, _jsp_81019.length);
        out.write(_jsp_81020, 0, _jsp_81020.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_81022, 0, _jsp_81022.length);
        this.write(out, (host.getName()));
        out.write(_jsp_81024, 0, _jsp_81024.length);
        out.write(_jsp_81025, 0, _jsp_81025.length);
        out.write(_jsp_81026, 0, _jsp_81026.length);
        out.write(_jsp_81027, 0, _jsp_81027.length);
        out.write(_jsp_81028, 0, _jsp_81028.length);
        out.write(_jsp_81029, 0, _jsp_81029.length);
        out.write(_jsp_81030, 0, _jsp_81030.length);

        for(Workspace workspace : workspaces) {
    
        out.write(_jsp_81032, 0, _jsp_81032.length);
        this.write(out, (workspace.getName()));
        out.write(_jsp_81034, 0, _jsp_81034.length);
        this.write(out, (workspace.getOrderNum()));
        out.write(_jsp_81036, 0, _jsp_81036.length);
        this.write(out, (workspace.getName()));
        out.write(_jsp_81038, 0, _jsp_81038.length);
        this.write(out, (workspace.getDisplayName()));
        out.write(_jsp_81040, 0, _jsp_81040.length);
        this.write(out, (workspace.getWork()));
        out.write(_jsp_81042, 0, _jsp_81042.length);
        this.write(out, (workspace.getCharset()));
        out.write(_jsp_81044, 0, _jsp_81044.length);
        this.write(out, (workspace.getReadonly()));
        out.write(_jsp_81046, 0, _jsp_81046.length);
        this.write(out, (workspace.getReadonly()));
        out.write(_jsp_81048, 0, _jsp_81048.length);
        this.write(out, (workspace.getName()));
        out.write(_jsp_81050, 0, _jsp_81050.length);
        this.write(out, (workspace.getName()));
        out.write(_jsp_81052, 0, _jsp_81052.length);

        }
    
        out.write(_jsp_81054, 0, _jsp_81054.length);

        out.flush();
    }

    protected static final byte[] _jsp_80994 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_80995 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_80996 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_80997 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_80998 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css&v=");
    protected static final byte[] _jsp_81000 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_81001 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js&v=");
    protected static final byte[] _jsp_81003 = b("\"></script>\r\n<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    jQuery(\"#create\").click(function() {\r\n");
    protected static final byte[] _jsp_81004 = b("        var hostName = document.body.getAttribute(\"hostName\");\r\n        window.location.href = \"?action=admin.workspace.edit&hostName=\" + encodeURIComponent(hostName);\r\n");
    protected static final byte[] _jsp_81005 = b("    });\r\n\r\n    jQuery(\"table tr td a.update\").click(function() {\r\n        var hostName = document.body.getAttribute(\"hostName\");\r\n");
    protected static final byte[] _jsp_81006 = b("        var workspaceName = this.getAttribute(\"workspaceName\");\r\n        window.location.href = \"?action=admin.workspace.edit&hostName=\" + encodeURIComponent(hostName) + \"&workspaceName=\" + encodeURIComponent(workspaceName);\r\n");
    protected static final byte[] _jsp_81007 = b("    });\r\n\r\n    jQuery(\"table tr td a.delete\").click(function() {\r\n        var hostName = document.body.getAttribute(\"hostName\");\r\n");
    protected static final byte[] _jsp_81008 = b("        var workspaceName = this.getAttribute(\"workspaceName\");\r\n\r\n        if(!window.confirm(\"确定要删除 [\" + workspaceName + \"] 吗？\")) {\r\n");
    protected static final byte[] _jsp_81009 = b("            return;\r\n        }\r\n\r\n        jQuery.ajax({\r\n            \"type\": \"get\",\r\n");
    protected static final byte[] _jsp_81010 = b("            \"url\": \"?action=admin.workspace.delete&hostName=\" + encodeURIComponent(hostName) + \"&workspaceName=\" + encodeURIComponent(workspaceName),\r\n");
    protected static final byte[] _jsp_81011 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_81012 = b("            },\r\n            \"success\": function(response) {\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_81013 = b("                    alert(response.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_81014 = b("                window.location.reload();\r\n            }\r\n        });\r\n    });\r\n");
    protected static final byte[] _jsp_81015 = b("\r\n    jQuery(\"table tr td input[name=orderNum]\").change(function() {\r\n        var hostName = document.body.getAttribute(\"hostName\");\r\n");
    protected static final byte[] _jsp_81016 = b("        var workspaceName = this.getAttribute(\"workspaceName\");\r\n        var value = StringUtil.trim(this.value);\r\n");
    protected static final byte[] _jsp_81017 = b("\r\n        if(value.length < 1) {\r\n            return;\r\n        }\r\n\r\n        var url = \"?action=admin.workspace.setValue&hostName=\" + encodeURIComponent(hostName)\r\n");
    protected static final byte[] _jsp_81018 = b("            + \"&workspaceName=\" + encodeURIComponent(workspaceName)\r\n            + \"&orderNum=\" + encodeURIComponent(value)\r\n");
    protected static final byte[] _jsp_81019 = b("\r\n        jQuery.ajax({\"type\": \"get\", \"url\": url, \"dataType\": \"json\"});\r\n    });\r\n");
    protected static final byte[] _jsp_81020 = b("});\r\n//-->\r\n</script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_81022 = b("\" hostName=\"");
    protected static final byte[] _jsp_81024 = b("\">\r\n<div class=\"menu-bar\">\r\n    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_81025 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_81026 = b("    <span class=\"seperator\"></span>\r\n    <a id=\"create\" class=\"button\" href=\"javascript:void(0)\"><span class=\"add\"></span>新建</a>\r\n");
    protected static final byte[] _jsp_81027 = b("</div>\r\n<table id=\"workspace-table\" class=\"list\">\r\n    <tr class=\"head\">\r\n        <td class=\"w060\">Order</td>\r\n");
    protected static final byte[] _jsp_81028 = b("        <td class=\"w200\">Name</td>\r\n        <td class=\"w200\">Display Name</td>\r\n");
    protected static final byte[] _jsp_81029 = b("        <td class=\"w240\">Work</td>\r\n        <td class=\"w100\">Charset</td>\r\n        <td class=\"w100\">Readonly</td>\r\n");
    protected static final byte[] _jsp_81030 = b("        <td>操作</td>\r\n    </tr>\r\n    ");
    protected static final byte[] _jsp_81032 = b("    <tr>\r\n        <td class=\"center\"><input name=\"orderNum\" type=\"text\" class=\"text1 w060\" workspaceName=\"");
    protected static final byte[] _jsp_81034 = b("\" value=\"");
    protected static final byte[] _jsp_81036 = b("\"/></td>\r\n        <td>");
    protected static final byte[] _jsp_81038 = b("</td>\r\n        <td>");
    protected static final byte[] _jsp_81040 = b("</td>\r\n        <td><input type=\"text\" class=\"text2\" readonly=\"true\" value=\"");
    protected static final byte[] _jsp_81042 = b("\"/></td>\r\n        <td>");
    protected static final byte[] _jsp_81044 = b("</td>\r\n        <td><span class=\"");
    protected static final byte[] _jsp_81046 = b("\">");
    protected static final byte[] _jsp_81048 = b("</span></td>\r\n        <td>\r\n            <a class=\"btn update\" href=\"javascript:void(0)\" workspaceName=\"");
    protected static final byte[] _jsp_81050 = b("\">编 辑</a>\r\n            <a class=\"btn delete\" href=\"javascript:void(0)\" workspaceName=\"");
    protected static final byte[] _jsp_81052 = b("\">刪 除</a>\r\n        </td>\r\n    </tr>\r\n    ");
    protected static final byte[] _jsp_81054 = b("</table>\r\n</body>\r\n</html>\r\n");

}
