/*
 * $RCSfile: BlankTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;



/**
 * <p>Title: BlankTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class BlankTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final BlankTemplate instance = new BlankTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_99851, 0, _jsp_99851.length);
        out.write(_jsp_99852, 0, _jsp_99852.length);
        out.write(_jsp_99853, 0, _jsp_99853.length);
        out.write(_jsp_99854, 0, _jsp_99854.length);
        out.write(_jsp_99855, 0, _jsp_99855.length);
        out.write(_jsp_99856, 0, _jsp_99856.length);

        out.flush();
    }

    protected static final byte[] _jsp_99851 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_99852 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_99853 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_99854 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_99855 = b("</head>\r\n<body>\r\n<div style=\"margin: 100px auto 0px auto; width: 400px; text-align: center; color: #c0c0c0;\">Welcome to Finder.</div>\r\n");
    protected static final byte[] _jsp_99856 = b("</body>\r\n</html>");

}
