/*
 * $RCSfile: DisplayTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;
import com.skin.finder.config.ConfigFactory;


/**
 * <p>Title: DisplayTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class DisplayTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final DisplayTemplate instance = new DisplayTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_52445, 0, _jsp_52445.length);
        out.write(_jsp_52446, 0, _jsp_52446.length);
        out.write(_jsp_52447, 0, _jsp_52447.length);
        out.write(_jsp_52448, 0, _jsp_52448.length);
        out.write(_jsp_52449, 0, _jsp_52449.length);
        this.write(out, (App.hash()));
        out.write(_jsp_52451, 0, _jsp_52451.length);
        out.write(_jsp_52452, 0, _jsp_52452.length);
        out.write(_jsp_52453, 0, _jsp_52453.length);
        this.write(out, (App.hash()));
        out.write(_jsp_52455, 0, _jsp_52455.length);
        out.write(_jsp_52456, 0, _jsp_52456.length);
        out.write(_jsp_52457, 0, _jsp_52457.length);
        out.write(_jsp_52458, 0, _jsp_52458.length);
        out.write(_jsp_52459, 0, _jsp_52459.length);
        out.write(_jsp_52460, 0, _jsp_52460.length);
        out.write(_jsp_52461, 0, _jsp_52461.length);
        out.write(_jsp_52462, 0, _jsp_52462.length);
this.write(out, ConfigFactory.getAccessCode(), false);
        out.write(_jsp_52464, 0, _jsp_52464.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_52466, 0, _jsp_52466.length);
        this.write(out, request.getAttribute("host"));
        out.write(_jsp_52468, 0, _jsp_52468.length);
        this.write(out, request.getAttribute("workspace"));
        out.write(_jsp_52470, 0, _jsp_52470.length);
        this.write(out, request.getAttribute("path"));
        out.write(_jsp_52472, 0, _jsp_52472.length);

        out.flush();
    }

    protected static final byte[] _jsp_52445 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_52446 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_52447 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_52448 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_52449 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/finder.css&v=");
    protected static final byte[] _jsp_52451 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_52452 = b("<script type=\"text/javascript\" src=\"?action=res&path=/sh/shCore.js\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/sh/shAutoloader.js\"></script>\r\n");
    protected static final byte[] _jsp_52453 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/display.js&v=");
    protected static final byte[] _jsp_52455 = b("\"></script>\r\n</head>\r\n<body style=\"overflow: hidden;\">\r\n<div class=\"addr-bar\" style=\"min-width: 988px;\" contextmenu=\"false\">\r\n");
    protected static final byte[] _jsp_52456 = b("    <div class=\"b2\">\r\n        <span class=\"label\">theme:</span>\r\n        <select id=\"uiThemeOption\" style=\"width: 150px;\" selected-value=\"Default\"></select>\r\n");
    protected static final byte[] _jsp_52457 = b("        <span class=\"label\">type:</span>\r\n        <select id=\"uiTypeOption\" style=\"width: 150px;\" selected-value=\"\"></select>\r\n");
    protected static final byte[] _jsp_52458 = b("        <span class=\"label\">encoding:</span>\r\n        <select id=\"uiCharsetOption\" style=\"width: 150px;\" selected-value=\"utf-8\"></select>\r\n");
    protected static final byte[] _jsp_52459 = b("    </div>\r\n</div>\r\n<div id=\"info-view\" class=\"info-view\"></div>\r\n<div id=\"data-view\" class=\"data-view\"></div>\r\n");
    protected static final byte[] _jsp_52460 = b("<div id=\"content\" style=\"height: 400px; display: none;\"><pre style=\"height: 100%;\" class=\"brush: bash;\"></pre></div>\r\n");
    protected static final byte[] _jsp_52461 = b("<div id=\"loading\" class=\"loading-mask\" style=\"display: block;\" contextmenu=\"false\"><div class=\"loading\"><img src=\"?action=res&path=/finder/images/loading.gif\"/></div></div>\r\n");
    protected static final byte[] _jsp_52462 = b("<div style=\"display: none;\">");
    protected static final byte[] _jsp_52464 = b("</div>\r\n<div id=\"pageContext\" style=\"display: none;\"\r\n    data-context-path=\"");
    protected static final byte[] _jsp_52466 = b("\"\r\n    data-host=\"");
    protected static final byte[] _jsp_52468 = b("\"\r\n    data-workspace=\"");
    protected static final byte[] _jsp_52470 = b("\"\r\n    data-path=\"");
    protected static final byte[] _jsp_52472 = b("\"></div>\r\n</html>\r\n");

}
