/*
 * $RCSfile: EditorTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;


/**
 * <p>Title: EditorTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class EditorTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final EditorTemplate instance = new EditorTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_15924, 0, _jsp_15924.length);
        out.write(_jsp_15925, 0, _jsp_15925.length);
        this.write(out, (App.hash()));
        out.write(_jsp_15927, 0, _jsp_15927.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_15929, 0, _jsp_15929.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_15931, 0, _jsp_15931.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_15933, 0, _jsp_15933.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_15935, 0, _jsp_15935.length);
        out.write(_jsp_15936, 0, _jsp_15936.length);
        this.write(out, (App.hash()));
        out.write(_jsp_15938, 0, _jsp_15938.length);
        this.write(out, request.getAttribute("host"));
        out.write(_jsp_15940, 0, _jsp_15940.length);
        this.write(out, request.getAttribute("workspace"));
        out.write(_jsp_15942, 0, _jsp_15942.length);
        this.write(out, request.getAttribute("path"));
        out.write(_jsp_15944, 0, _jsp_15944.length);
        out.write(_jsp_15945, 0, _jsp_15945.length);

        out.flush();
    }

    protected static final byte[] _jsp_15924 = b("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"UTF-8\">\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n");
    protected static final byte[] _jsp_15925 = b("<title>ACE Editor - Powered by FinderWeb</title>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/editor.css&v=");
    protected static final byte[] _jsp_15927 = b("\"/>\n<script type=\"text/javascript\" src=\"");
    protected static final byte[] _jsp_15929 = b("/lib/ace-min/ace.js\"></script>\n<script type=\"text/javascript\" src=\"");
    protected static final byte[] _jsp_15931 = b("/lib/ace-min/ext-modelist.js\"></script>\n<script type=\"text/javascript\" src=\"");
    protected static final byte[] _jsp_15933 = b("/lib/ace-min/ext-statusbar.js\"></script>\n<script type=\"text/javascript\" src=\"");
    protected static final byte[] _jsp_15935 = b("/lib/ace-min/ext-language_tools.js\"></script>\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\n");
    protected static final byte[] _jsp_15936 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/editor.js&v=");
    protected static final byte[] _jsp_15938 = b("\"\"></script>\n</head>\n<body>\n<div id=\"editor\" data-host=\"");
    protected static final byte[] _jsp_15940 = b("\" data-workspace=\"");
    protected static final byte[] _jsp_15942 = b("\" data-path=\"");
    protected static final byte[] _jsp_15944 = b("\"></div>\n<div id=\"status-bar\" class=\"status-bar\">\n    <div id=\"status-inf\" class=\"status-inf\"></div>\n");
    protected static final byte[] _jsp_15945 = b("</div>\n</body>\n</html>\n");

}
