/*
 * $RCSfile: ErrorTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;



/**
 * <p>Title: ErrorTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class ErrorTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final ErrorTemplate instance = new ErrorTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_69342, 0, _jsp_69342.length);
        out.write(_jsp_69343, 0, _jsp_69343.length);
        out.write(_jsp_69344, 0, _jsp_69344.length);
        out.write(_jsp_69345, 0, _jsp_69345.length);
        out.write(_jsp_69346, 0, _jsp_69346.length);
        this.write(out, request.getAttribute("title"));
        out.write(_jsp_69348, 0, _jsp_69348.length);
        this.write(out, request.getAttribute("message"));
        out.write(_jsp_69350, 0, _jsp_69350.length);

        out.flush();
    }

    protected static final byte[] _jsp_69342 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_69343 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_69344 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_69345 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_69346 = b("</head>\r\n<body>\r\n<div style=\"margin: 0px auto; width: 400px;\">\r\n    <h1>");
    protected static final byte[] _jsp_69348 = b("</h1>\r\n    <p>");
    protected static final byte[] _jsp_69350 = b("</p>\r\n</div>\r\n</body>\r\n</html>\r\n");

}
