/*
 * $RCSfile: GrepTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;


/**
 * <p>Title: GrepTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class GrepTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final GrepTemplate instance = new GrepTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_17473, 0, _jsp_17473.length);
        out.write(_jsp_17474, 0, _jsp_17474.length);
        out.write(_jsp_17475, 0, _jsp_17475.length);
        this.write(out, request.getAttribute("fileName"));
        out.write(_jsp_17477, 0, _jsp_17477.length);
        out.write(_jsp_17478, 0, _jsp_17478.length);
        this.write(out, (App.hash()));
        out.write(_jsp_17480, 0, _jsp_17480.length);
        out.write(_jsp_17481, 0, _jsp_17481.length);
        this.write(out, (App.hash()));
        out.write(_jsp_17483, 0, _jsp_17483.length);
        this.write(out, (App.hash()));
        out.write(_jsp_17485, 0, _jsp_17485.length);
        this.write(out, (App.hash()));
        out.write(_jsp_17487, 0, _jsp_17487.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_17489, 0, _jsp_17489.length);
        this.write(out, request.getAttribute("host"));
        out.write(_jsp_17491, 0, _jsp_17491.length);
        this.write(out, request.getAttribute("workspace"));
        out.write(_jsp_17493, 0, _jsp_17493.length);
        this.write(out, request.getAttribute("parent"));
        out.write(_jsp_17495, 0, _jsp_17495.length);
        this.write(out, request.getAttribute("path"));
        out.write(_jsp_17497, 0, _jsp_17497.length);
        this.write(out, request.getAttribute("charset"));
        out.write(_jsp_17499, 0, _jsp_17499.length);
        out.write(_jsp_17500, 0, _jsp_17500.length);
        out.write(_jsp_17501, 0, _jsp_17501.length);
        out.write(_jsp_17502, 0, _jsp_17502.length);
        out.write(_jsp_17503, 0, _jsp_17503.length);
        this.write(out, request.getAttribute("host"));
        out.write(_jsp_17505, 0, _jsp_17505.length);
        this.write(out, request.getAttribute("workspace"));
        out.write(_jsp_17507, 0, _jsp_17507.length);
        this.write(out, request.getAttribute("path"));
        out.write(_jsp_17509, 0, _jsp_17509.length);
        this.write(out, request.getAttribute("fileName"));
        out.write(_jsp_17511, 0, _jsp_17511.length);
        this.write(out, request.getAttribute("charset"));
        out.write(_jsp_17513, 0, _jsp_17513.length);
        out.write(_jsp_17514, 0, _jsp_17514.length);
        out.write(_jsp_17515, 0, _jsp_17515.length);
        out.write(_jsp_17516, 0, _jsp_17516.length);
        out.write(_jsp_17517, 0, _jsp_17517.length);
        out.write(_jsp_17518, 0, _jsp_17518.length);
        out.write(_jsp_17519, 0, _jsp_17519.length);
        out.write(_jsp_17520, 0, _jsp_17520.length);
        out.write(_jsp_17521, 0, _jsp_17521.length);
        out.write(_jsp_17522, 0, _jsp_17522.length);
        out.write(_jsp_17523, 0, _jsp_17523.length);
        out.write(_jsp_17524, 0, _jsp_17524.length);
        out.write(_jsp_17525, 0, _jsp_17525.length);

        out.flush();
    }

    protected static final byte[] _jsp_17473 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_17474 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_17475 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>grep - ");
    protected static final byte[] _jsp_17477 = b(" - Powered by FinderWeb</title>\r\n<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_17478 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/less.css&v=");
    protected static final byte[] _jsp_17480 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_17481 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/config.js&v=");
    protected static final byte[] _jsp_17483 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/charset.js&v=");
    protected static final byte[] _jsp_17485 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/grep.js&v=");
    protected static final byte[] _jsp_17487 = b("\"></script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_17489 = b("\" host=\"");
    protected static final byte[] _jsp_17491 = b("\" workspace=\"");
    protected static final byte[] _jsp_17493 = b("\" parent=\"");
    protected static final byte[] _jsp_17495 = b("\" path=\"");
    protected static final byte[] _jsp_17497 = b("\" charset=\"");
    protected static final byte[] _jsp_17499 = b("\">\r\n<div id=\"less-container\" class=\"less-container\" contenteditable=\"true\" spellcheck=\"false\"></div>\r\n");
    protected static final byte[] _jsp_17500 = b("<div id=\"less-progress-bar\" class=\"less-progress-bar\">\r\n    <div class=\"progress\">\r\n");
    protected static final byte[] _jsp_17501 = b("        <div class=\"slider\">\r\n            <div class=\"pace\"></div>\r\n            <a class=\"dot\" href=\"#\"></a>\r\n");
    protected static final byte[] _jsp_17502 = b("            <div class=\"mask\"></div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div id=\"less-status-bar\" class=\"less-status-bar\">\r\n");
    protected static final byte[] _jsp_17503 = b("    <div style=\"height: 18px;\">\r\n        <span class=\"file\"><input id=\"less-file\" type=\"text\" class=\"text w240\" readonly=\"true\" title=\"");
    protected static final byte[] _jsp_17505 = b("@");
    protected static final byte[] _jsp_17507 = b("/");
    protected static final byte[] _jsp_17509 = b("\" value=\"");
    protected static final byte[] _jsp_17511 = b("\"/></span>\r\n        <span class=\"charset\"><select name=\"charset\" selected-value=\"");
    protected static final byte[] _jsp_17513 = b("\"></select></span>\r\n        <span class=\"info\"><input id=\"less-info\" type=\"text\" class=\"text w160\" value=\"0 B\"/></span>\r\n");
    protected static final byte[] _jsp_17514 = b("        <span class=\"status\"><input id=\"less-status\" type=\"text\" class=\"text w160\" readonly=\"true\" value=\"READY\"/></span>\r\n");
    protected static final byte[] _jsp_17515 = b("    </div>\r\n</div>\r\n<div id=\"less-tooltip\" class=\"less-tooltip\">50%</div>\r\n<div id=\"find-panel\" class=\" dialog\" style=\"top: 100px;\">\r\n");
    protected static final byte[] _jsp_17516 = b("    <div class=\"find-panel\">\r\n        <div>\r\n            查找内容: <input id=\"grep-keyword\" type=\"text\" class=\"grep-keyword\" value=\"\" placeholder=\"正则示例: /finder/.*\\.html\"/>\r\n");
    protected static final byte[] _jsp_17517 = b("            <input id=\"grep-ensure\" type=\"button\" class=\"grep-search\" value=\"查找\"/>\r\n");
    protected static final byte[] _jsp_17518 = b("        </div>\r\n        <div style=\"clear: both; padding-top: 12px; height: 20px;\">\r\n");
    protected static final byte[] _jsp_17519 = b("            <span style=\"float: left; width: 10px; display: inline-block;\"><input id=\"grep-regexp\" type=\"checkbox\" title=\"正则表达式\"/></span>\r\n");
    protected static final byte[] _jsp_17520 = b("            <span style=\"float: left; margin-left: 6px; margin-top: -1px; width: 100px; display: inline-block;\">正则表达式</span>\r\n");
    protected static final byte[] _jsp_17521 = b("        </div>\r\n        <div style=\"clear: both; margin-top: 10px;\">\r\n            <p><span style=\"color: #ff0000;\">提示：</span>快捷键(Ctrl + B)，再次按下可关闭。</p>\r\n");
    protected static final byte[] _jsp_17522 = b("            <p><span style=\"color: #ff0000;\">参考：</span><a href=\"http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#sum\" target=\"_blank\">正则表达式参考</a></p>\r\n");
    protected static final byte[] _jsp_17523 = b("        </div>\r\n        <div style=\"margin-top: 20px; text-align: center;\">\r\n            <input id=\"grep-close\" type=\"button\" class=\"grep-button\" value=\"关闭\"/>\r\n");
    protected static final byte[] _jsp_17524 = b("        </div>\r\n    </div>\r\n</div>\r\n<!-- http://www.finderweb.net -->\r\n</body>\r\n");
    protected static final byte[] _jsp_17525 = b("</html>\r\n");

}
