/*
 * $RCSfile: HelpTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;



/**
 * <p>Title: HelpTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class HelpTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final HelpTemplate instance = new HelpTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_18084, 0, _jsp_18084.length);
        out.write(_jsp_18085, 0, _jsp_18085.length);
        out.write(_jsp_18086, 0, _jsp_18086.length);
        out.write(_jsp_18087, 0, _jsp_18087.length);
        out.write(_jsp_18088, 0, _jsp_18088.length);
        out.write(_jsp_18089, 0, _jsp_18089.length);
        out.write(_jsp_18090, 0, _jsp_18090.length);
        out.write(_jsp_18091, 0, _jsp_18091.length);
        out.write(_jsp_18092, 0, _jsp_18092.length);
        out.write(_jsp_18093, 0, _jsp_18093.length);
        out.write(_jsp_18094, 0, _jsp_18094.length);
        out.write(_jsp_18095, 0, _jsp_18095.length);
        this.write(out, request.getAttribute("requestURI"));
        out.write(_jsp_18097, 0, _jsp_18097.length);
        out.write(_jsp_18098, 0, _jsp_18098.length);
        out.write(_jsp_18099, 0, _jsp_18099.length);
        out.write(_jsp_18100, 0, _jsp_18100.length);
        out.write(_jsp_18101, 0, _jsp_18101.length);
        out.write(_jsp_18102, 0, _jsp_18102.length);
        out.write(_jsp_18103, 0, _jsp_18103.length);
        out.write(_jsp_18104, 0, _jsp_18104.length);
        out.write(_jsp_18105, 0, _jsp_18105.length);
        out.write(_jsp_18106, 0, _jsp_18106.length);
        out.write(_jsp_18107, 0, _jsp_18107.length);
        out.write(_jsp_18108, 0, _jsp_18108.length);
        out.write(_jsp_18109, 0, _jsp_18109.length);
        out.write(_jsp_18110, 0, _jsp_18110.length);
        out.write(_jsp_18111, 0, _jsp_18111.length);
        out.write(_jsp_18112, 0, _jsp_18112.length);
        out.write(_jsp_18113, 0, _jsp_18113.length);
        out.write(_jsp_18114, 0, _jsp_18114.length);
        out.write(_jsp_18115, 0, _jsp_18115.length);
        out.write(_jsp_18116, 0, _jsp_18116.length);
        out.write(_jsp_18117, 0, _jsp_18117.length);
        out.write(_jsp_18118, 0, _jsp_18118.length);
        out.write(_jsp_18119, 0, _jsp_18119.length);
        out.write(_jsp_18120, 0, _jsp_18120.length);
        out.write(_jsp_18121, 0, _jsp_18121.length);
        out.write(_jsp_18122, 0, _jsp_18122.length);
        out.write(_jsp_18123, 0, _jsp_18123.length);
        out.write(_jsp_18124, 0, _jsp_18124.length);
        out.write(_jsp_18125, 0, _jsp_18125.length);
        out.write(_jsp_18126, 0, _jsp_18126.length);
        out.write(_jsp_18127, 0, _jsp_18127.length);
        out.write(_jsp_18128, 0, _jsp_18128.length);
        out.write(_jsp_18129, 0, _jsp_18129.length);
        out.write(_jsp_18130, 0, _jsp_18130.length);
        out.write(_jsp_18131, 0, _jsp_18131.length);
        out.write(_jsp_18132, 0, _jsp_18132.length);
        out.write(_jsp_18133, 0, _jsp_18133.length);
        out.write(_jsp_18134, 0, _jsp_18134.length);
        out.write(_jsp_18135, 0, _jsp_18135.length);
        out.write(_jsp_18136, 0, _jsp_18136.length);
        out.write(_jsp_18137, 0, _jsp_18137.length);

        out.flush();
    }

    protected static final byte[] _jsp_18084 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_18085 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_18086 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_18087 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_18088 = b("<style type=\"text/css\">\r\n.red{color: #ff0000;}\r\ndiv.wrap{margin: 0px auto; width: 980px;}\r\n");
    protected static final byte[] _jsp_18089 = b("ul.list{list-style-type: disc;}\r\nul.list li{line-height: 24px; font-size: 13px;}\r\n");
    protected static final byte[] _jsp_18090 = b("table tr.head td{font-size: 14px;}\r\ntable tr td{padding-left: 4px; height: 24px; font-size: 13px;}\r\n");
    protected static final byte[] _jsp_18091 = b("</style>\r\n</head>\r\n<body>\r\n<div class=\"wrap\">\r\n    <div class=\"finder\">\r\n        <div class=\"menu-bar\" style=\"padding-top: 4px;\">\r\n");
    protected static final byte[] _jsp_18092 = b("            <div style=\"float: left; width: 80px;\">\r\n                <a class=\"button disabled\" href=\"javascript:void(0)\"><span class=\"back-disabled\"></span></a>\r\n");
    protected static final byte[] _jsp_18093 = b("                <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\" title=\"刷新\"><span class=\"refresh\"></span></a>\r\n");
    protected static final byte[] _jsp_18094 = b("            </div>\r\n            <div style=\"float: left; height: 28px; position: relative;\"></div>\r\n");
    protected static final byte[] _jsp_18095 = b("            <div style=\"float: right; width: 40px;\">\r\n                <a class=\"button\" href=\"");
    protected static final byte[] _jsp_18097 = b("?action=finder.help\" title=\"帮助\"><span class=\"help\"></span></a>\r\n            </div>\r\n");
    protected static final byte[] _jsp_18098 = b("        </div>\r\n    </div>\r\n    <div class=\"finder\">\r\n        <h1>WebFinder简介</h1>\r\n");
    protected static final byte[] _jsp_18099 = b("        <p>WebFinder是一个高性能的Web版分布式文件管理工具，它具有体积小，易部署，功能强大等特点。</p>\r\n        <p>主页：<a href=\"http://www.finderweb.net\" target=\"_blank\">http://www.finderweb.net</a></p>\r\n");
    protected static final byte[] _jsp_18100 = b("        <p>安装部署文档：<a href=\"http://www.finderweb.net/docs/index.html\" target=\"_blank\">http://www.finderweb.net/docs/index.html</a></p>\r\n");
    protected static final byte[] _jsp_18101 = b("        <ul class=\"list\">\r\n            <li>(<span class=\"red\">程序员专用</span>) 支持集群部署，允许你同时管理多台机器上的文件或者查看不同机器上的日志；</li>\r\n");
    protected static final byte[] _jsp_18102 = b("            <li>(<span class=\"red\">程序员专用</span>) grep支持，类似linux系统的grep命令，支持任意大小的文件，支持随时查看文件的任意位置，像播放器一样点击进度条的任意位置；</li>\r\n");
    protected static final byte[] _jsp_18103 = b("            <li>(<span class=\"red\">程序员专用</span>) less支持，类似linux系统的less命令，支持任意大小的文件，支持随时查看文件的任意位置，像播放器一样点击进度条的任意位置；</li>\r\n");
    protected static final byte[] _jsp_18104 = b("            <li>(<span class=\"red\">程序员专用</span>) tail支持，类似linux系统的tail命令，支持任意大小的文件；</li>\r\n");
    protected static final byte[] _jsp_18105 = b("            <li><span class=\"red\">支持细粒度的权限控制，能满足不同的权限需求；IT运维或者公司内部资料分享，允许控制文件可见和文件的各种操作。</span></li>\r\n");
    protected static final byte[] _jsp_18106 = b("            <li>支持全键盘操作，几乎所有操作均有对应的快捷键支持；</li>\r\n            <li>支持右键菜单，文件的常规操作都可以通过右键菜单完成；</li>\r\n");
    protected static final byte[] _jsp_18107 = b("            <li>支持文件重命名，点击选中文件，然后按F2即可重命名文件；</li>\r\n            <li>支持大文件上传，超大文件会自动分段上传，默认设置每次上传5M；</li>\r\n");
    protected static final byte[] _jsp_18108 = b("            <li>支持文件拖拽上传，可同时拖拽多个文件上传；</li>\r\n            <li>支持截图上传，截图之后按Ctrl + Shift + V；</li>\r\n");
    protected static final byte[] _jsp_18109 = b("            <li>支持音频和视频播放（需支持H5的浏览器）；</li>\r\n            <li>体积小，只有不到3M，目前一般基于SSH的web应用，基本都在几十兆左右。WebFinder除了日志组件无任何第三方依赖（日志组件也不需要单独安装）;</li>\r\n");
    protected static final byte[] _jsp_18110 = b("            <li>无数据库设计，免去部署数据库的麻烦，所有数据存储都存在本地文件系统，集群环境下分布式存储。</li>\r\n            <li>易于部署，直接扔到Tomcat里即可；</li>\r\n");
    protected static final byte[] _jsp_18111 = b("            <li>基于web的文件管理，几乎所有的操作系统和服务器的防火墙默认都对HTTP开放，而FTP大多需要专门开通；不需要用户安装专门的客户端软件，使用浏览器即可。</li>\r\n");
    protected static final byte[] _jsp_18112 = b("            <li>对网络环境无任何要求，不需要做任何特殊设置。出于安全考虑，几乎所有的服务器都限制单个HTTP请求体的大小，且默认值很小，一般在2M左右，并且限制连接时间。WebFinder不需要专门设置即可上传或者下载超大的文件，WebFinder所有的功能都使用短连接完成以避免服务器超时限制。对于大文件采用分片上传，一方面可以避免服务器的限制，另一方面在网络环境不好的情况下提高上传的成功率，因为大文件长时间连接一旦网络断掉就需要全部重传，WebFinder采用分片的方式，每次只上传一段数据，如果失败自动重新上传这一段，并且针对每一段都自动重试3次。</li>\r\n");
    protected static final byte[] _jsp_18113 = b("        </ul>\r\n    </div>\r\n\r\n    <div class=\"finder\">\r\n        <h1>使用技巧</h1>\r\n        <ul class=\"list\">\r\n");
    protected static final byte[] _jsp_18114 = b("            <li>文件列表页面 - 双击文件名可以打开文件。</li>\r\n            <li>文件列表页面 - 按住Ctrl键点击tail或者less可以在新窗口打开less和tail。</li>\r\n");
    protected static final byte[] _jsp_18115 = b("            <li>文件列表页面 - 按住Ctrl键点击刷新可在新窗口打开文件列表页。</li>\r\n            <li>音频播放的同时可以继续其他操作，包括切换不同的文件夹。</li>\r\n");
    protected static final byte[] _jsp_18116 = b("            <li>地址栏的suggest列表支持键盘上下键滚动。</li>\r\n        </ul>\r\n    </div>\r\n\r\n    <div class=\"finder\">\r\n");
    protected static final byte[] _jsp_18117 = b("        <h1>剪切板</h1>\r\n        <p>WebFinder中有两种剪切板，一种是操作系统的剪切板，由于浏览器安全限制，WebFinder无法直接访问操作系统的剪切板，只能间接访问，当用户在Finder的界面上使用CTRL + V的时候，Finder可以访问到系统剪切板中的截图并上传。Finder无法访问剪切板中的文件。</p>\r\n");
    protected static final byte[] _jsp_18118 = b("        <p>第二种剪切板是Finder自己的剪切板，用户在界面上选择多个文件拷贝或者剪切的时候，WebFinder将需要拷贝的文件信息放到自己的剪切板中，在用户使用Finder自己的右键菜单上点击粘贴的时候WebFinder从自己的剪切板中读取文件信息完成拷贝或者粘贴。</p>\r\n");
    protected static final byte[] _jsp_18119 = b("        <p>所以CTRL + V只能上传操作系统剪切板中的截图。</p>\r\n    </div>\r\n\r\n    <div class=\"finder\">\r\n");
    protected static final byte[] _jsp_18120 = b("        <h1>快捷键</h1>\r\n        <table>\r\n            <tr class=\"head\">\r\n                <td style=\"width: 480px; height: 30px; background-color: #efefef;\">操作</td>\r\n");
    protected static final byte[] _jsp_18121 = b("                <td style=\"width: 300px; height: 30px; background-color: #efefef;\">快捷键</td>\r\n");
    protected static final byte[] _jsp_18122 = b("            </tr>\r\n            <tr>\r\n                <td>重命名</td>\r\n                <td>F2</td>\r\n");
    protected static final byte[] _jsp_18123 = b("            </tr>\r\n            <tr>\r\n                <td>向上滚动</td>\r\n                <td>UP</td>\r\n");
    protected static final byte[] _jsp_18124 = b("            </tr>\r\n            <tr>\r\n                <td>向下滚动</td>\r\n                <td>DOWN</td>\r\n");
    protected static final byte[] _jsp_18125 = b("            </tr>\r\n            <tr>\r\n                <td>向左滚动</td>\r\n                <td>LEFT</td>\r\n");
    protected static final byte[] _jsp_18126 = b("            </tr>\r\n            <tr>\r\n                <td>向右滚动</td>\r\n                <td>RIGHT</td>\r\n");
    protected static final byte[] _jsp_18127 = b("            </tr>\r\n            <tr>\r\n                <td>全选</td>\r\n                <td>CTRL + A</td>\r\n");
    protected static final byte[] _jsp_18128 = b("            </tr>\r\n            <tr>\r\n                <td>剪切(WebFinder中的文件)</td>\r\n");
    protected static final byte[] _jsp_18129 = b("                <td>CTRL + X</td>\r\n            </tr>\r\n            <tr>\r\n                <td>拷贝(WebFinder中的文件)</td>\r\n");
    protected static final byte[] _jsp_18130 = b("                <td>CTRL + C</td>\r\n            </tr>\r\n            <tr>\r\n                <td>粘贴截图</td>\r\n");
    protected static final byte[] _jsp_18131 = b("                <td>CTRL + V</td>\r\n            </tr>\r\n            <tr>\r\n                <td>多选</td>\r\n");
    protected static final byte[] _jsp_18132 = b("                <td>CTRL + CLICK</td>\r\n            </tr>\r\n            <tr>\r\n                <td>多选</td>\r\n");
    protected static final byte[] _jsp_18133 = b("                <td>ALT + CLICK</td>\r\n            </tr>\r\n            <tr>\r\n                <td>多选</td>\r\n");
    protected static final byte[] _jsp_18134 = b("                <td>CTRL + [UP|DOWN|LEFT|RIGHT]</td>\r\n            </tr>\r\n            <tr>\r\n");
    protected static final byte[] _jsp_18135 = b("                <td>删除选中文件</td>\r\n                <td>DELETE</td>\r\n            </tr>\r\n");
    protected static final byte[] _jsp_18136 = b("        </table>\r\n    </div>\r\n</div>\r\n<div style=\"height: 200px;\"></div>\r\n</body>\r\n");
    protected static final byte[] _jsp_18137 = b("</html>\r\n");

}
