/*
 * $RCSfile: LangTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;


/**
 * <p>Title: LangTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class LangTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final LangTemplate instance = new LangTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_76128, 0, _jsp_76128.length);
        out.write(_jsp_76129, 0, _jsp_76129.length);
        out.write(_jsp_76130, 0, _jsp_76130.length);
        out.write(_jsp_76131, 0, _jsp_76131.length);
        out.write(_jsp_76132, 0, _jsp_76132.length);
        this.write(out, (App.hash()));
        out.write(_jsp_76134, 0, _jsp_76134.length);
        out.write(_jsp_76135, 0, _jsp_76135.length);
        this.write(out, (App.hash()));
        out.write(_jsp_76137, 0, _jsp_76137.length);
        this.write(out, (App.hash()));
        out.write(_jsp_76139, 0, _jsp_76139.length);
        this.write(out, (App.hash()));
        out.write(_jsp_76141, 0, _jsp_76141.length);
        out.write(_jsp_76142, 0, _jsp_76142.length);
        out.write(_jsp_76143, 0, _jsp_76143.length);
        out.write(_jsp_76144, 0, _jsp_76144.length);
        out.write(_jsp_76145, 0, _jsp_76145.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_76147, 0, _jsp_76147.length);
        this.write(out, request.getAttribute("workspace"));
        out.write(_jsp_76149, 0, _jsp_76149.length);
        out.write(_jsp_76150, 0, _jsp_76150.length);
        out.write(_jsp_76151, 0, _jsp_76151.length);
        out.write(_jsp_76152, 0, _jsp_76152.length);
        out.write(_jsp_76153, 0, _jsp_76153.length);
        out.write(_jsp_76154, 0, _jsp_76154.length);
        out.write(_jsp_76155, 0, _jsp_76155.length);
        out.write(_jsp_76156, 0, _jsp_76156.length);
        out.write(_jsp_76157, 0, _jsp_76157.length);

        out.flush();
    }

    protected static final byte[] _jsp_76128 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_76129 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_76130 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Setting - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_76131 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_76132 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/form.css&v=");
    protected static final byte[] _jsp_76134 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_76135 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/charset.js&v=");
    protected static final byte[] _jsp_76137 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/colorpicker.js&v=");
    protected static final byte[] _jsp_76139 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/config.js&v=");
    protected static final byte[] _jsp_76141 = b("\"></script>\r\n<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    var theme = Finder.getCookie(\"finder_lang\");\r\n");
    protected static final byte[] _jsp_76142 = b("    jQuery(\"select[name=lang]\").val(theme);\r\n});\r\n\r\njQuery(function() {\r\n    jQuery(\"#ensure-btn\").click(function() {\r\n");
    protected static final byte[] _jsp_76143 = b("        var lang = jQuery(\"select[name=lang]\").val();\r\n        Finder.setCookie({\"name\": \"finder_lang\", \"value\": lang, \"expires\": 365 * 24 * 60 * 60});\r\n");
    protected static final byte[] _jsp_76144 = b("        alert(\"Save successfully, please reload！\");\r\n    });\r\n});\r\n//-->\r\n</script>\r\n");
    protected static final byte[] _jsp_76145 = b("</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_76147 = b("\" workspace=\"");
    protected static final byte[] _jsp_76149 = b("\">\r\n<div id=\"finder-panel\" class=\"form\">\r\n    <div class=\"title\"><h4>Language</h4></div>\r\n");
    protected static final byte[] _jsp_76150 = b("    <div class=\"form-row\">\r\n        <div class=\"form-label\">Language:</div>\r\n        <div class=\"form-c300\">\r\n");
    protected static final byte[] _jsp_76151 = b("            <div class=\"form-field\">\r\n                <select name=\"lang\">\r\n                    <option value=\"\">Auto</option>\r\n");
    protected static final byte[] _jsp_76152 = b("                    <option value=\"en\">English</option>\r\n                    <option value=\"zh_cn\">简体中文</option>\r\n");
    protected static final byte[] _jsp_76153 = b("                    <option value=\"zh_tw\">繁体中文</option>\r\n                    <option value=\"ja\">日本語</option>\r\n");
    protected static final byte[] _jsp_76154 = b("                </select>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n");
    protected static final byte[] _jsp_76155 = b("            <div class=\"form-comment\">Language.</div>\r\n        </div>\r\n    </div>\r\n");
    protected static final byte[] _jsp_76156 = b("    <div class=\"button\">\r\n        <button id=\"ensure-btn\" class=\"button ensure\">Ok</button>\r\n");
    protected static final byte[] _jsp_76157 = b("    </div>\r\n</div>\r\n</body>\r\n</html>\r\n");

}
