/*
 * $RCSfile: LessTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;


/**
 * <p>Title: LessTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class LessTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final LessTemplate instance = new LessTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_25743, 0, _jsp_25743.length);
        out.write(_jsp_25744, 0, _jsp_25744.length);
        out.write(_jsp_25745, 0, _jsp_25745.length);
        this.write(out, request.getAttribute("fileName"));
        out.write(_jsp_25747, 0, _jsp_25747.length);
        out.write(_jsp_25748, 0, _jsp_25748.length);
        this.write(out, (App.hash()));
        out.write(_jsp_25750, 0, _jsp_25750.length);
        out.write(_jsp_25751, 0, _jsp_25751.length);
        this.write(out, (App.hash()));
        out.write(_jsp_25753, 0, _jsp_25753.length);
        this.write(out, (App.hash()));
        out.write(_jsp_25755, 0, _jsp_25755.length);
        this.write(out, (App.hash()));
        out.write(_jsp_25757, 0, _jsp_25757.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_25759, 0, _jsp_25759.length);
        this.write(out, request.getAttribute("host"));
        out.write(_jsp_25761, 0, _jsp_25761.length);
        this.write(out, request.getAttribute("workspace"));
        out.write(_jsp_25763, 0, _jsp_25763.length);
        this.write(out, request.getAttribute("parent"));
        out.write(_jsp_25765, 0, _jsp_25765.length);
        this.write(out, request.getAttribute("path"));
        out.write(_jsp_25767, 0, _jsp_25767.length);
        this.write(out, request.getAttribute("charset"));
        out.write(_jsp_25769, 0, _jsp_25769.length);
        out.write(_jsp_25770, 0, _jsp_25770.length);
        out.write(_jsp_25771, 0, _jsp_25771.length);
        out.write(_jsp_25772, 0, _jsp_25772.length);
        out.write(_jsp_25773, 0, _jsp_25773.length);
        this.write(out, request.getAttribute("host"));
        out.write(_jsp_25775, 0, _jsp_25775.length);
        this.write(out, request.getAttribute("workspace"));
        out.write(_jsp_25777, 0, _jsp_25777.length);
        this.write(out, request.getAttribute("path"));
        out.write(_jsp_25779, 0, _jsp_25779.length);
        this.write(out, request.getAttribute("fileName"));
        out.write(_jsp_25781, 0, _jsp_25781.length);
        this.write(out, request.getAttribute("charset"));
        out.write(_jsp_25783, 0, _jsp_25783.length);
        out.write(_jsp_25784, 0, _jsp_25784.length);
        out.write(_jsp_25785, 0, _jsp_25785.length);
        out.write(_jsp_25786, 0, _jsp_25786.length);

        out.flush();
    }

    protected static final byte[] _jsp_25743 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_25744 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_25745 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>less - ");
    protected static final byte[] _jsp_25747 = b(" - Powered by FinderWeb</title>\r\n<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_25748 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/less.css&v=");
    protected static final byte[] _jsp_25750 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_25751 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/config.js&v=");
    protected static final byte[] _jsp_25753 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/charset.js&v=");
    protected static final byte[] _jsp_25755 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/less.js&v=");
    protected static final byte[] _jsp_25757 = b("\"></script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_25759 = b("\" host=\"");
    protected static final byte[] _jsp_25761 = b("\" workspace=\"");
    protected static final byte[] _jsp_25763 = b("\" parent=\"");
    protected static final byte[] _jsp_25765 = b("\" path=\"");
    protected static final byte[] _jsp_25767 = b("\" charset=\"");
    protected static final byte[] _jsp_25769 = b("\">\r\n<div id=\"less-container\" class=\"less-container\" contenteditable=\"true\" spellcheck=\"false\"></div>\r\n");
    protected static final byte[] _jsp_25770 = b("<div id=\"less-progress-bar\" class=\"less-progress-bar\">\r\n    <div class=\"progress\">\r\n");
    protected static final byte[] _jsp_25771 = b("        <div class=\"slider\">\r\n            <div class=\"pace\"></div>\r\n            <a class=\"dot\" href=\"#\"></a>\r\n");
    protected static final byte[] _jsp_25772 = b("            <div class=\"mask\"></div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div id=\"less-status-bar\" class=\"less-status-bar\">\r\n");
    protected static final byte[] _jsp_25773 = b("    <div style=\"height: 18px;\">\r\n        <span class=\"file\"><input id=\"less-file\" type=\"text\" class=\"text w240\" readonly=\"true\" title=\"");
    protected static final byte[] _jsp_25775 = b("@");
    protected static final byte[] _jsp_25777 = b("/");
    protected static final byte[] _jsp_25779 = b("\" value=\"");
    protected static final byte[] _jsp_25781 = b("\"/></span>\r\n        <span class=\"charset\"><select name=\"charset\" selected-value=\"");
    protected static final byte[] _jsp_25783 = b("\"></select></span>\r\n        <span class=\"info\"><input id=\"less-info\" type=\"text\" class=\"text w160\" value=\"0 B\"/></span>\r\n");
    protected static final byte[] _jsp_25784 = b("        <span class=\"status\"><input id=\"less-status\" type=\"text\" class=\"text w160\" readonly=\"true\" value=\"READY\"/></span>\r\n");
    protected static final byte[] _jsp_25785 = b("    </div>\r\n</div>\r\n<div id=\"less-tooltip\" class=\"less-tooltip\">50%</div>\r\n<!-- http://www.finderweb.net -->\r\n");
    protected static final byte[] _jsp_25786 = b("</body>\r\n</html>\r\n");

}
