/*
 * $RCSfile: PlayTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;


/**
 * <p>Title: PlayTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class PlayTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final PlayTemplate instance = new PlayTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_80011, 0, _jsp_80011.length);
        out.write(_jsp_80012, 0, _jsp_80012.length);
        out.write(_jsp_80013, 0, _jsp_80013.length);
        this.write(out, request.getAttribute("path"));
        out.write(_jsp_80015, 0, _jsp_80015.length);
        out.write(_jsp_80016, 0, _jsp_80016.length);
        this.write(out, (App.hash()));
        out.write(_jsp_80018, 0, _jsp_80018.length);
        out.write(_jsp_80019, 0, _jsp_80019.length);
        this.write(out, (App.hash()));
        out.write(_jsp_80021, 0, _jsp_80021.length);
        this.write(out, (App.hash()));
        out.write(_jsp_80023, 0, _jsp_80023.length);
        out.write(_jsp_80024, 0, _jsp_80024.length);
        out.write(_jsp_80025, 0, _jsp_80025.length);
        out.write(_jsp_80026, 0, _jsp_80026.length);
        out.write(_jsp_80027, 0, _jsp_80027.length);
        out.write(_jsp_80028, 0, _jsp_80028.length);
        out.write(_jsp_80029, 0, _jsp_80029.length);
        out.write(_jsp_80030, 0, _jsp_80030.length);
        out.write(_jsp_80031, 0, _jsp_80031.length);
        out.write(_jsp_80032, 0, _jsp_80032.length);
        out.write(_jsp_80033, 0, _jsp_80033.length);
        out.write(_jsp_80034, 0, _jsp_80034.length);
        out.write(_jsp_80035, 0, _jsp_80035.length);
        out.write(_jsp_80036, 0, _jsp_80036.length);
        out.write(_jsp_80037, 0, _jsp_80037.length);
        out.write(_jsp_80038, 0, _jsp_80038.length);
        out.write(_jsp_80039, 0, _jsp_80039.length);
        out.write(_jsp_80040, 0, _jsp_80040.length);
        out.write(_jsp_80041, 0, _jsp_80041.length);
        out.write(_jsp_80042, 0, _jsp_80042.length);
        out.write(_jsp_80043, 0, _jsp_80043.length);
        out.write(_jsp_80044, 0, _jsp_80044.length);
        out.write(_jsp_80045, 0, _jsp_80045.length);
        out.write(_jsp_80046, 0, _jsp_80046.length);
        out.write(_jsp_80047, 0, _jsp_80047.length);
        out.write(_jsp_80048, 0, _jsp_80048.length);
        out.write(_jsp_80049, 0, _jsp_80049.length);
        this.write(out, request.getAttribute("loacalIp"));
        out.write(_jsp_80051, 0, _jsp_80051.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_80053, 0, _jsp_80053.length);
        this.write(out, request.getAttribute("host"));
        out.write(_jsp_80055, 0, _jsp_80055.length);
        this.write(out, request.getAttribute("workspace"));
        out.write(_jsp_80057, 0, _jsp_80057.length);
        this.write(out, request.getAttribute("work"));
        out.write(_jsp_80059, 0, _jsp_80059.length);
        this.write(out, request.getAttribute("path"));
        out.write(_jsp_80061, 0, _jsp_80061.length);
        out.write(_jsp_80062, 0, _jsp_80062.length);

        out.flush();
    }

    protected static final byte[] _jsp_80011 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_80012 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_80013 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>");
    protected static final byte[] _jsp_80015 = b(" - Powered by FinderWeb</title>\r\n<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_80016 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/media/css/media.css&v=");
    protected static final byte[] _jsp_80018 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_80019 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/widget.js&v=");
    protected static final byte[] _jsp_80021 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/media/index.js&v=");
    protected static final byte[] _jsp_80023 = b("\"></script>\r\n<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    jQuery(document.body).css(\"margin\", \"0px\");\r\n");
    protected static final byte[] _jsp_80024 = b("    jQuery(document.body).css(\"padding\", \"0px\");\r\n    jQuery(document.body).css(\"backgroundColor\", \"#333333\");\r\n");
    protected static final byte[] _jsp_80025 = b("    jQuery(document.body).css(\"overflow\", \"hidden\");\r\n});\r\n\r\njQuery(function() {\r\n");
    protected static final byte[] _jsp_80026 = b("    var playList = new PlayList();\r\n    var host = document.body.getAttribute(\"host\");\r\n");
    protected static final byte[] _jsp_80027 = b("    var workspace = document.body.getAttribute(\"workspace\");\r\n    var path = document.body.getAttribute(\"path\");\r\n");
    protected static final byte[] _jsp_80028 = b("    var requestURI = window.location.pathname;\r\n\r\n    var prefix = requestURI + \"?action=finder.download&host=\" + encodeURIComponent(host) + \"&workspace=\" + encodeURIComponent(workspace);\r\n");
    protected static final byte[] _jsp_80029 = b("    playList.add({\"title\": \"test\", \"url\": prefix + \"&path=\" + encodeURIComponent(path)});\r\n");
    protected static final byte[] _jsp_80030 = b("\r\n    var videoPlayer = new VideoPlayer({\"container\": \"finder-videodialog\"});\r\n    var container = videoPlayer.getContainer();\r\n");
    protected static final byte[] _jsp_80031 = b("    var parent = jQuery(container);\r\n    parent.css(\"top\", \"0px\");\r\n    parent.css(\"left\", \"0px\");\r\n");
    protected static final byte[] _jsp_80032 = b("    parent.css(\"width\", \"100%\");\r\n    parent.css(\"height\", \"auto\");\r\n    parent.css(\"position\", \"static\");\r\n");
    protected static final byte[] _jsp_80033 = b("    parent.css(\"border\", \"none\");\r\n    parent.find(\"div.title\").remove();\r\n\r\n    jQuery(window).resize(function() {\r\n");
    protected static final byte[] _jsp_80034 = b("        var height = (document.documentElement.clientHeight - 100);\r\n        parent.find(\"video\").attr(\"width\", \"100%\");\r\n");
    protected static final byte[] _jsp_80035 = b("        parent.find(\"video\").attr(\"height\", height + \"px;\");\r\n    });\r\n    jQuery(window).resize();\r\n");
    protected static final byte[] _jsp_80036 = b("\r\n    videoPlayer.setPlayList(playList);\r\n    videoPlayer.play(0);\r\n    parent.show();\r\n");
    protected static final byte[] _jsp_80037 = b("});\r\n\r\njQuery(function() {\r\n    /**\r\n     * jQuery-1.7.2版本的paste事件获取不到clipboardData\r\n");
    protected static final byte[] _jsp_80038 = b("     * 该事件尽可能放到jQuery事件之前\r\n     * bug: IE11不触发paste事件\r\n     */\r\n    EventUtil.addEventListener(document, \"paste\", function(event) {\r\n");
    protected static final byte[] _jsp_80039 = b("        return DialogManager.dispatch(\"paste\", event);\r\n    });\r\n\r\n    jQuery(document).click(function(event) {\r\n");
    protected static final byte[] _jsp_80040 = b("        return DialogManager.dispatch(\"click\", event);\r\n    });\r\n\r\n    jQuery(document).dblclick(function(event) {\r\n");
    protected static final byte[] _jsp_80041 = b("        return DialogManager.dispatch(\"dblclick\", event);\r\n    });\r\n\r\n    /**\r\n     * keydown事件先于paste触发\r\n");
    protected static final byte[] _jsp_80042 = b("     * 因此要保证paste被触发必须使Ctrl + V操作返回true\r\n     * 如果Ctrl + V事件存在弹框, 那么root将无法捕获到paste事件\r\n");
    protected static final byte[] _jsp_80043 = b("     * 因为当弹框出现的时候, 弹框是活动窗口, 因此paste事件不会被传递到root\r\n     */\r\n    jQuery(document).keydown(function(event) {\r\n");
    protected static final byte[] _jsp_80044 = b("        var flag = DialogManager.dispatch(\"keydown\", event);\r\n        return flag;\r\n");
    protected static final byte[] _jsp_80045 = b("    });\r\n\r\n    jQuery(document).bind(\"contextmenu\", function(event) {\r\n        var e = (event || window.event);\r\n");
    protected static final byte[] _jsp_80046 = b("        var src = (e.srcElement || e.target);\r\n        var nodeName = src.nodeName.toLowerCase();\r\n");
    protected static final byte[] _jsp_80047 = b("\r\n        if(nodeName == \"input\" || nodeName == \"textarea\") {\r\n            return true;\r\n");
    protected static final byte[] _jsp_80048 = b("        }\r\n        else {\r\n            return DialogManager.dispatch(\"contextmenu\", e);\r\n");
    protected static final byte[] _jsp_80049 = b("        }\r\n    });\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n<body loacalIp=\"");
    protected static final byte[] _jsp_80051 = b("\" contextPath=\"");
    protected static final byte[] _jsp_80053 = b("\" host=\"");
    protected static final byte[] _jsp_80055 = b("\" workspace=\"");
    protected static final byte[] _jsp_80057 = b("\" work=\"");
    protected static final byte[] _jsp_80059 = b("\" path=\"");
    protected static final byte[] _jsp_80061 = b("\">\r\n<div id=\"finder-videodialog\" class=\"media-dialog\" contextmenu=\"false\" style=\"z-index: 1010; margin-top: 0px; margin-left: 0px; display: block;\"></div>\r\n");
    protected static final byte[] _jsp_80062 = b("</body>\r\n</html>\r\n");

}
