/*
 * $RCSfile: SettingMenuTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;


/**
 * <p>Title: SettingMenuTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class SettingMenuTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final SettingMenuTemplate instance = new SettingMenuTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_83359, 0, _jsp_83359.length);
        out.write(_jsp_83360, 0, _jsp_83360.length);
        out.write(_jsp_83361, 0, _jsp_83361.length);
        out.write(_jsp_83362, 0, _jsp_83362.length);
        out.write(_jsp_83363, 0, _jsp_83363.length);
        this.write(out, (App.hash()));
        out.write(_jsp_83365, 0, _jsp_83365.length);
        this.write(out, (App.hash()));
        out.write(_jsp_83367, 0, _jsp_83367.length);
        this.write(out, (App.hash()));
        out.write(_jsp_83369, 0, _jsp_83369.length);
        this.write(out, (App.hash()));
        out.write(_jsp_83371, 0, _jsp_83371.length);
        out.write(_jsp_83372, 0, _jsp_83372.length);
        out.write(_jsp_83373, 0, _jsp_83373.length);
        out.write(_jsp_83374, 0, _jsp_83374.length);
        out.write(_jsp_83375, 0, _jsp_83375.length);
        out.write(_jsp_83376, 0, _jsp_83376.length);
        out.write(_jsp_83377, 0, _jsp_83377.length);
        out.write(_jsp_83378, 0, _jsp_83378.length);
        out.write(_jsp_83379, 0, _jsp_83379.length);
        out.write(_jsp_83380, 0, _jsp_83380.length);
        out.write(_jsp_83381, 0, _jsp_83381.length);
        out.write(_jsp_83382, 0, _jsp_83382.length);
        out.write(_jsp_83383, 0, _jsp_83383.length);
        out.write(_jsp_83384, 0, _jsp_83384.length);
        out.write(_jsp_83385, 0, _jsp_83385.length);
        out.write(_jsp_83386, 0, _jsp_83386.length);
        out.write(_jsp_83387, 0, _jsp_83387.length);
        out.write(_jsp_83388, 0, _jsp_83388.length);
        out.write(_jsp_83389, 0, _jsp_83389.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_83391, 0, _jsp_83391.length);
        out.write(_jsp_83392, 0, _jsp_83392.length);

        out.flush();
    }

    protected static final byte[] _jsp_83359 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_83360 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_83361 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_83362 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_83363 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css&v=");
    protected static final byte[] _jsp_83365 = b("\"/>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/tree.css&v=");
    protected static final byte[] _jsp_83367 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/htree/htree.js&v=");
    protected static final byte[] _jsp_83369 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/htree/htree.util.js&v=");
    protected static final byte[] _jsp_83371 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_83372 = b("<script type=\"text/javascript\">\r\n//<![CDATA[\r\nHTree.mode = \"menu\";\r\nHTree.click = function(src) {\r\n");
    protected static final byte[] _jsp_83373 = b("    var url = src.getAttribute(\"data\");\r\n\r\n    if(url == null || url.length < 1) {\r\n");
    protected static final byte[] _jsp_83374 = b("        return;\r\n    }\r\n\r\n    if(url == \"javascript:void(0);\") {\r\n        return;\r\n");
    protected static final byte[] _jsp_83375 = b("    }\r\n\r\n    try {\r\n        var doc = window.parent.window.document;\r\n        var iframe = doc.getElementById(\"main-frame\");\r\n");
    protected static final byte[] _jsp_83376 = b("\r\n        if(iframe != null) {\r\n            iframe.src = url;\r\n        }\r\n        else {\r\n");
    protected static final byte[] _jsp_83377 = b("            alert(\"系统错误，请稍后再试！\");\r\n        }\r\n    }\r\n    catch(e) {\r\n        if(typeof(window.console) != \"undefined\") {\r\n");
    protected static final byte[] _jsp_83378 = b("            window.console.error(e.name + \": \" + e.message);\r\n        }\r\n        alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_83379 = b("    }\r\n};\r\n\r\nfunction buildTree(id, xmlUrl, rootUrl){\r\n    HTree.config.stylePath = window.location.pathname + \"?action=res&path=/htree/menu/\";\r\n");
    protected static final byte[] _jsp_83380 = b("\r\n    var e = document.getElementById(id);\r\n\r\n    if(e == null) {\r\n        return;\r\n");
    protected static final byte[] _jsp_83381 = b("    }\r\n\r\n    var tree = new HTree.TreeNode({text: \"系统设置\", href: rootUrl, xmlSrc: xmlUrl});\r\n");
    protected static final byte[] _jsp_83382 = b("\r\n    tree.load(function() {\r\n        this.render(document.getElementById(id));\r\n");
    protected static final byte[] _jsp_83383 = b("    });\r\n}\r\n\r\njQuery(function() {\r\n    var resize = function() {\r\n        var e = document.getElementById(\"htree\");\r\n");
    protected static final byte[] _jsp_83384 = b("\r\n        if(e != null) {\r\n            var parent = e.parentNode;\r\n            var offset = parseInt(parent.getAttribute(\"offset-top\"));\r\n");
    protected static final byte[] _jsp_83385 = b("\r\n            if(isNaN(offset)) {\r\n                offset = 0;\r\n            }\r\n\r\n");
    protected static final byte[] _jsp_83386 = b("            var height = document.documentElement.clientHeight - offset;\r\n            parent.style.height = height + \"px\";\r\n");
    protected static final byte[] _jsp_83387 = b("        }\r\n    };\r\n    jQuery(window).load(resize);\r\n    jQuery(window).resize(resize);\r\n");
    protected static final byte[] _jsp_83388 = b("});\r\n\r\njQuery(function() {\r\n    var requestURI = window.location.pathname;\r\n    buildTree(\"htree\", requestURI + \"?action=setting.getMenuXml&r=\" + new Date().getTime(), requestURI + \"?action=finder.blank\");\r\n");
    protected static final byte[] _jsp_83389 = b("});\r\n//]]>\r\n</script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_83391 = b("\">\r\n<div class=\"left-nav\">\r\n    <div class=\"menu-body\">\r\n        <div id=\"htree\" class=\"htree\" style=\"margin-top: 10px; white-space: nowrap;\"></div>\r\n");
    protected static final byte[] _jsp_83392 = b("    </div>\r\n</div>\r\n</body>\r\n</html>\r\n");

}
