/*
 * $RCSfile: SettingXmlTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;



/**
 * <p>Title: SettingXmlTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class SettingXmlTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final SettingXmlTemplate instance = new SettingXmlTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/xml; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_92346, 0, _jsp_92346.length);
        out.write(_jsp_92347, 0, _jsp_92347.length);
        out.write(_jsp_92348, 0, _jsp_92348.length);
        out.write(_jsp_92349, 0, _jsp_92349.length);

        out.flush();
    }

    protected static final byte[] _jsp_92346 = b("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<tree>\r\n<!-- FinderWeb - Powered by FinderWeb -->\r\n");
    protected static final byte[] _jsp_92347 = b("    <treeNode title=\"文本选项\" href=\"?action=setting.text\"/>\r\n    <treeNode title=\"语言设置\" href=\"?action=setting.lang\"/>\r\n");
    protected static final byte[] _jsp_92348 = b("    <treeNode title=\"账号设置\" href=\"#\" expand=\"true\">\r\n        <treeNode title=\"修改密码\" href=\"?action=user.password\"/>\r\n");
    protected static final byte[] _jsp_92349 = b("    </treeNode>\r\n</tree>\r\n");

}
