/*
 * $RCSfile: TailTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;


/**
 * <p>Title: TailTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class TailTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final TailTemplate instance = new TailTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_41762, 0, _jsp_41762.length);
        out.write(_jsp_41763, 0, _jsp_41763.length);
        out.write(_jsp_41764, 0, _jsp_41764.length);
        this.write(out, request.getAttribute("fileName"));
        out.write(_jsp_41766, 0, _jsp_41766.length);
        out.write(_jsp_41767, 0, _jsp_41767.length);
        this.write(out, (App.hash()));
        out.write(_jsp_41769, 0, _jsp_41769.length);
        out.write(_jsp_41770, 0, _jsp_41770.length);
        this.write(out, (App.hash()));
        out.write(_jsp_41772, 0, _jsp_41772.length);
        this.write(out, (App.hash()));
        out.write(_jsp_41774, 0, _jsp_41774.length);
        this.write(out, (App.hash()));
        out.write(_jsp_41776, 0, _jsp_41776.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_41778, 0, _jsp_41778.length);
        this.write(out, request.getAttribute("host"));
        out.write(_jsp_41780, 0, _jsp_41780.length);
        this.write(out, request.getAttribute("workspace"));
        out.write(_jsp_41782, 0, _jsp_41782.length);
        this.write(out, request.getAttribute("parent"));
        out.write(_jsp_41784, 0, _jsp_41784.length);
        this.write(out, request.getAttribute("path"));
        out.write(_jsp_41786, 0, _jsp_41786.length);
        this.write(out, request.getAttribute("charset"));
        out.write(_jsp_41788, 0, _jsp_41788.length);
        out.write(_jsp_41789, 0, _jsp_41789.length);
        this.write(out, request.getAttribute("host"));
        out.write(_jsp_41791, 0, _jsp_41791.length);
        this.write(out, request.getAttribute("workspace"));
        out.write(_jsp_41793, 0, _jsp_41793.length);
        this.write(out, request.getAttribute("path"));
        out.write(_jsp_41795, 0, _jsp_41795.length);
        this.write(out, request.getAttribute("fileName"));
        out.write(_jsp_41797, 0, _jsp_41797.length);
        this.write(out, request.getAttribute("charset"));
        out.write(_jsp_41799, 0, _jsp_41799.length);
        out.write(_jsp_41800, 0, _jsp_41800.length);
        out.write(_jsp_41801, 0, _jsp_41801.length);
        out.write(_jsp_41802, 0, _jsp_41802.length);
        out.write(_jsp_41803, 0, _jsp_41803.length);
        out.write(_jsp_41804, 0, _jsp_41804.length);
        out.write(_jsp_41805, 0, _jsp_41805.length);
        out.write(_jsp_41806, 0, _jsp_41806.length);
        out.write(_jsp_41807, 0, _jsp_41807.length);
        out.write(_jsp_41808, 0, _jsp_41808.length);
        out.write(_jsp_41809, 0, _jsp_41809.length);
        out.write(_jsp_41810, 0, _jsp_41810.length);
        out.write(_jsp_41811, 0, _jsp_41811.length);
        out.write(_jsp_41812, 0, _jsp_41812.length);
        out.write(_jsp_41813, 0, _jsp_41813.length);
        out.write(_jsp_41814, 0, _jsp_41814.length);
        out.write(_jsp_41815, 0, _jsp_41815.length);
        out.write(_jsp_41816, 0, _jsp_41816.length);

        out.flush();
    }

    protected static final byte[] _jsp_41762 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_41763 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_41764 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>tail - ");
    protected static final byte[] _jsp_41766 = b(" - Powered by FinderWeb</title>\r\n<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_41767 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/less.css&v=");
    protected static final byte[] _jsp_41769 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_41770 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/config.js&v=");
    protected static final byte[] _jsp_41772 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/charset.js&v=");
    protected static final byte[] _jsp_41774 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/tail.js&v=");
    protected static final byte[] _jsp_41776 = b("\"></script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_41778 = b("\" host=\"");
    protected static final byte[] _jsp_41780 = b("\" workspace=\"");
    protected static final byte[] _jsp_41782 = b("\" parent=\"");
    protected static final byte[] _jsp_41784 = b("\" path=\"");
    protected static final byte[] _jsp_41786 = b("\" charset=\"");
    protected static final byte[] _jsp_41788 = b("\">\r\n<div id=\"tail-container\" class=\"less-container\" contenteditable=\"true\" spellcheck=\"false\"></div>\r\n");
    protected static final byte[] _jsp_41789 = b("<div class=\"less-status-bar\">\r\n    <div style=\"height: 18px;\">\r\n        <span class=\"file\"><input id=\"less-file\" type=\"text\" class=\"text w240\" readonly=\"true\" title=\"");
    protected static final byte[] _jsp_41791 = b("@");
    protected static final byte[] _jsp_41793 = b("/");
    protected static final byte[] _jsp_41795 = b("\" value=\"");
    protected static final byte[] _jsp_41797 = b("\"/></span>\r\n        <span class=\"charset\"><select name=\"charset\" selected-value=\"");
    protected static final byte[] _jsp_41799 = b("\"></select></span>\r\n        <span class=\"ctrl\">\r\n            <input id=\"tail-reload-btn\" type=\"button\" class=\"button\" value=\"刷 新\"/>\r\n");
    protected static final byte[] _jsp_41800 = b("            <input id=\"tail-clear-btn\" type=\"button\" class=\"button\" value=\"清 空\"/>\r\n");
    protected static final byte[] _jsp_41801 = b("            <input id=\"tail-stop-btn\" type=\"button\" class=\"button\" value=\"停 止\"/>\r\n");
    protected static final byte[] _jsp_41802 = b("            <input id=\"tail-select-btn\" type=\"button\" class=\"button\" value=\"全 选\"/>\r\n");
    protected static final byte[] _jsp_41803 = b("            <input id=\"tail-find-btn\" type=\"button\" class=\"button\" value=\"过 滤\"/>\r\n");
    protected static final byte[] _jsp_41804 = b("        </span>\r\n        <span class=\"pad4\"><input id=\"tail-reload-interval\" type=\"hidden\" class=\"text w30\" value=\"1\"/></span>\r\n");
    protected static final byte[] _jsp_41805 = b("        <span class=\"pad4\"><input id=\"tail-auto-scroll\" type=\"checkbox\" class=\"checkbox\" checked=\"true\"/>自动滚动</span>\r\n");
    protected static final byte[] _jsp_41806 = b("    </div>\r\n</div>\r\n<div id=\"find-panel\" class=\" dialog\" style=\"top: 100px; display: none;\">\r\n");
    protected static final byte[] _jsp_41807 = b("    <div class=\"find-panel\">\r\n        <div>\r\n            查找内容: <input id=\"grep-keyword\" type=\"text\" class=\"grep-keyword\" value=\"\" placeholder=\"正则示例: /finder/.*\\.html\"/>\r\n");
    protected static final byte[] _jsp_41808 = b("            <input id=\"grep-ensure\" type=\"button\" class=\"grep-search\" value=\"确定\"/>\r\n");
    protected static final byte[] _jsp_41809 = b("        </div>\r\n        <div style=\"clear: both; padding-top: 12px; height: 20px;\">\r\n");
    protected static final byte[] _jsp_41810 = b("            <span style=\"float: left; width: 10px; display: inline-block;\"><input id=\"grep-regexp\" type=\"checkbox\" title=\"正则表达式\"/></span>\r\n");
    protected static final byte[] _jsp_41811 = b("            <span style=\"float: left; margin-left: 6px; margin-top: -1px; width: 100px; display: inline-block;\">正则表达式</span>\r\n");
    protected static final byte[] _jsp_41812 = b("        </div>\r\n        <div style=\"clear: both; margin-top: 10px;\">\r\n            <p><span style=\"color: #ff0000;\">提示：</span>快捷键(Ctrl + B)，再次按下可关闭。</p>\r\n");
    protected static final byte[] _jsp_41813 = b("            <p><span style=\"color: #ff0000;\">说明：</span>正则相关文档请参考JavaScript正则表达式 。</p>\r\n");
    protected static final byte[] _jsp_41814 = b("        </div>\r\n        <div style=\"margin-top: 20px; text-align: center;\">\r\n            <input id=\"grep-close\" type=\"button\" class=\"grep-button\" value=\"取消\"/>\r\n");
    protected static final byte[] _jsp_41815 = b("        </div>\r\n    </div>\r\n</div>\r\n<!-- http://www.finderweb.net -->\r\n</body>\r\n");
    protected static final byte[] _jsp_41816 = b("</html>\r\n");

}
