/*
 * $RCSfile: TextConfigTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;


/**
 * <p>Title: TextConfigTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class TextConfigTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final TextConfigTemplate instance = new TextConfigTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_77388, 0, _jsp_77388.length);
        out.write(_jsp_77389, 0, _jsp_77389.length);
        out.write(_jsp_77390, 0, _jsp_77390.length);
        out.write(_jsp_77391, 0, _jsp_77391.length);
        out.write(_jsp_77392, 0, _jsp_77392.length);
        this.write(out, (App.hash()));
        out.write(_jsp_77394, 0, _jsp_77394.length);
        out.write(_jsp_77395, 0, _jsp_77395.length);
        this.write(out, (App.hash()));
        out.write(_jsp_77397, 0, _jsp_77397.length);
        this.write(out, (App.hash()));
        out.write(_jsp_77399, 0, _jsp_77399.length);
        this.write(out, (App.hash()));
        out.write(_jsp_77401, 0, _jsp_77401.length);
        out.write(_jsp_77402, 0, _jsp_77402.length);
        out.write(_jsp_77403, 0, _jsp_77403.length);
        out.write(_jsp_77404, 0, _jsp_77404.length);
        out.write(_jsp_77405, 0, _jsp_77405.length);
        out.write(_jsp_77406, 0, _jsp_77406.length);
        out.write(_jsp_77407, 0, _jsp_77407.length);
        out.write(_jsp_77408, 0, _jsp_77408.length);
        out.write(_jsp_77409, 0, _jsp_77409.length);
        out.write(_jsp_77410, 0, _jsp_77410.length);
        out.write(_jsp_77411, 0, _jsp_77411.length);
        out.write(_jsp_77412, 0, _jsp_77412.length);
        out.write(_jsp_77413, 0, _jsp_77413.length);
        out.write(_jsp_77414, 0, _jsp_77414.length);
        out.write(_jsp_77415, 0, _jsp_77415.length);
        out.write(_jsp_77416, 0, _jsp_77416.length);
        out.write(_jsp_77417, 0, _jsp_77417.length);
        out.write(_jsp_77418, 0, _jsp_77418.length);
        out.write(_jsp_77419, 0, _jsp_77419.length);
        out.write(_jsp_77420, 0, _jsp_77420.length);
        out.write(_jsp_77421, 0, _jsp_77421.length);
        out.write(_jsp_77422, 0, _jsp_77422.length);
        out.write(_jsp_77423, 0, _jsp_77423.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_77425, 0, _jsp_77425.length);
        this.write(out, request.getAttribute("workspace"));
        out.write(_jsp_77427, 0, _jsp_77427.length);
        out.write(_jsp_77428, 0, _jsp_77428.length);
        out.write(_jsp_77429, 0, _jsp_77429.length);
        out.write(_jsp_77430, 0, _jsp_77430.length);
        out.write(_jsp_77431, 0, _jsp_77431.length);
        out.write(_jsp_77432, 0, _jsp_77432.length);
        out.write(_jsp_77433, 0, _jsp_77433.length);
        out.write(_jsp_77434, 0, _jsp_77434.length);
        out.write(_jsp_77435, 0, _jsp_77435.length);
        out.write(_jsp_77436, 0, _jsp_77436.length);
        out.write(_jsp_77437, 0, _jsp_77437.length);
        out.write(_jsp_77438, 0, _jsp_77438.length);
        out.write(_jsp_77439, 0, _jsp_77439.length);
        out.write(_jsp_77440, 0, _jsp_77440.length);
        out.write(_jsp_77441, 0, _jsp_77441.length);
        out.write(_jsp_77442, 0, _jsp_77442.length);
        out.write(_jsp_77443, 0, _jsp_77443.length);
        out.write(_jsp_77444, 0, _jsp_77444.length);
        out.write(_jsp_77445, 0, _jsp_77445.length);
        out.write(_jsp_77446, 0, _jsp_77446.length);
        out.write(_jsp_77447, 0, _jsp_77447.length);
        out.write(_jsp_77448, 0, _jsp_77448.length);
        out.write(_jsp_77449, 0, _jsp_77449.length);
        out.write(_jsp_77450, 0, _jsp_77450.length);
        out.write(_jsp_77451, 0, _jsp_77451.length);
        out.write(_jsp_77452, 0, _jsp_77452.length);
        out.write(_jsp_77453, 0, _jsp_77453.length);
        out.write(_jsp_77454, 0, _jsp_77454.length);
        out.write(_jsp_77455, 0, _jsp_77455.length);
        out.write(_jsp_77456, 0, _jsp_77456.length);
        out.write(_jsp_77457, 0, _jsp_77457.length);
        out.write(_jsp_77458, 0, _jsp_77458.length);
        out.write(_jsp_77459, 0, _jsp_77459.length);
        out.write(_jsp_77460, 0, _jsp_77460.length);

        out.flush();
    }

    protected static final byte[] _jsp_77388 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_77389 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_77390 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Setting - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_77391 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_77392 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/form.css&v=");
    protected static final byte[] _jsp_77394 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_77395 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/charset.js&v=");
    protected static final byte[] _jsp_77397 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/colorpicker.js&v=");
    protected static final byte[] _jsp_77399 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/config.js&v=");
    protected static final byte[] _jsp_77401 = b("\"></script>\r\n<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    var theme = Finder.getConfig(\"global.theme\", \"RDark\");\r\n");
    protected static final byte[] _jsp_77402 = b("    var charset = Finder.getConfig(\"global.charset\", \"utf-8\");\r\n    var fontFamily = Finder.getConfig(\"less.fontFamily\", \"Lucida Console\");\r\n");
    protected static final byte[] _jsp_77403 = b("    var fontColor = Finder.getConfig(\"less.fontColor\", \"#999999\");\r\n    var backgroundColor = Finder.getConfig(\"less.backgroundColor\", \"#000000\");\r\n");
    protected static final byte[] _jsp_77404 = b("    Charset.setup(jQuery(\"select[name=charset]\").get(0), charset);\r\n\r\n    jQuery(\"select[name=theme]\").val(theme);\r\n");
    protected static final byte[] _jsp_77405 = b("    jQuery(\"select[name=fontFamily]\").val(fontFamily);\r\n    jQuery(\"input[name=fontColor]\").val(fontColor);\r\n");
    protected static final byte[] _jsp_77406 = b("    jQuery(\"input[name=backgroundColor]\").val(backgroundColor);\r\n\r\n    jQuery(\"input[name=fontColorPicker]\").css(\"backgroundColor\", fontColor);\r\n");
    protected static final byte[] _jsp_77407 = b("    jQuery(\"input[name=backgroundColorPicker]\").css(\"backgroundColor\", backgroundColor);\r\n");
    protected static final byte[] _jsp_77408 = b("    jQuery(\"#fontExample\").css(\"fontFamily\", fontFamily);\r\n});\r\n\r\njQuery(function() {\r\n");
    protected static final byte[] _jsp_77409 = b("    jQuery(\"input.color-picker\").click(function(event) {\r\n        var position = jQuery(this).position();\r\n");
    protected static final byte[] _jsp_77410 = b("        var x = position.left;\r\n        var y = position.top + jQuery(this).height();\r\n");
    protected static final byte[] _jsp_77411 = b("        var self = jQuery(this);\r\n\r\n        ColorDialog.open(x, y, function(color) {\r\n");
    protected static final byte[] _jsp_77412 = b("            self.css(\"backgroundColor\", color);\r\n            self.parent().find(\"input.color-text\").val(color);\r\n");
    protected static final byte[] _jsp_77413 = b("            ColorDialog.close();\r\n        });\r\n    });\r\n\r\n    jQuery(\"select[name=fontFamily]\").change(function() {\r\n");
    protected static final byte[] _jsp_77414 = b("        jQuery(\"#fontExample\").css(\"fontFamily\", this.value);\r\n    });\r\n\r\n    jQuery(\"#default-btn\").click(function() {\r\n");
    protected static final byte[] _jsp_77415 = b("        jQuery(\"select[name=theme]\").val(\"RDark\");\r\n        jQuery(\"select[name=charset]\").val(\"utf-8\");\r\n");
    protected static final byte[] _jsp_77416 = b("        jQuery(\"select[name=fontFamily]\").val(\"Lucida Console\");\r\n        jQuery(\"input[name=fontColor]\").val(\"#999999\");\r\n");
    protected static final byte[] _jsp_77417 = b("        jQuery(\"input[name=backgroundColor]\").val(\"#000000\");\r\n        jQuery(\"#ensure-btn\").click();\r\n");
    protected static final byte[] _jsp_77418 = b("    });\r\n\r\n    jQuery(\"#ensure-btn\").click(function() {\r\n        var config = {\"global\": {}, \"less\": {}};\r\n");
    protected static final byte[] _jsp_77419 = b("        var global = config.global;\r\n        var lessConfig = config.less;\r\n\r\n        global.theme = jQuery(\"select[name=theme]\").val();\r\n");
    protected static final byte[] _jsp_77420 = b("        global.charset = jQuery(\"select[name=charset]\").val();\r\n\r\n        lessConfig.fontFamily = jQuery(\"select[name=fontFamily]\").val();\r\n");
    protected static final byte[] _jsp_77421 = b("        lessConfig.fontColor = jQuery(\"input[name=fontColor]\").val();\r\n        lessConfig.backgroundColor = jQuery(\"input[name=backgroundColor]\").val();\r\n");
    protected static final byte[] _jsp_77422 = b("        Finder.setFinderConfig(config);\r\n        alert(\"保存成功！\");\r\n    });\r\n});\r\n");
    protected static final byte[] _jsp_77423 = b("//-->\r\n</script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_77425 = b("\" workspace=\"");
    protected static final byte[] _jsp_77427 = b("\">\r\n<div id=\"finder-panel\" class=\"form\">\r\n    <div class=\"title\"><h4>文本选项</h4></div>\r\n");
    protected static final byte[] _jsp_77428 = b("    <div class=\"form-row\">\r\n        <div class=\"form-label\">主题：</div>\r\n        <div class=\"form-c300\">\r\n");
    protected static final byte[] _jsp_77429 = b("            <div class=\"form-field\">\r\n                <select name=\"theme\">\r\n                    <option value=\"Django\">Django</option>\r\n");
    protected static final byte[] _jsp_77430 = b("                    <option value=\"Eclipse\">Eclipse</option>\r\n                    <option value=\"Emacs\">Emacs</option>\r\n");
    protected static final byte[] _jsp_77431 = b("                    <option value=\"FadeToGrey\">FadeToGrey</option>\r\n                    <option value=\"MDUltra\">MDUltra</option>\r\n");
    protected static final byte[] _jsp_77432 = b("                    <option value=\"Midnight\">Midnight</option>\r\n                    <option value=\"RDark\">RDark</option>\r\n");
    protected static final byte[] _jsp_77433 = b("                </select>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n");
    protected static final byte[] _jsp_77434 = b("            <div class=\"form-comment\">主题。</div>\r\n        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n");
    protected static final byte[] _jsp_77435 = b("        <div class=\"form-label\">字符集：</div>\r\n        <div class=\"form-c300\">\r\n            <div class=\"form-field\"><select name=\"charset\"></select></div>\r\n");
    protected static final byte[] _jsp_77436 = b("        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">字符集。工作空间设置的字符集优先于此处的设置。</div>\r\n");
    protected static final byte[] _jsp_77437 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">字体：</div>\r\n");
    protected static final byte[] _jsp_77438 = b("        <div class=\"form-c300\">\r\n            <div class=\"form-field\">\r\n                <select name=\"fontFamily\">\r\n");
    protected static final byte[] _jsp_77439 = b("                    <option value=\"Andale Mono\">Andale Mono</option>\r\n                    <option value=\"Anonymous\">Anonymous</option>\r\n");
    protected static final byte[] _jsp_77440 = b("                    <option value=\"Consolas\">Consolas</option>\r\n                    <option value=\"Courier New\">Courier New</option>\r\n");
    protected static final byte[] _jsp_77441 = b("                    <option value=\"Dejavu\">Dejavu</option>\r\n                    <option value=\"DroidMono\">DroidMono</option>\r\n");
    protected static final byte[] _jsp_77442 = b("                    <option value=\"EnvyR\">EnvyR</option>\r\n                    <option value=\"FiraCode\">FiraCode</option>\r\n");
    protected static final byte[] _jsp_77443 = b("                    <option value=\"Hasklig\">Hasklig</option>\r\n                    <option value=\"InputMono\">InputMono</option>\r\n");
    protected static final byte[] _jsp_77444 = b("                    <option value=\"liberation\">liberation</option>\r\n                    <option value=\"Lucida Console\">Lucida Console</option>\r\n");
    protected static final byte[] _jsp_77445 = b("                    <option value=\"LucidaMono\">LucidaMono</option>\r\n                    <option value=\"Monaco\">Monaco</option>\r\n");
    protected static final byte[] _jsp_77446 = b("                    <option value=\"Monoid\">Monoid</option>\r\n                    <option value=\"Profont\">Profont</option>\r\n");
    protected static final byte[] _jsp_77447 = b("                    <option value=\"SourceCode\">SourceCode</option>\r\n                    <option value=\"UbuntuMono\">UbuntuMono</option>\r\n");
    protected static final byte[] _jsp_77448 = b("                </select>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n");
    protected static final byte[] _jsp_77449 = b("            <div id=\"fontExample\">我是字体示例 abcd ABCD 123</div>\r\n        </div>\r\n    </div>\r\n");
    protected static final byte[] _jsp_77450 = b("    <div class=\"form-row\">\r\n        <div class=\"form-label\">字体颜色：</div>\r\n        <div class=\"form-c300\">\r\n");
    protected static final byte[] _jsp_77451 = b("            <div class=\"form-field\">\r\n                <input name=\"fontColor\" type=\"text\" class=\"color-text\" value=\"\"/>\r\n");
    protected static final byte[] _jsp_77452 = b("                <input name=\"fontColorPicker\" type=\"text\" class=\"color-picker\" readonly=\"true\" value=\"\"/>\r\n");
    protected static final byte[] _jsp_77453 = b("            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">字体颜色。</div>\r\n");
    protected static final byte[] _jsp_77454 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">背景颜色：</div>\r\n");
    protected static final byte[] _jsp_77455 = b("        <div class=\"form-c300\">\r\n            <div class=\"form-field\">\r\n                <input name=\"backgroundColor\" type=\"text\" class=\"color-text\" value=\"\"/>\r\n");
    protected static final byte[] _jsp_77456 = b("                <input name=\"backgroundColorPicker\" type=\"text\" class=\"color-picker\" readonly=\"true\" value=\"\"/>\r\n");
    protected static final byte[] _jsp_77457 = b("            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">背景颜色。</div>\r\n");
    protected static final byte[] _jsp_77458 = b("        </div>\r\n    </div>\r\n    <div class=\"button\">\r\n        <button id=\"default-btn\" class=\"button\">恢复默认</button>\r\n");
    protected static final byte[] _jsp_77459 = b("        <button id=\"ensure-btn\" class=\"button ensure\">确 定</button>\r\n    </div>\r\n");
    protected static final byte[] _jsp_77460 = b("</div>\r\n</body>\r\n</html>\r\n");

}
