/*
 * $RCSfile: ZipViewTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 * http://www.finderweb.net
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.App;
import com.skin.finder.config.ConfigFactory;
import com.skin.finder.i18n.I18N;
import com.skin.finder.i18n.LocalizationContext;


/**
 * <p>Title: ZipViewTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class ZipViewTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final ZipViewTemplate instance = new ZipViewTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();


    LocalizationContext i18n = I18N.getBundle(request);

        out.write(_jsp_13622, 0, _jsp_13622.length);
        out.write(_jsp_13623, 0, _jsp_13623.length);
        out.write(_jsp_13624, 0, _jsp_13624.length);
        out.write(_jsp_13625, 0, _jsp_13625.length);
        out.write(_jsp_13626, 0, _jsp_13626.length);
        this.write(out, (App.hash()));
        out.write(_jsp_13628, 0, _jsp_13628.length);
        this.write(out, (App.hash()));
        out.write(_jsp_13630, 0, _jsp_13630.length);
        out.write(_jsp_13631, 0, _jsp_13631.length);
        this.write(out, (App.hash()));
        out.write(_jsp_13633, 0, _jsp_13633.length);
        this.write(out, (App.hash()));
        out.write(_jsp_13635, 0, _jsp_13635.length);
        this.write(out, (App.hash()));
        out.write(_jsp_13637, 0, _jsp_13637.length);
        this.write(out, (i18n.getLang()));
        out.write(_jsp_13639, 0, _jsp_13639.length);
        this.write(out, (App.hash()));
        out.write(_jsp_13641, 0, _jsp_13641.length);
        this.write(out, (App.hash()));
        out.write(_jsp_13643, 0, _jsp_13643.length);
        this.write(out, (App.hash()));
        out.write(_jsp_13645, 0, _jsp_13645.length);
        this.write(out, request.getAttribute("remoteIp"));
        out.write(_jsp_13647, 0, _jsp_13647.length);
        this.write(out, request.getAttribute("host"));
        out.write(_jsp_13649, 0, _jsp_13649.length);
        this.write(out, request.getAttribute("workspace"));
        out.write(_jsp_13651, 0, _jsp_13651.length);
        this.write(out, request.getAttribute("path"));
        out.write(_jsp_13653, 0, _jsp_13653.length);
        out.write(_jsp_13654, 0, _jsp_13654.length);
        this.write(out, (i18n.getString("finder.button.back")));
        out.write(_jsp_13656, 0, _jsp_13656.length);
        this.write(out, (i18n.getString("finder.button.refresh")));
        out.write(_jsp_13658, 0, _jsp_13658.length);
        out.write(_jsp_13659, 0, _jsp_13659.length);
        this.write(out, (i18n.getString("finder.list.title.file-name")));
        out.write(_jsp_13661, 0, _jsp_13661.length);
        this.write(out, (i18n.getString("finder.list.title.file-size")));
        out.write(_jsp_13663, 0, _jsp_13663.length);
        this.write(out, (i18n.getString("finder.list.title.file-type")));
        out.write(_jsp_13665, 0, _jsp_13665.length);
        this.write(out, (i18n.getString("finder.list.title.last-modified")));
        out.write(_jsp_13667, 0, _jsp_13667.length);
        out.write(_jsp_13668, 0, _jsp_13668.length);
        out.write(_jsp_13669, 0, _jsp_13669.length);
        out.write(_jsp_13670, 0, _jsp_13670.length);
        this.write(out, (App.getVersion()));
        out.write(_jsp_13672, 0, _jsp_13672.length);
        this.write(out, (ConfigFactory.getEnvName()));
        out.write(_jsp_13674, 0, _jsp_13674.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_13676, 0, _jsp_13676.length);
        this.write(out, request.getAttribute("admin"));
        out.write(_jsp_13678, 0, _jsp_13678.length);
        this.write(out, (App.hash()));
        out.write(_jsp_13680, 0, _jsp_13680.length);
        this.write(out, (i18n.getLang()));
        out.write(_jsp_13682, 0, _jsp_13682.length);
        this.write(out, (ConfigFactory.getTextType()));
        out.write(_jsp_13684, 0, _jsp_13684.length);
        this.write(out, (ConfigFactory.getUploadPartSize()));
        out.write(_jsp_13686, 0, _jsp_13686.length);
        this.write(out, (ConfigFactory.getOperateButton()));
        out.write(_jsp_13688, 0, _jsp_13688.length);
        this.write(out, (App.getVersion()));
        out.write(_jsp_13690, 0, _jsp_13690.length);
        this.write(out, request.getAttribute("hasNewVersion"));
        out.write(_jsp_13692, 0, _jsp_13692.length);
        out.write(_jsp_13693, 0, _jsp_13693.length);

        out.flush();
    }

    protected static final byte[] _jsp_13622 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_13623 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_13624 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>FinderWeb - Powered by FinderWeb</title>\r\n");
    protected static final byte[] _jsp_13625 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_13626 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/finder.css&v=");
    protected static final byte[] _jsp_13628 = b("\"/>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/widget.css&v=");
    protected static final byte[] _jsp_13630 = b("\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.12.4.min.js\"></script>\r\n");
    protected static final byte[] _jsp_13631 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/widget.js&v=");
    protected static final byte[] _jsp_13633 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/finder.js&v=");
    protected static final byte[] _jsp_13635 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/fileupload.js&v=");
    protected static final byte[] _jsp_13637 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/lang/");
    protected static final byte[] _jsp_13639 = b(".js&v=");
    protected static final byte[] _jsp_13641 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/plugins.js&v=");
    protected static final byte[] _jsp_13643 = b("\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/zip-viewer.js&v=");
    protected static final byte[] _jsp_13645 = b("\"></script>\r\n</head>\r\n<body style=\"overflow: hidden;\" remoteIp=\"");
    protected static final byte[] _jsp_13647 = b("\" data-host=\"");
    protected static final byte[] _jsp_13649 = b("\" data-workspace=\"");
    protected static final byte[] _jsp_13651 = b("\" data-path=\"");
    protected static final byte[] _jsp_13653 = b("\">\r\n<div class=\"view-panel\" style=\"top: 0px; bottom: 0px;\">\r\n    <div id=\"loading\" class=\"loading-mask\" style=\"display: block;\"><div class=\"loading\"><img src=\"?action=res&path=/finder/images/loading.gif\"/></div></div>\r\n");
    protected static final byte[] _jsp_13654 = b("    <div class=\"addr-bar\" contextmenu=\"false\">\r\n        <div class=\"b1\">\r\n            <span id=\"back\" class=\"button\" title=\"");
    protected static final byte[] _jsp_13656 = b("\"><i class=\"back\"></i></span>\r\n            <span id=\"refresh\" class=\"button\" title=\"");
    protected static final byte[] _jsp_13658 = b("\"><i class=\"refresh\"></i></span>\r\n        </div>\r\n    </div>\r\n    <div id=\"head-view\" class=\"head-view\" draggable=\"false\">\r\n");
    protected static final byte[] _jsp_13659 = b("        <span class=\"file-name orderable\" orderBy=\"file-name\" unselectable=\"on\" onselectstart=\"return false;\"><em class=\"title\">");
    protected static final byte[] _jsp_13661 = b("</em><em class=\"order asc\"></em></span>\r\n        <span class=\"file-size orderable\" orderBy=\"file-size\" unselectable=\"on\" onselectstart=\"return false;\"><em class=\"title\">");
    protected static final byte[] _jsp_13663 = b("</em><em class=\"order\"></em></span>\r\n        <span class=\"file-type orderable\" orderBy=\"file-type\" unselectable=\"on\" onselectstart=\"return false;\"><em class=\"title\">");
    protected static final byte[] _jsp_13665 = b("</em><em class=\"order\"></em></span>\r\n        <span class=\"modified orderable\" orderBy=\"modified\" unselectable=\"on\" onselectstart=\"return false;\"><em class=\"title\">");
    protected static final byte[] _jsp_13667 = b("</em><em class=\"order\"></em></span>\r\n        <span class=\"operate\"><em class=\"title\">&nbsp;</em></span>\r\n");
    protected static final byte[] _jsp_13668 = b("    </div>\r\n    <div id=\"file-view\" class=\"file-view\" contextmenu=\"true\" draggable=\"false\" data-frame=\"false\">\r\n");
    protected static final byte[] _jsp_13669 = b("        <div id=\"info-view\" class=\"info-view\" contextmenu=\"false\"></div>\r\n        <ul id=\"file-list\" class=\"detail-view\"></ul>\r\n");
    protected static final byte[] _jsp_13670 = b("        <div id=\"watermark\" class=\"watermark\">Powered by FinderWeb v");
    protected static final byte[] _jsp_13672 = b("</div>\r\n    </div>\r\n</div>\r\n<div id=\"pageContext\" style=\"display: none;\"\r\n    data-env-name=\"");
    protected static final byte[] _jsp_13674 = b("\"\r\n    data-context-path=\"");
    protected static final byte[] _jsp_13676 = b("\"\r\n    data-admin=\"");
    protected static final byte[] _jsp_13678 = b("\"\r\n    data-hash=\"");
    protected static final byte[] _jsp_13680 = b("\"\r\n    data-lang=\"");
    protected static final byte[] _jsp_13682 = b("\"\r\n    data-text-type=\"");
    protected static final byte[] _jsp_13684 = b("\"\r\n    data-upload-part-size=\"");
    protected static final byte[] _jsp_13686 = b("\"\r\n    data-display-operate-button=\"");
    protected static final byte[] _jsp_13688 = b("\"\r\n    data-version=\"");
    protected static final byte[] _jsp_13690 = b("\"\r\n    data-upgrade-tips=\"");
    protected static final byte[] _jsp_13692 = b("\"></div>\r\n<!-- http://www.finderweb.net -->\r\n<!-- http://www.finderweb.net -->\r\n");
    protected static final byte[] _jsp_13693 = b("</body>\r\n</html>\r\n");

}
